### ISSUE TITLE
DesignToolsServerException using WebView2 on Winforms app

### ISSUE THREAD

**Issue by scovetta** [MicrosoftEdge/WebView2Feedback#1006]
**Description**
I am trying to add a web browser control to a new WinForms app. After I add the WebView2 NuGet package and try to use it, I get a stack trace / alert. I am also unable to do anything with with the project -- e.g. clicking elsewhere in the app GUI shows things like:

![image](https://user-images.githubusercontent.com/732166/109398069-32d0e580-78ef-11eb-8655-d54a919d6b5f.png)

The error in the alert is:
```
---------------------------
Microsoft Visual Studio
---------------------------
Failed to create component 'WebView2'.  The error message follows:

'Microsoft.VisualStudio.WinForms.RemoteClient.DesignToolsServerException: Could not load type 'System.Windows.Forms.ContextMenu' from assembly 'System.Windows.Forms, Version=5.0.3.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

   at Microsoft.VisualStudio.WinForms.RemoteClient.DesignToolsClient.<SendRequestAsync>d__49`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()

   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()

   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)

   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)

   at Microsoft.VisualStudio.WinForms.RemoteClient.DesignToolsClient.Microsoft.DotNet.DesignTools.Protocol.Endpoints.IRequestSender.SendRequest[TRequest,TResponse](String name, TRequest request)

   at Microsoft.VisualStudio.WinForms.Protocol.Endpoints.DesignerHosts.CreateComponentEndpoint.Sender.SendRequest(SessionId sessionId, TypeIdentity type, String name, DefaultComponentValues defaultValues)

   at Microsoft.VisualStudio.WinForms.Protocol.Endpoints.WinFormsEndpoints.DesignerHostsImpl.CreateComponent(SessionId sessionId, TypeIdentity type, String name, DefaultComponentValues defaultValues)

   at Microsoft.VisualStudio.WinForms.RemoteClient.Toolbox.WinFormsToolboxItem.CreateComponentsCore(IDesignerHost host, IDictionary defaultValues)

   at System.Drawing.Design.ToolboxItem.CreateComponents(IDesignerHost host, IDictionary defaultValues)

   at Microsoft.VisualStudio.Windows.Forms.Design.OleDragDropHandler.CreateTool(ToolboxItem tool, ControlProxy parent, Int32 x, Int32 y, Int32 width, Int32 height, Boolean hasLocation, Boolean hasSize, ToolboxSnapDragDropEventArgs snapDragDropEventArgs)'
---------------------------
OK   
---------------------------
```

**Version**
SDK: VS 2019 16.8.6
Runtime: n/a
Framework: .NET 3.1 and .NET 5 (tried both, neither work)
OS: Win10 (current)

**Repro Steps**

1. Create a new Windows Forms App (.NET).
2. Install the NuGet Microsoft.Web.WebView2 (1.0.705.50).
3. Drag the new WebView2 control onto the form.
4. See the error called out above and in the image below.

I installed the WebView2 developer package, no change.

**Screenshots**
![image](https://user-images.githubusercontent.com/732166/109398010-ed141d00-78ee-11eb-9811-4c2659f6983e.png)

**Additional context**

**Comment by scovetta** [comment]
This appears to work when targeting .NET Framework, but not .NET 3.1 or .NET 5.

**Comment by pagoe-msft** [comment]
@scovetta The Web Browser Control does not support .NET 3.1 or .NET 5 as far as I am aware. If you are building a new application - I'd highly recommend using WebView2 based on Microsoft Edge (Chromium) which supports modern web standards and .NET 3.1/.NET5. 

Here's a link to get started: https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms

**Comment by scovetta** [comment]
Thanks @pagoe-msft -- But I was using webview2 -- it seems to work fine in Framework but not in Core.

**Comment by champnic** [comment]
Hey @scovetta - I believe this issue has been fixed in the latest package. Can you see if you still repro the issue using the 1.0.790-prerelease package?

**Comment by scovetta** [comment]
Thank you @champnic! Yes, it's working in 1.0.790-prerelease -- both under .NET Core 3.1 and .NET 5.
