### ISSUE TITLE
WebView2Loader.dll is missing from the Installer Folder.

### ISSUE THREAD

**Issue by Gopal-23** [MicrosoftEdge/WebView2Feedback#1121]
I am using Microsoft.Web.WebView2.1.0.790-prerelease NuGet package in my WPF application which is targeting the .NET 4.6.2 Framework.
Getting this exception when packaging the app:
Initializing Error:System.DllNotFoundException: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Windstream.Desktop.WeConnect.Views.LogInPage.<InitializeWebViewCoreAsync>d__20.MoveNext()

**Comment by champnic** [comment]
Hey @Gopal-23 - thanks for the report. Could you add some detail around how you are packaging and deploying your app?

**Comment by RickStrahl** [comment]
Perhaps this is related to #1133?

**Comment by Gopal-23** [comment]
> Hey @Gopal-23 - thanks for the report. Could you add some detail around how you are packaging and deploying your app?

Hey @champnic, 
Now working, 
Like I manually added this into my Wix MSI packing:

 <Component Id="WebView2Loader" Guid="xxx.xxx">
		<File Source="$(var.TargetDir)\runtimes\win-x86\native\WebView2Loader.dll"/>				
</Component>

So just to know, when we run our app with VS 2019 it automatically adds the runtime folder into the Bin>Release Folder, so why not in the WIX installer. And also there is no proper guidance in the DOC of Packaging related to WIX Installer.

**Comment by champnic** [comment]
Glad it's working for you now. Yes that file needs to be deployed with the app. I'm not sure why VS automatically adds the folder but WiX doesn't. We have samples of WiX deployment in our sample repo: https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps

@DavidShoe Do we have docs describing how to do this? Maybe we should link to the samples from the "Distributing your app" doc. And do you know if WiX should be picking up the dependencies itself automatically?
