### ISSUE TITLE
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

### ISSUE THREAD

**Issue by Yoda-Man** [MicrosoftEdge/WebView2Feedback#1176]
API Version 1.7.7.78
Source : mscorlib
Message
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
Stack Trace
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WorkBench.ScanningControl.<InitializeAsync>d__12.MoveNext()

**Comment by champnic** [comment]
Hey @Yoda-Man - E_ACCESSDENIED is usually thrown when the runtime can't create/write to the user data folder location (for example, the default location is next to the exe, which can sometimes be in C:\Program Files, etc.). You can set the user data folder to something else, like a folder in application data, and see if that resolves the issue. Let me know if it doesn't or you need help. Thanks!
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder
