### ISSUE TITLE
CoreWebView2CookieManager cookies can only be accessed from Main Thread

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#1283]
**Description**
When calling `CoreWebView2CookieManager.GetCookiesAsync(null)` from non-Main thread, **the call succeeds** (cookies are returned), but **attempting to access a cookie's property (e.g. `c.Domain`) throws an exception.** 

Either this is an issue in WebView2 that needs to be addressed, or it's working as expected and the documentation should make it clear that cookie properties can not be read from non-main thread. 

Exception:

`{"Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2CookieManager'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{177CD9E7-B6F5-451A-94A0-5D7A3A4C4141}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE))."}` 

Stack trace:

```
   at Microsoft.Web.WebView2.Core.CoreWebView2CookieManager.get__nativeICoreWebView2CookieManager()
   at Microsoft.Web.WebView2.Core.CoreWebView2CookieManager.<GetCookiesAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at WpfApp1.MainWindow.<<Button_OnClick>b__2_0>d.MoveNext() in [..]
```

**Version**
SDK: 
Runtime: Evergreen 90.0.818.56
Framework: WPF, .NET 5
OS:  Windows 10 x64, 20H2 (19042.985)

**Repro Steps**

- Create a WPF app with a WebView2 with Source set to `https://www.bing.com`
- Create a button and add a handler:
```
        private void Button_OnClick(object sender, RoutedEventArgs e)
        {
            // This runs in Main thread
            this.cookieManager = this.ww2.CoreWebView2.CookieManager;

            var t = new Thread(async () =>
            {
                try
                {
                    // This succeeds, even though called from non-main thread
                    var cookies = await this.cookieManager.GetCookiesAsync(null).ConfigureAwait(false);
                    var firstCookie = cookies.First();

                    // This fails when trying to access .Domain
                    Debug.WriteLine($"Domain: {firstCookie.Domain}");
                }
                catch (Exception e)
                {
                    Debugger.Break();
                }
            });
            t.Start();
        }
```
- Run the project and click the button

Expected:

- Cookie's domain is printed to Debug

Actual:
 
- Exception is thrown when `cookie.Domain` is accessed

**Comment by champnic** [comment]
@RendijsSmukulis In general the WebView2 control is single-threaded and should only be called on the thread it was created on. In your example, I'm assuming the WebView2 was created on the main thread? If so the is indeed By Design and we have documentation here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model

Rather than linking to the threading model on every API, is there somewhere you think we should link to this information from to make it more clear? Maybe a "Required Reading" section that's linked from the main page or the Getting Started guides as a next step?

**Comment by RendijsSmukulis** [comment]
@champnic thanks for the quick response!

Since this code fails even when `GetCookiesAsync()` itself is called from the main thread, I think the surprising moment here was the fact that a returned cookie's property also needs to be accessed from the UI thread, I presume due to a lazy-loading implementation. I'd argue that the documentation makes it clear that WebView2 methods should be accessed from the main thread, but not so much about the returned object properties. Maybe that's worth a call-out on the threading model page?

**Comment by champnic** [comment]
That's a great idea - I've added a work item for us to update the docs. Thanks!
