### ISSUE TITLE
WebView2 fails to initialize on Outlook with Exception (0x8007139F)

### ISSUE THREAD

**Issue by tiagoabreu** [MicrosoftEdge/WebView2Feedback#1464]
**Description**
We have a working VSTO Add-in that uses WebView2 and for a specific user, WebView2 fails to initialize every time. I also tried with a minimal add-in with just a WebView2 window on a task pane and I get the same result.
The exception, taken from the InitializationException property on the event InitializationCompleted, is as follow:

```
System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
```

How can I get to the root cause of the error? The same add-in on other Office applications work fine for the same user.

**Version**
SDK: 1.0.864.35
Runtime: Runtime 91.0.864.59
Framework: WinForms
OS: Win10 21H1, Outlook 16.0.14131.20116 64-bit.

**Repro Steps**

1. Open a task pane with a WebView2 in Outlook.
2. Check event InitializationCompleted

Expected: Initialization is Successful
Actual: Initialization fails with provided exception

We specify a UserData folder, but it is not shared by applications other than Outlook.
No special properties are set in the initialization.

**Comment by champnic** [comment]
Hey @tiagoabreu - I've added this to our backlog. It sounds like there is something strange in the configuration of that particular machine. I'll reach out to the team to see if there's any logging or dumps that would be helpful in diagnosing this.

**Comment by champnic** [comment]
@tiagoabreu If the same user data folder is being shared between multiple add-ins (or instances of the add-in) then the main runtime processes (msedgewebview2.exe with no `--type=` arg) need to have the same command line args, including DPI awareness (which is usually the part that can differ between instances and trip-up). For the user, can you have them verify that there are no other instances of WebView2 running (msedgewebview2.exe in Task Manager) and see if that resolves the issue?

**Comment by darbid** [comment]
"need to have the same command line args, including DPI awareness"

@champnic could you please link to more info on this. I'm thinking of adding Webview2 through vsto to excel but I would like to use the same data folder to keep the same session going.

**Comment by champnic** [comment]
Hey @darbid - you can read more here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder#share-user-data-folders

Let me know if you'd like more info or think something is missing and we can try to answer + update that doc. Thanks!

**Comment by tiagoabreu** [comment]
Hello @champnic ,

The folder is not used by other add-ins. We do publish the add-in in other Office applications, but we have separate user data folders for each Office application.

We tested and made sure no other WebView2 instances were running.
Anything else we can try or check?

**Comment by champnic** [comment]
Have you verified that the DPI awareness of the host exe and the runtime processes (msedgewebview2.exe) match up? I'm working through a similar bug right now, where the host app is getting launched as DPI UNAWARE, but the runtime process is getting launched as PER_MONITOR_AWARE and this causes an 0x8007139F error.

You can check DPI awareness in Task Manager > Details tab (need to display "DPI Awareness" column)

**Comment by tiagoabreu** [comment]
This was not easy to check, because the processes close very fast. I assume that they crash.

The first process that appeared on the task manager was indeed with DPI UNAWARE and other processes that appeared had the value PER_MONITOR_AWARE.

On my system, where everything works fine, the main process has the DPI value UNAWARE  and remaining processes are a mix between SYSTEM and UNAWARE.

**Comment by tiagoabreu** [comment]
Hey @champnic ,

Is there any workaround we can apply in the meantime for this issue?

**Comment by tiagoabreu** [comment]
Hello @champnic ,

Do you have any updates on this issue specially if there are any workarounds available for us to use?

**Comment by champnic** [comment]
Unfortunately I'm unaware of a workaround at this time. You could try setting your app to different DPI awareness to match what the browser processes are trying to launch as to see if that resolves the issue and confirms the hypothesis. Our expert on DPI awareness is out until next week, but I'll ask them to take a look when they get back.

**Comment by tiagoabreu** [comment]
@champnic Do you have an update regarding this issue?

We were not able to get a setup to test that hypothesis unfortunately.

**Comment by champnic** [comment]
No update on our side. Are you able to test with newer SDK/Runtime versions to see if the issue might be resolved?

**Comment by tiagoabreu** [comment]
@champnic We tested this today with the latest stable version (1.0.1020.30) on latest WebView2 runtime (95.0.1020.40).
The behaviour is exactly the same, we checked for dumps on the `EBWebView\Crashpad\reports` folder and it came up empty.

Anything else we can check?

**Comment by tiagoabreu** [comment]
Hello @champnic ,

Do you know if there are any recent changes, maybe related to DPIs, that can help us figure out what is the issue here?

We do have other users reporting the same thing when opening Word from other applications (in their case, eDocs) but we do not know where can we look further.

**Comment by champnic** [comment]
If you can reproduce the bug under a debugger you can try looking at the output to see if it has any clues. We started putting some error/warning messages there that might help.

**Comment by tiagoabreu** [comment]
Unfortunately no, we could not reproduce it on our development machines. Is there any extra event we can listen to, to write logs about?
Or anything we can check on the UserData folder? As mentioned before, `EBWebView\Crashpad\reports` came back empty.

We have different use cases where this is happening and it is not consistent at all.

Also, this is a child control within VSTO, so it inherits DPI settings from the parent (in this case, Office).
