### ISSUE TITLE
Unable to use Fixed Runtime from UNC Path

### ISSUE THREAD

**Issue by damienpra** [MicrosoftEdge/WebView2Feedback#1478]
**Description**
I'm trying to create a WinForm using the WebView2 control. This is built in an old version of .Net as it's a plugin for a proprietary piece of software. Having said that, everything works well on my development environment and I wished to make this available in our production WVD environment. As the WebView runtime is not available, I decided to use the Fixed Runtime version as it is easiest for me to deploy.

The behaviour that I am experiencing, is that if I use a UNC path for the BrowserExecutableFolder, then I get an exception relating to the control being disposed. Actually, using the UNC path from my development environment has the same issue. If I point the BrowserExecutableFolder to the same fixed runtime on the local drive of my dev environment then it works perfectly. Any ideas why I can't use the fixed runtime from a UNC path?

System.InvalidOperationException
  HResult=0x80131509
  Message=CoreWebView2 members cannot be accessed after the WebView2 control is disposed.
  Source=Microsoft.Web.WebView2.Core
  StackTrace:
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   at Microsoft.Web.WebView2.WinForms.WebView2.OnGotFocus(EventArgs e)
   at System.Windows.Forms.Control.InvokeGotFocus(Control toInvoke, EventArgs e)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Inner Exception 1:
COMException: The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)

**Version**
SDK: WebView2 v1.0.864.35
Runtime: 91.0.864.59.x86
Framework: WinForms
OS: Windows 10

**Repro Steps**
With the WebView2 control on a WinForm.
Download the Fixed runtime and extract it to a network share.
Set BrowserExecutableFolder to the UNC path for the runtime.
Exception happens when this.ShowDialog(initPluginData.Owner); is executed

**Comment by champnic** [comment]
Hey @damienpra - Please see #1370. It's currently a limitation that you can't use the Fixed Version binaries from a network location. If you'd like I can change this to a feature request (and I'm guessing we need to update our docs to make the current limitation clear).

**Comment by damienpra** [comment]
> Hey @damienpra - Please see #1370. It's currently a limitation that you can't use the Fixed Version binaries from a network location. If you'd like I can change this to a feature request (and I'm guessing we need to update our docs to make the current limitation clear).

Hi @champnic , if you can change this to a feature request that will be great. Given our environment, being able to load the runtime like that, would be hugely beneficial.

**Comment by rvassal** [comment]
Hi, I am also interested in this feature

**Comment by movedoa** [comment]
We are also depending on this feature. We can't use webview2 until this is possible.

**Comment by Stormwalker** [comment]
Hi - just started integrating WebView2 into our apps - this feature would be extremely useful to encourage users.

**Comment by RubenBonillaLluch** [comment]
So, this has been a feature request since 2021 and nothing has changed yet. Nice. I changed a whole application from CefSharp to WebView2 without knowing about this issue :)
