### ISSUE TITLE
WebView2 is not loading/initialized,

### ISSUE THREAD

**Issue by prashant-mhase** [MicrosoftEdge/WebView2Feedback#1505]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x800705B4): This operation returned because the timeout period expired. (Exception from HRESULT: 0x800705B4)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WinForms_GettingStarted.Form1.<InitializeAsync>d__3.MoveNext() in C:\Users\Prashant.Mhase\Downloads\WebView2Samples-master\GettingStartedGuides\WinForms_GettingStarted\Form1.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WinForms_GettingStarted.Form1.<Form1_Load>d__6.MoveNext() in C:\Users\Prashant.Mhase\Downloads\WebView2Samples-master\GettingStartedGuides\WinForms_GettingStarted\Form1.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
WinForms_GettingStarted
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/x6001/Documents/ScreenConnect/Files/Debug/WinForms_GettingStarted.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.864.35
    Win32 Version: 1.0.864.35
    CodeBase: file:///C:/Users/x6001/Documents/ScreenConnect/Files/Debug/Microsoft.Web.WebView2.WinForms.DLL
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.864.35
    Win32 Version: 1.0.864.35
    CodeBase: file:///C:/Users/x6001/Documents/ScreenConnect/Files/Debug/Microsoft.Web.WebView2.Core.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

System.Runtime.InteropServices.COMException (0x800705B4): This operation returned because the timeout period expired. (Exception from HRESULT: 0x800705B4)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WinForms_GettingStarted.Form1.<InitializeAsync>d__3.MoveNext() in 
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

Faulting application name: WebView2WpfBrowser.exe, version: 1.0.0.0, time stamp: 0x8075128b
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1023, time stamp: 0x924f9cdb
Exception code: 0xe0434352
Fault offset: 0x0000000000034b89
Faulting process id: 0xa44
Faulting application start time: 0x01d7724dbde2018a
Faulting application path: 
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: fa817186-ac72-472e-a7bf-b1aaf34d365a
Faulting package full name: 
Faulting package-relative application ID: 

![image](https://user-images.githubusercontent.com/20657117/124761709-b2cb2400-df4f-11eb-9711-650dd2c03ee9.png)
![image](https://user-images.githubusercontent.com/20657117/124761775-c70f2100-df4f-11eb-8c17-3c583c56269a.png)
![image](https://user-images.githubusercontent.com/20657117/124761843-d5f5d380-df4f-11eb-9634-b3c7db63bc11.png)
Windows: 10

[AB#34784869](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/34784869)

**Comment by champnic** [comment]
Hey @prashant-mhase - do you have a sample app you can share that reproduces this issue? Are you seeing this with all WebView2 apps or a particular one (for example, do the [WebView2Samples ](https://github.com/MicrosoftEdge/WebView2Samples)work)?

**Comment by prashant-mhase** [comment]
Yes, It was for all the sample applications https://github.com/MicrosoftEdge/WebView2Samples
but when I reinstalled my windows 10 OS, it started working.

**Comment by champnic** [comment]
Thanks - I'll open this as a bug on our backlog.

**Comment by champnic** [comment]
Hey @prashant-mhase - Unfortunately we haven't been able to repro this and haven't heard other reports, so I'm going to close this issue. If you run into this issue again please let me know. Thanks!
