### ISSUE TITLE
InvalidCastException from CoreWebView2Environment.CreateAsync on Office 365 <v2010

### ISSUE THREAD

**Issue by omni-htg** [MicrosoftEdge/WebView2Feedback#1548]
Hello there, WebView2 team!

As originally posted [here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1369#issuecomment-881384969), I'm also experiencing an InvalidCastException getting thrown by CoreWebView2Environment.CreateAsync on a WebForm within Office.

After some experimenting, I was able to find out that the very same binaries start behaving differently in these two versions:
v2009 b13231.20418 (not working, InvalidCastException _see below_)
v2010 b13328.20292 (working)

For reference, some more context:
Word VSTO Add-in, Office 365
WinForms
WebView2 1.0.902-prerelease* (we need to make use of the Download API)
"Fixed Version" 92.0.902.45 (taken from Edge Beta folder)

* I could try with another version, but we need to make use of the Download API.

Stack trace of the "empty" InvalidCastException during CoreWebView2Environment.CreateAsync:
```
System.InvalidCastException: Specified cast is not valid.
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at WebDataSource.<GetDataValues>d__8.MoveNext() System.InvalidCastException: Specified cast is not valid.
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at WebDataSource.<GetDataValues>d__8.MoveNext()
```

----

What makes this so confusing is that the "empty" exception seems to be different to [the ones getting thrown when the SDK and RT versions do not match](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning#determine-webview2-runtime-requirement).

Thanks a lot!

This is our current code (albeit a bit modified for brevity and other redactions):
```csharp
public class WebDataSource
{
    private readonly string _url;
    private readonly string _webView2Path;
    private readonly string _userDataFolder;

    private string _downloadFilePath;
    private Form _form;

    public WebDataSource(string url, string webView2Path)
    {
        _url = url;
        _webView2Path = webView2Path;
        _userDataFolder = Path.Combine(Path.GetTempPath(), "WebView2");
    }

    public async Task<Dictionary<string, string>> GetDataValues()
    {       
        var browser = new WebView2
        {
            Dock = DockStyle.Fill
        };

        try
        {
            _form = new Form
            {
                ShowIcon = false,
                Size = new System.Drawing.Size
                {
                    Height = WindowHeight,
                    Width = WindowWidth
                },
                StartPosition = FormStartPosition.CenterParent,
                Text = "Web Data"
            };

            ((ISupportInitialize)(browser)).BeginInit();
            _form.SuspendLayout();

            string executableFolder = null;
            if (string.IsNullOrWhiteSpace(_webView2Path))
                Logger.Trace("WebView2 path not specified, using default runtime");
            else if (!Directory.Exists(_webView2Path) || !File.Exists(Path.Combine(_webView2Path, "msedgewebview2.exe")))
                throw new ArgumentException("WebView2 does not exist in the specified folder");
            else
                executableFolder = _webView2Path;
            var env = await CoreWebView2Environment.CreateAsync(executableFolder, _userDataFolder);

            browser.CoreWebView2InitializationCompleted += OnBrowserOnCoreWebView2InitializationCompleted;

            await browser
                .EnsureCoreWebView2Async(env);

            browser.Source = uri;

            _form.Controls.Add(browser);

            ((ISupportInitialize) (browser)).EndInit();
            _form.ResumeLayout(false);
            _form.PerformLayout();

            var toReturn = new Dictionary<string, string>();

            _form.ShowDialog();

            /*
                Code redacted for brevity
            */

            return toReturn;
        }
        catch (Exception e)
        {
            Logger.Error(e);
            throw;
        }
        finally // Clean-up
        {
            if (browser.CoreWebView2 != null)
            {
                browser.CoreWebView2.CookieManager.DeleteAllCookies();
                await browser.CoreWebView2?.CallDevToolsProtocolMethodAsync("Network.clearBrowserCache", @"{}");
            }

            browser.Dispose();
            _form?.Dispose();

            if (!string.IsNullOrWhiteSpace(_downloadFilePath) && File.Exists(_downloadFilePath))
            {
                File.Delete(_downloadFilePath);
            }
            _downloadFilePath = null;

            if (!string.IsNullOrWhiteSpace(_userDataFolder) && Directory.Exists(_userDataFolder))
            {
                Directory.Delete(_userDataFolder, true);
            }
        }
    }
}
```

**Comment by champnic** [comment]
Thanks for the bug report @omni-htg! Could you test this with a release SDK and regular WebView2 runtime (and probably have to remove the references to the Download API)? I think the error might be in the faux "Fixed Version" and the office versions are a red herring, but this will help figure that out.

And/or try using `Environment.SetEnvironmentVariable("WEBVIEW2_RELEASE_CHANNEL_PREFERENCE", "1");` to change the runtime search order and pickup the regular Beta/Dev/Canary runtimes instead of the "Fixed Version".

**Comment by omni-htg** [comment]
Thanks for getting into this, Nic.

I can try later today and come back with results -- hopefully they are positive.
If release works, it should also work with the next version, I take it?
Is it still on track to be released later this week? :shipit: 

On the other hand, while the runtime might have more to do with the problem than Office... Please remember that this change in behaviour _did_ happen with the very same binaries and conditions.

If it ends up being the runtime, I do hope that it provides yet again another reason for an official _Beta Channel_ runtime.

See you soon.

**Comment by omni-htg** [comment]
So, I tried going back to Office v2009 b13231.20418, and changed the code to:
- Point towards a release WebView2 runtime (`browserExecutableFolder = null`)
- Use latest release SDK (MS Edge + WebView2 Runtime 91.0.864.71)
- Remove all references to the Download API

At first, I didn't install the runtime, thinking that it might pick up "normal" Edge -- instead I got this exception:
```
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews. ---> System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebDataSource.<GetDataValues>d__8.MoveNext() Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews. ---> System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebDataSource.<GetDataValues>d__8.MoveNext()
```

Unfortunately, after installing the runtime, I got the same exception again:
```
System.InvalidCastException: Specified cast is not valid.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebDataSource.<GetDataValues>d__8.MoveNext() System.InvalidCastException: Specified cast is not valid.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebDataSource.<GetDataValues>d__8.MoveNext()
```

On v2010 b13328.20292 it starts working, just as before!
Regards!

**Comment by champnic** [comment]
Thanks for testing this. It does seem related to the Office version for some reason. I'll try to reach out to that team and ask if anything has been changing recently.

I wonder if you try an even older office if it still doesn't work?

**Comment by omni-htg** [comment]
Thank you for pushing it forward.
Will try with an older version if that helps -- but right now, our client has v2008, and I'm pretty sure they won't be going backwards 😄 

While we wait on the Office team to come back with some pointers, is there anything else do you think we could try?
Maybe there's a way to go deeper into the code to check out why does the Marshall throw that exception?

Oh, there's one other thing I would like to ask you about:
How influential do you think it is the "threading" context before launching the aforementioned code?
On v2008 we have tried the following, but nothing worked: 
- Dispatcher.CurrentDispatcher
- SynchronizationContext.SetSynchronizationContext(new WindowsFormsSynchronizationContext())
- Task.RunSynchronously(TaskScheduler.FromCurrentSynchronizationContext())

I also tried checking out the ApartmentState of the Thread that runs the solution and it says it is STA.
Any clues / recommendations?

**Comment by omni-htg** [comment]
Hey, man, some more findings:
I tried starting from scratch using a new Word VSTO Addin Ribbon, the above code and the release Runtime and SDK.
For some reason, when trying to launch it using this piece:
```csharp
public void LaunchWebView2(Office.IRibbonControl control)
{
    if (SynchronizationContext.Current == null)
        SynchronizationContext.SetSynchronizationContext(new WindowsFormsSynchronizationContext());
    SynchronizationContext.Current.Send(async state => await webDataSource.GetDataValues(), null);
}
```

I get this exception:
```
System.InvalidCastException: Could not complete the operation due to error 8070000c.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WordAddIn1.WebDataSource.<GetDataValues>d__7.MoveNext()
```

Does this help in any way?

**Comment by champnic** [comment]
I wasn't suggesting having the customer use an older version of Office, but rather wanted to see if it was an issue with a single version of Office or if it just doesn't work in version <2010.

The Apartment does need to be STA, and the WebView2 typically need to be created and accessed from the same thread.

**Comment by omni-htg** [comment]
> I wasn't suggesting having the customer use an older version of Office, but rather wanted to see if it was an issue with a single version of Office or if it just doesn't work in version <2010.

Don't worry, I was just joking haha -- will try some other older versions besides v2009 and v2008.

> the WebView2 typically need to be created and accessed from the same thread.

I will try another way to see if that works... but currently this whole "works in v2010, not in <2010" happens with the code I provided above (`LaunchWebView2`).

> The Apartment does need to be STA

I am currently checking Thread and Apartment using breakpoints and System.Threading.Thread.CurrentThread.
With this it always says it's the same Thread and STA.
Should I check it out another way?

---

Besides going for the older Offices test, is there anything else you think could help?
Did this exception `System.InvalidCastException: Could not complete the operation due to error 8070000c` help in some way, or did it make it worse?

Thanks!

**Comment by champnic** [comment]
Thanks for the follow-up! I don't think there's too much else to check on your end at this time. I hope to hear back from the VSTO folks soon :)

**Comment by omni-htg** [comment]
Hey, Nic!

New findings:
We took the _**Platform target**_ on the Project's _Properties_ > _Build_ from _Any CPU to x64 and back to Any CPU_ (to force it to "appear" in the .csproj xml), and now it works ._.
So: Any CPU > x64 > Any CPU > (Save)

No clue why did this make such a huge change in the underlying VSTO, but we can confirm after some testing that now everything works as intended on v2008 and v2009, including Download API.

Could you please look into this?
My understanding is that the "de-facto" Platform target is Any CPU, even if it's not "explicit" in the .csproj .

Thanks!

**Comment by champnic** [comment]
This sounds like it has a similar root cause as #730. We're working on a fix that would explicitly set the PlatformTarget in cases where it doesn't get set automatically by VS/csproj and I think that would have resolved this case as well. I'll link these two and make sure we verify this as well. Thanks! And glad you've got it working :)

**Comment by omni-htg** [comment]
Amazing, thanks Nic!

The most curious thing is how is this related to the Office versions, though haha
Think there's a chance to find out sooner or later?
