### ISSUE TITLE
System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.RuntimeInformation'

### ISSUE THREAD

**Issue by camambeou** [MicrosoftEdge/WebView2Feedback#1571]
My Winform App running on .Net Framework 4.6.2 got an error:

System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.RuntimeInformation' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.LoadWebView2LoaderDll()
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyApp.DropBoxLoginFrm.a.d()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

![Untitled](https://user-images.githubusercontent.com/37794164/127085806-251ef551-7ecb-4298-a477-315b7723ee83.png)

**Comment by champnic** [comment]
Thanks for the bug report @camambeou! This is a known issue we are working on in #946.
