### ISSUE TITLE
Cannot use WebView2 when main view created manually, not by StartupUri

### ISSUE THREAD

**Issue by pgarbo** [MicrosoftEdge/WebView2Feedback#1577]
Everything works fine when WPF App creates main view via StartupUri either in App.xaml or in the code, but not when creating manually:
app.Run(new MainWindow()); //This does not work

//This works:
app.StartupUri = new System.Uri("MainWindow.xaml", System.UriKind.Relative);
app.Run();

The WebView2 is not showing anything.
If you add EnsureCoreWebView2Async, it throws exception:

Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Environment.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning'

   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.get__nativeICoreWebView2Environment()
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__41.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass26_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WebViewBug.MainWindow.<InitializeAsync>d__1.MoveNext() in c:\git\BP\WebViewBug\WebViewBug\MainWindow.xaml.cs:line 31

Inner Exception:
 Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Environment'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{B96D755E-0319-4E92-A296-23436F46A1FC}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).
   at System.Runtime.CompilerServices.CastHelpers.ChkCastAny(Void* toTypeHnd, Object obj)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.get__nativeICoreWebView2Environment()

**Version**
SDK: 1.0.902.49
Runtime: 92.0.902.55
Framework: WPF
OS Win10

**Repro Steps**
run attached 
[WebViewBug.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/6891606/WebViewBug.zip)
See app.xaml.cs and comment/uncomment working and non-working version:

app.Run(new MainWindow()); //This does not work

            //This works:
            //app.StartupUri = new System.Uri("MainWindow.xaml", System.UriKind.Relative);
            //app.Run();

**Comment by champnic** [comment]
Thanks for the repro app and bug report! I'm able to see the same, though I'm not sure what the cause is. I've opened this bug on our backlog. Thanks!

**Comment by champnic** [comment]
This looks related to #970.

**Comment by AndyT-MS** [comment]
I've investigated this issue, discovered the problem, and should have a fix in soon.  Until then I have a potential workaround for you.

The root of the problem is that the `WebView2` control is trying to initialize before the application's event loop has started.  The thing that starts the event loop is `app.Run`.  When you set `app.StartupUri` and then call `Run`, the `Run` method apparently constructs the specified window (and its controls) *after* it has already started the event loop.  When you instead explicitly construct a window (and its controls) and then pass it to `Run`, the construction of the window (and controls) obviously finishes before `Run` is even called.

At this point it's important to differentiate between *constructing* the `WebView2` and *initializing* it (i.e. creating its `CoreWebView2`).  It's not a problem to *construct* it before the event loop starts, only to *initialize* it (see the [WPF WebView2 control documentation](https://docs.microsoft.com/dotnet/api/microsoft.web.webview2.wpf.webview2) for more about initialization).  In your case, the `WebView2` is immediately initializing itself on construction because the constructor runs the XAML, and the XAML sets the `Source` property, and setting the `Source` property triggers *implicit initialization*.  So, the potential workaround -- assuming that you need to construct the window/control before calling `Run` -- is to not set `Source` in your window's XAML, and instead trigger the `WebView2` initialization later after the event loop has started, perhaps in a handler for `Application.Startup` or your window's `FrameworkElement.Loaded`.

**Comment by ODtian** [comment]
Appreciate that! Thanks!
