### ISSUE TITLE
WebView Control is no longer valid because the Browser Process Crashed.

### ISSUE THREAD

**Issue by dhallada** [MicrosoftEdge/WebView2Feedback#1636]
We have a number of WPF applications that are using Webview2. These WPFs are embedded in a control for Microsoft Unified Service Desk. In short, there are a number of buttons that take you to certain websites, and users may have multiple open at once or reopen them by clicking the buttons. We are seeing users periodically run into issues where the WebView2 will crash and cause the entire application to crash. 

So far, there doesn't seem to be any rhyme or reason as to recreating it - it will sometimes happen for a certain set of steps, which will then be fine upon restarting the application. 

Here is an example of the error:

Microsoft.Crm.UnifiedServiceDesk Error 2 08/11/2021 9:14:20 AM  Message: Origin:USD BOOT FAILURE : DispatcherUnhandledException, IsFatal:False
Source : Microsoft.Web.WebView2.Wpf
Method : VerifyBrowserNotCrashed
Time : 9:14:20 AM
Date : 08/11/2021
Error : The WebView control is no longer valid because the browser process crashed.To work around this, please listen for the CoreWebView2.ProcessFailed event to explicitly manage the lifetime of the WebView2 control in the event of a browser failure.https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.processfailed
Stack Trace : at Microsoft.Web.WebView2.Wpf.WebView2.VerifyBrowserNotCrashed()
   at Microsoft.Web.WebView2.Wpf.WebView2.get_CoreWebView2()
   at Microsoft.Web.WebView2.Wpf.WebView2.OnWindowPositionChanged(Rect rcBoundingBox)
   at System.Windows.Interop.HwndHost.UpdateWindowPos()
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Version:**
WebView2 1.0.902.49
.NET Framework 4.7.2
OS Wind10

**Comment by dhallada** [comment]
It looks like this might be the same issue found here?

https://github.com/MicrosoftEdge/WebView2Feedback/issues/1411

Is there any update on this?

**Comment by champnic** [comment]
The browser process may crash for any number of reasons - is your app listening for the ProcessFailed event?

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!

**Comment by champnic** [comment]
@AliAsghar42 The error message includes recommendations for listening to the ProcessFailed event and restarting WebView2 if the browser process fails. Are you doing that?

**Comment by AliAsghar42** [comment]
Yes i restart the application
but again and again error message coming

**Comment by AliAsghar42** [comment]
but some times it works perfectly
