### ISSUE TITLE
WebView2 throw COMException (0x800401F0): CoInitialize has not been called. (0x800401F0 (CO_E_NOTINITIALIZED))

### ISSUE THREAD

**Issue by SkyIsWhite** [MicrosoftEdge/WebView2Feedback#1640]
Description
1 Call CoreWebView2Environment.CreateAsync throw exception
2 this call was in main thread
3 has no another one

Stack
,CoreWebView2InitializationCompleted,InitializationException=System.Runtime.InteropServices.COMException (0x800401F0): CoInitialize has not been called. (0x800401F0 (CO_E_NOTINITIALIZED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>cDisplayClass26_0.<<EnsureCoreWebView2Async>gInit|0>d.MoveNext(),Return

Version
SDK: 1.0.902.49
Runtime: edg/92.0.902.67
Framework: wpf

code
                webView = new Microsoft.Web.WebView2.Wpf.WebView2();
                webView.BeginInit();
                webView.CoreWebView2InitializationCompleted += WebView_CoreWebView2InitializationCompleted;
                webView.CreationProperties = new CoreWebView2CreationProperties();
                webView.CreationProperties.UserDataFolder = UserDataPath;
                this.grid.Children.add(webView);
                webView.EndInit();
                await webView.EnsureCoreWebView2Async();

**Comment by champnic** [comment]
Hey @SkyIsWhite - Can you share a sample app that reproduces this issue?
