### ISSUE TITLE
Async Dialog Code crashes WebView with RenderProcessUnresponsive

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#1648]
I have another very strange behavior bug that causes the WebView to become unresponsive, when calling a function that calls a modal dialog like `SaveFileDialog` and then waits for > 20 seonds. This sounds  highly circumstantial and it is, but it's repeatable with several different modal scenarios. 

When then accessing the WebView with an interop call that call fails with `RenderProcessUnresponsive`. This happens when I:

* Run inside of an `async` handler method
* Make an `await` call into the WebView via Interop
* Call a modal dialog

Example (here' this is a menu command - simplified to the basics here):

```cs
SaveAsCommand = new CommandBase(async (parameter, e) =>
{

    var md  = await Model.ActiveEditor.GetMarkdown();

    var sd1 = new SaveFileDialog
    {
        FilterIndex = 1,
        CheckFileExists = false,
        OverwritePrompt = true,
        CheckPathExists = true,
        RestoreDirectory = true
    };
    
    var res = sd1.ShowDialog();   // this fails

   // any subsequent access to the WebView causes the Unresponsive failure

    return;
```

This is likely related #1630 as well.

The exception that fires triggers from the dialog looks like this:
```
 at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at System.Windows.FrameworkElement.OnPreviewGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr hwnd)
   at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.CommonDialog.OwnerWndProc(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
**Addi tional context**
```

The exception fires but **only does this if I first call WebView Interop**. If I replace the call above to `ActiveEditor.GetMarkdown()` and replace it with `Task.Delay()` there's no problem - the dialog does not fail.

What's really weird about this is that hte code doesn't instantly blow up - it only blows up when the dialog is open for a while (> 20 seconds it seems). In my case the most common thing is File dialogs for saving, loading etc. but I also tried a plain `MessageBox.Show()` and I see the same behavior. Any dialog fails.

I have a feeling this occurs because the WebView is perhaps stealing the thread context from the dialog, so the dialog no longer is on the UI thread when it fails. 

**Workaround**:

I can work around this by putting the ShowDialog() call into a Dispatcher like this and that seems to fix the problem (at least for me, although I have at least one report that this did not fix the problem).

```cs

```cs
result = Model.Window.Dispatcher.Invoke(() => sd1.ShowDialog());
```

While this works, this is not a great solution because I have a ton of code that has modals like this. Finding and replaceing all these with Dispatchers would be a pain, but worse it's a bug that will bite others and it's extremely difficult to track this down because it's time sensitive in that it takes 20 or more seconds before the dialog failure causes a problem. 

For reference here our Markdown Monster user issue that triggered this and there's some more info on how we tracked to this point:

https://github.com/RickStrahl/MarkdownMonster/issues/838

**Comment by RickStrahl** [comment]
I've spent a bit more time trying to track this down and create a simpler repro case, but I haven't had much luck. I see the above errors in a variety of scenarios but it seems that there are some very specific cases in my app where this manifests:

* InputKeyBindings (shortcut keys)
* some async void event handlers (not all though)

I've compared call stacks when it fails and when it doesn't and the failures invariably come out of native code directly into the two CoreWebView2 methods shown in the error trace above. 

I've been able to make it fail in my sample application but it is **much, much less frequent** than in my live application. I suspect this is due to the fact that in MM there's a lot of Interop happening literally with every key stroke (spell checking, key checks, key forwarding etc.) and even for simple things like menu clicks often multiple WebViews get activated. 

Although the `InvokeAsync()` solution above seems to work, it's really troublesome that other modal operations are breaking up in this way. I've also seen a few other non dialog scenarios.

I realize once again that this sounds like a bunch of rambling, but I'm hoping somebody on the WV team can look at the error stack trace and perhaps think of something that might be responsible for failing in that focus change scenario that appears to be causing the WebView unresponsive lockup.

Still tracknig this on my end, and will post more when I find out more.

**Comment by RickStrahl** [comment]
@champnic - so I have some more info on this error as I've now run into this error myself a few times. I still see many of these a day in my product log from customers. For me it's really rare, but it does happen.

The scenario when it does seem to occur is the following:

* Application has been sitting **idle for a long time**
* Activate application - error immediately occurs and crashes app hitting last resort error handler 
  (same call stack as provided)

It's not consistent as I often have my app open and idle for long periods (even through sleep) and it doesn't crash, but every time I've seen this failure it's the same scenario - immediate crash upon activation. 

I do have some activation code that fires when activated, and tries to explicitly set focus to the editor (one of the WebViews) but it would appear that code never actually fires or at least doesn't show up in the call stack.

**Comment by champnic** [comment]
@RickStrahl - thanks for the update!

If you check the crash folder (<user data folder>\EBWebView\Crashpad\reports) do you have any dumps in there that would match the time when you saw the crashes on your machine? If so, can you share those? (You can email me directly at `champnic@microsoft.com`)

And when you say "idle for a long time", how long (ballpark) is that?
