### ISSUE TITLE
Selenium Grid not working with WebView2 application

### ISSUE THREAD

**Issue by pramodkeeliputti12345** [MicrosoftEdge/WebView2Feedback#1679]
**Description**

Selenium Grid not working with WebView2 application

**Version**
SDK: 91.0.864.37
Runtime: 91.0.864.37.x64
Framework: WPF
OS: Win10

**Repro Steps**
Run the below c# code

            EdgeOptions edgeOptions = new EdgeOptions();
            edgeOptions.UseChromium = true;
            edgeOptions.UseWebView = true;
            edgeOptions.BinaryLocation = @"C:\MyWebView2App.exe";
            IWebDriver webDriver = new RemoteWebDriver(new Uri("http://127.0.0.1:4444"),edgeOptions);

Below exception occurs:

OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4444/session timed out after 60 seconds.
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities, TimeSpan commandTimeout)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, DriverOptions options)
   at WebViewTesting.Program.Main(String[] args) in 

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
WebException: The operation has timed out.

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
Hey @pramodkeeliputti12345 - have you tried the instructions in our automation doc?
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver

**Comment by pramodkeeliputti12345** [comment]
The instructions in the automation doc does not talk about remote execution (selenium grid). i want to execute the tests on remote machine . In local it is working fine, but not working with RemoteWebDriver.

**Comment by champnic** [comment]
@pramodkeeliputti12345 
Hey Pramod - we believe this is an issue in Selenium Grid itself. When `UseWebView` is set it makes the browserName change from "Microsoft Edge" to "webview2" and we don't think Selenium Grid knows what to do with this name.

Can you open an issue at https://github.com/SeleniumHQ/selenium?
