### ISSUE TITLE
WebView2 crashes, but unsure if it's a bug or expected behavio

### ISSUE THREAD

**Issue by kyle-mcknight** [MicrosoftEdge/WebView2Feedback#1777]
When creating a new CoreWebView2 instance with the following code
`var op = new CoreWebView2EnvironmentOptions($"--disable-web-security --allow-file-access-from-files --remote-debugging-port=9229");`

And when our application opens another website within an iframe AND the devtools are open, the application crashes with the following stack trace

```
Unhandled Exception: System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed. ---> System.Runtime.InteropServices.COMException: The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
    at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
    at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
    --- End of inner exception stack trace ---
    at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
    at Microsoft.Web.WebView2.Wpf.WebView2.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
    at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

Not sure if this should be reported as a bug or this is a browser problem in general vs a webview2 problem. I'm not familiar enough with how browsers work in that fashion.

**Comment by champnic** [comment]
Hey @kyle-mcknight - thanks for the question! Do you have a small sample app that can reproduce this issue?

Something is making the WebView2 be disposed, and it's unclear whether it's coming from the host app side, or perhaps a crash in the browser processes. You can try listening to the BrowserProcessFailed event to see if that hits first.

**Comment by fvanheeswijk** [comment]
@r-cass Thank you for the reference to my issue! I'm curious how did you get the msedge.dll internal code visible? Are there (publicly available) PDB's you can download somewhere?

**Comment by r-cass** [comment]
@fvanheeswijk Aw, i think these PDB's are available publicly. First I opened the dump file with visual studio but I was unable to get symbols neither. However as a native and not a managed dump, I gave a try to windbg preview app, this way, fortunaly, symbols were loaded successfully. Nothing more ^^

**Comment by exchange321** [comment]
Are there further findings around ^? We're observing the same issue too.

**Comment by kyle-mcknight** [comment]
Hey, I can't recall what version helped, but when we updated to a later version, this worked for us with no changes from us. If I can find the version, I'll post it.
