### ISSUE TITLE
EnsureCoreWebView2Async is internally called a 2nd time and throws the exception

### ISSUE THREAD

**Issue by SchreinerK** [MicrosoftEdge/WebView2Feedback#1781]
EnsureCoreWebView2Async is internally called a 2nd time and throws the exception
System.ArgumentException: WebView2 was already initialized with a different CoreWebView2Environment. Check to see if the Source property was already set or EnsureCoreWebView2Async was previously called with different values.
   at Microsoft.Web.WebView2.Wpf.WebView2.EnsureCoreWebView2Async(CoreWebView2Environment environment)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass52_0.<SourcePropertyChanged>b__0()
   at Microsoft.Web.WebView2.Wpf.WebView2.WhenInit_Source(Action action)
   at Microsoft.Web.WebView2.Wpf.WebView2.SourcePropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at Microsoft.Web.WebView2.Wpf.WebView2.set_Source(Uri value)

Steps to reproduce:
- (A) handle CoreWebView2.NewWindowRequested, to initialize the WebView2 on a new tab
- (B)  set WebView2.Uri on the new tab to navigate to other page (user inputs a new URL)

I think maybe the problem is that EnsureCoreWebView2Async is called because the Uri is set the first time
BUT should not be called because environment already set in NewWindowRequested handler.

(A)
```
var environment = referrer?.WebView2.CoreWebView2.Environment;
var d = e.GetDeferral();
await WebView2.EnsureCoreWebView2Async(environment);
e.NewWindow = WebView2.CoreWebView2;
e.Handled = true;
d.Complete();
```
(B)
```
private void NavigateToUri(Uri uri) {
	if (WebView2.Source == null) InitCreationProperties(); 
	WebView2.Source = uri;
}
```
InitCreationProperties() is not called in this case because Source is not null

SDK: 1.0.992.28
Framework: WPF
OS:  Win10

**Comment by rozeboosje** [comment]
Following as this appears to be part of the bigger issue reported by several users in the last 24 hours

**Comment by JooJooBee666** [comment]
Yeah, they really screwed the pooch on this latest "stable" update.  Seems EnsureCoreWebView2Async is just broken mess for for everyone.  See issue #1778 and #1782 as well.

**Comment by rozeboosje** [comment]
Agreed. In fact I have now reverted to Build 1.0.902.49 as that is the only one that appears to work consistently for me across standalone WPF applications as well as our Outlook and Office Add-ins.

**Comment by champnic** [comment]
Hey @SchreinerK - Thanks for the bug report! In general this new behavior is "By Design", in that we are trying to catch instances where devs were causing initialization to happen twice, and the second time was being silently ignored. For example, if the Source property was set (which triggers implicit initialization) and then the dev tried to call EnsureCoreWebView2Async with a specific environment setup, the environment was being silently ignored, causing unexpected behavior (missing browser args or settings, etc.). 

However, you have found a case where we don't want this to happen, which is setting the Source property after EnsureCoreWebView2Async has completed initialization, only within the WPF control. This shouldn't cause a new implicit initialization because initialization has already completed! The Winforms control correctly allows the Source property to be set after EnsureCoreWebView2Async without an error.

The workarounds available to you are:
1. Use the WebView2.CoreWebView2.Navigate function instead of setting the Source property.
2. Use try/catch(ArgumentException) around the Source call and ignore the error. The navigation will still happen.
3. Downgrade to a different SDK package.

I've opened this bug on our backlog and we'll get a fix out shortly. Thanks!

**Comment by cosmin-teslovan** [comment]
I just upgraded to 1.0.1020.30 and the exception is no longer thrown for WPF.

**Comment by rozeboosje** [comment]
Yes ignore my comment I think I'm still struggling with #1778

**Comment by DanDev206** [comment]
I posted the solution here: 
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2435#issuecomment-1140186931
