### ISSUE TITLE
power bi

### ISSUE THREAD

**Issue by Thebill1000** [MicrosoftEdge/WebView2Feedback#1785]
Feedback Type:
Frown (Error)

Error Message:
Could not load type 'System.Runtime.InteropServices.RuntimeInformation' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

Stack Trace:
System.TypeLoadException
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.LoadWebView2LoaderDll()
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString(String browserExecutableFolder)
   at Microsoft.PowerBI.Client.Windows.WebView2.WebView2BrowserFactory.IsRuntimeAvailable(String browserExecutableFolder)
   at Microsoft.PowerBI.Client.Windows.Services.FeatureSwitchManager.RegisterPreviewFeatureSwitches()
   at Microsoft.PowerBI.Client.Windows.Services.FeatureSwitchManager.RegisterKnownSwitches()
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_0.<Main>b__1()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass3_0.<HandleExceptionsWithNestedTasks>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)

Stack Trace Message:
Could not load type 'System.Runtime.InteropServices.RuntimeInformation' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.GetStackTraceInfo(Exception e)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass15_0.<HandleException>b__0()
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.HandleException(Exception e)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

PowerBINonFatalError:
{"AppName":"PBIDesktop","AppVersion":"2.97.921.0","ModuleName":"Microsoft.Web.WebView2.Core.dll","Component":"Microsoft.Web.WebView2.Core.CoreWebView2Environment","Error":"System.TypeLoadException","MethodDef":"LoadWebView2LoaderDll","ErrorOffset":"-1"}

PowerBIUserFeedbackServices_IsReported:
True

**Comment by champnic** [comment]
Hey @Thebill1000 - this looks like it's the same issue as #946. Are you able to update the .NET Framework Runtime version that's installed on the machine?
