### ISSUE TITLE
.Net 4.8 application published via Citrix 6.5 cannot launch the webview2 control

### ISSUE THREAD

**Issue by aledeniz** [MicrosoftEdge/WebView2Feedback#1799]
**Description**
A .Net 4.8 application published via Citrix 6.5 cannot launch the webview2 control.

**Version**
Runtime: Evergreen Standalone Installer x64 (at the latest version, currently 94.0.992.38)
Framework: WinForms
OS: Windows 2008 R2 x64, updated to the latest published Microsoft updates.

**Repro Steps**
The code where the application fails:
```
private async void frmSchemeCrm_Load(object sender, System.EventArgs e)
{
   _webBrowser.CoreWebView2InitializationCompleted += CoreWebView2InitializationCompleted;
    var webView2Environment = await CoreWebView2Environment.CreateAsync(userDataFolder: Utilities.WebView2UserDataFolder);
    await _webBrowser.EnsureCoreWebView2Async(webView2Environment);
    SetBrowserContents();
    _isWebBrowserLoaded = true;
}
```

We get:
```
The following exception was caught:
	Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))

Diagnostic information follows:
	   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OurApplication.frmCrm.<frmCrm_Load>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

We use chocolatey as package manager, but this is a legacy machine, so there are plenty of packages which were not deployed via chocolatey. This is the list of installed packages and their version in that computer:

```
PS C:\> choco list -li
Chocolatey v0.11.2 Business
choco-upgrade-all-at 0.0.5
chocolatey 0.11.2
chocolatey-agent 0.12.1
chocolatey-core.extension 1.3.5.1
chocolatey-license 2023.11.23
chocolatey.extension 2.2.1
microsoft-edge 94.0.992.38
microsoft-edge-webview2 93.0.961.52
OurApplication 1.1.1267.22
9 packages installed.

Adobe Acrobat Reader DC|21.007.20095
Citrix App Delivery Setup Tools|1.0.1.211
Citrix Common Commands|1.3.0.0
Citrix Diagnostics Toolkit|7.0
Citrix EdgeSight for XenApp 6 Agent 5.4 x64|5.4.0.5107
Citrix Group Policy Client-Side Extension (x64)|1.5.0.0
Citrix Group Policy Management (x64)|1.5.0.0
Citrix HDX MediaStream for Flash - Server|2.0.0.0
Citrix HDX WMI Provider|2.0.0.0
Citrix Hotfix Rollup Pack XA650W2K8R2X64R07|
Citrix Hotfix XA650W2K8R2X64038|
Citrix License Configuration Tool|1.1.0.0
Citrix Offline Plug-in|6.5.0.6684
Citrix Profile management|5.0.0.111
Citrix Provisioning Services Target Device x64|7.1.0.4022
Citrix Receiver (Enterprise)|13.4.400.9
Citrix XenApp 6.5|6.5.0.0
Citrix XenApp Commands|6.5.0.0
Citrix XenApp Management|6.5.0.0
Citrix XenApp Migration|6.5.0.0
Citrix XenApp Server Configuration Tool|1.2.0.0
Citrix XenApp Server Role Manager|1.1.1.0
Classic Client 6.0 SP1 Patch1 for 64 bits|6.01.001.001
Dependency Agent|9.10.7
LiveUpdate 3.3 (Symantec Corporation)|3.3.100.15
Microsoft .NET Framework 4.8|4.8.03761
Microsoft Application Virtualization Client for Remote Desktop Services|4.6.3.24870
Microsoft Application Virtualization Client for Remote Desktop Services|4.6.2.24020
Microsoft Baseline Security Analyzer 2.3|2.3.2211
Microsoft Dynamics CRM 2011 for Microsoft Office Outlook|5.0.9690.4376
Microsoft Monitoring Agent|10.20.18053.0
Microsoft Office Professional Plus 2013|15.0.4569.1506
Microsoft Online Services Sign-in Assistant|7.250.4287.0
Microsoft Primary Interoperability Assemblies 2005|9.0.21022
Microsoft Report Viewer 2012 Runtime|11.1.3366.16
Microsoft ReportViewer 2010 Redistributable|10.0.30319
Microsoft Silverlight|5.1.50918.0
Microsoft SQL Server 2012 Native Client |11.1.3000.0
Microsoft SQL Server Compact 3.5 SP2 ENU|3.5.8082.0
Microsoft SQL Server Compact 3.5 SP2 x64 ENU|3.5.8082.0
Microsoft SQL Server Compact 4.0 SP1 x64 ENU|4.0.8876.1
Microsoft Sync Framework 2.1 Core Components (x64) ENU |2.1.1648.0
Microsoft Sync Framework 2.1 Core Components (x86) ENU |2.1.1648.0
Microsoft Sync Framework 2.1 Database Providers (x64) ENU |3.1.1648.0
Microsoft Sync Framework 2.1 Database Providers (x86) ENU |3.1.1648.0
Microsoft System CLR Types for SQL Server 2012|11.0.2100.60
Microsoft Visual C++ 2005 Redistributable|8.0.61001
Microsoft Visual C++ 2005 Redistributable (x64)|8.0.61000
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.4148|9.0.30729.4148
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161|9.0.30729.6161
Microsoft Visual C++ 2008 Redistributable - x86 9.0.21022|9.0.21022
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17|9.0.30729
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.4148|9.0.30729.4148
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.6161|9.0.30729.6161
Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219|10.0.40219
Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219|10.0.40219
Microsoft Visual C++ 2012 Redistributable (x64) - 11.0.61030|11.0.61030.0
Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.61030|11.0.61030.0
Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40660|12.0.40660.0
Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.40660|12.0.40660.0
Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24212|14.0.24212.0
Microsoft Visual Studio 2010 Tools for Office Runtime (x64)|10.0.50903
Mimecast for Outlook 32-bit|7.9.0.79
Nessus Agent (x64)|8.3.1.20060
System Center Endpoint Protection|4.10.209.0
TITUS Classification|16.5.9.4
TITUS Classification for Office Administration Tool|3.5.20.5
TrueSight Server Automation RSCD Agent|8.9.03.647
Veritas NetBackup Client|8.2
Windows Firewall Configuration Provider|1.2.3412.0
Windows Live ID Sign-in Assistant|6.500.3165.0
69 applications not managed with Chocolatey.
```
And the Windows Updates, by date of installation:

```
PS C:\>  Get-HotFix | Sort-Object InstalledOn | Select-Object Description, HotFixID | ogv

Update | KB976902
Update | KB958488
Update | KB974405
Hotfix | KB2550978
Hotfix | KB2561285
Update | KB2574819
Update | KB2670838
Update | KB2729094
Update | KB2786081
Update | KB2800095
Update | KB2830477
Update | KB2834140
Update | KB2843630
Update | KB2852386
Update | KB2857650
Update | KB2882822
Update | KB2908783
Update | KB2919469
Update | KB2928562
Update | KB2929733
Update | KB2966583
Update | KB2985461
Update | KB3018238
Security Update | KB2862330
Security Update | KB2862973
Security Update | KB2871997
Security Update | KB2894844
Security Update | KB2911501
Security Update | KB2931356
Security Update | KB2937610
Security Update | KB2943357
Security Update | KB2957189
Security Update | KB2972100
Security Update | KB2972211
Security Update | KB2973112
Security Update | KB2973201
Security Update | KB2973351
Security Update | KB2977292
Security Update | KB2978120
Security Update | KB2984972
Security Update | KB2991963
Security Update | KB2992611
Security Update | KB3000483
Security Update | KB3003743
Security Update | KB3004361
Security Update | KB3004375
Security Update | KB3010788
Security Update | KB3011780
Security Update | KB3021674
Security Update | KB3022777
Hotfix | KB2639308
Hotfix | KB3006137
Update | KB2923545
Update | KB2970228
Update | KB3006121
Security Update | KB2912390
Security Update | KB2928120
Security Update | KB2968294
Security Update | KB3020388
Security Update | KB3030377
Security Update | KB3035126
Update | KB2506014
Update | KB2506928
Update | KB2533552
Update | KB2545698
Update | KB2547666
Update | KB2552343
Update | KB2563227
Update | KB2603229
Update | KB2607047
Update | KB2608658
Update | KB2640148
Update | KB2660075
Update | KB2685811
Update | KB2685813
Update | KB2719857
Update | KB2726535
Update | KB2732059
Update | KB2750841
Update | KB2761217
Update | KB2763523
Update | KB2791765
Update | KB2808679
Update | KB2820331
Update | KB2853952
Update | KB2868116
Update | KB2891804
Update | KB2893519
Update | KB977236
Update | KB977238
Update | KB977239
Update | KB981111
Update | KB981390
Update | KB981391
Update | KB981392
Security Update | KB2479943
Security Update | KB2506212
Security Update | KB2509553
Security Update | KB2560656
Security Update | KB2564958
Security Update | KB2585542
Security Update | KB2604115
Security Update | KB2620704
Security Update | KB2621440
Security Update | KB2643719
Security Update | KB2654428
Security Update | KB2667402
Security Update | KB2676562
Security Update | KB2690533
Security Update | KB2698365
Security Update | KB2705219
Security Update | KB2719033
Security Update | KB2727528
Security Update | KB2736422
Security Update | KB2742599
Security Update | KB2765809
Security Update | KB2770660
Security Update | KB2807986
Security Update | KB2813347
Security Update | KB2813430
Security Update | KB2840631
Security Update | KB2847927
Security Update | KB2861698
Security Update | KB2862152
Security Update | KB2862335
Security Update | KB2864202
Security Update | KB2868038
Security Update | KB2884256
Security Update | KB2892074
Security Update | KB2893294
Security Update | KB2900986
Update | KB2386667
Update | KB2515325
Update | KB2647753
Update | KB982018
Hotfix | KB2508120
Update | KB3075851
Security Update | KB3023215
Security Update | KB3037574
Security Update | KB3042553
Security Update | KB3045685
Security Update | KB3046017
Security Update | KB3046269
Security Update | KB3055642
Security Update | KB3059317
Security Update | KB3060716
Security Update | KB3067903
Security Update | KB3068457
Security Update | KB3071756
Security Update | KB3072305
Security Update | KB3075226
Security Update | KB3076895
Security Update | KB3078601
Update | KB3138612
Update | KB3210131
Security Update | KB3074543
Security Update | KB3080446
Security Update | KB3084135
Security Update | KB3086255
Security Update | KB3092601
Security Update | KB3097989
Security Update | KB3101722
Security Update | KB3108371
Security Update | KB3108381
Security Update | KB3108664
Security Update | KB3109103
Security Update | KB3109560
Security Update | KB3110329
Security Update | KB3115858
Security Update | KB3122648
Security Update | KB3123479
Security Update | KB3126587
Security Update | KB3127220
Security Update | KB3133043
Security Update | KB3135983
Security Update | KB3138910
Security Update | KB3139398
Security Update | KB3139914
Security Update | KB3142024
Security Update | KB3146706
Security Update | KB3146963
Security Update | KB3149090
Security Update | KB3156016
Security Update | KB3156017
Security Update | KB3156019
Security Update | KB3159398
Security Update | KB3161949
Security Update | KB3161958
Security Update | KB3170455
Security Update | KB3177186
Security Update | KB3212642
Security Update | KB4012212
Update | KB4014504
Security Update | KB4014573
Security Update | KB4014579
Security Update | KB4015546
Security Update | KB4019263
Security Update | KB4022722
Security Update | KB4025337
Security Update | KB4034679
Update | KB4019990
Update | KB4040980
Security Update | KB4038779
Security Update | KB4040966
Security Update | KB4041678
Update | KB3020369
Update | KB4049068
Update | KB4051956
Update | KB4054998
Security Update | KB4048960
Security Update | KB4054176
Security Update | KB4054521
Security Update | KB4056897
Security Update | KB4074587
Security Update | KB4088878
Update | KB4100480
Security Update | KB4093108
Update | KB4338423
Security Update | KB4095514
Security Update | KB4103712
Security Update | KB4284867
Security Update | KB4338612
Security Update | KB4338823
Update | KB4339284
Security Update | KB3177467
Security Update | KB4343899
Security Update | KB4457145
Security Update | KB4462915
Security Update | KB4467106
Update | KB4468323
Security Update | KB4471328
Security Update | KB4480960
Update | KB4490628
Update | KB4486459
Update | KB4490128
Security Update | KB4486564
Security Update | KB4489885
Security Update | KB4493448
Security Update | KB4499175
Update | KB4501226
Update | KB4507704
Security Update | KB4503269
Security Update | KB4507456
Security Update | KB4516655
Update | KB4532945
Security Update | KB4474419
Security Update | KB4495612
Security Update | KB4506976
Security Update | KB4520003
Security Update | KB4525233
Security Update | KB4530692
Security Update | KB4532960
Security Update | KB4534314
Security Update | KB4536952
Security Update | KB4565354
Update | KB4569767
Security Update | KB4552965
Security Update | KB4569736
Security Update | KB4570673
Security Update | KB4575903
Security Update | KB4571719
Security Update | KB4577053
Update | KB2841134
Update | KB2849696
Update | KB2849697
Update | KB4578952
Security Update | KB4565579
Security Update | KB4578980
Security Update | KB4580387
Security Update | KB4580970
Security Update | KB4586768
Security Update | KB4586805
Update | KB2592687
Update | KB3013531
Update | KB3020370
Update | KB3054205
Update | KB3054476
Update | KB3068708
Update | KB3078667
Update | KB3080149
Update | KB3102429
Update | KB3107998
Update | KB3133977
Update | KB3137061
Update | KB3138378
Update | KB3140245
Update | KB3147071
Update | KB3172605
Update | KB3179573
Update | KB4072650
Security Update | KB4592510
Security Update | KB4592503
Security Update | KB4598289
Update | KB2809215
Update | KB3191566
Security Update | KB5001392
Hotfix | KB2872035
Security Update | KB5003165
Security Update | KB5003228
Security Update | KB5003636
Security Update | KB5003694
Security Update | KB5004378
Security Update | KB5004233
Security Update | KB5004307
Security Update | KB5004951
Security Update | KB5005036
Security Update | KB5005089
Security Update | KB5005563
Security Update | KB5005615
Security Update | KB5005633
```

**Additional context**

The application is compiled as Any CPU, but it is executed as x86.
The application doesn't get this issue when we launch it in the Citrix Desktop, or when we launch it from a RDP session, or in a Windows 2008 R2 computer without Citrix. The issue appears only when the application is a published app.
We have tried installing the Evergreen Standalone Installer x64, the Evergreen Standalone Installer x86 or both, it doesn't appear to do any meaningful difference.

We disabled the Citrix API hooks as described in CTX107825 (https://support.citrix.com/article/CTX107825) e.g. adding 

```
Key: HKEY_LOCAL_MACHINE\SOFTWARE\Citrix\CtxHook
Value Name: ExcludedImageNames
Type: REG_SZ
Value: msedge.exe,msedgewebview2.exe,sftdcc.exe,ssonsvr.exe,wfshell.exe,OurApplication.exe,icast.exe
```
in:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Citrix\CtxHook
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Citrix\CtxHook
```
Please note that without applying the workaround described in CTX107825 the msedge.exe or the msedgewebview2.exe applications crash straight away not only as a published app but also when in the Citrix desktop or in a RDP session. It would work fine in a non Citrix Windows 2008 R2 computer.

I can see other people are facing the same issue, a special mention to this very well made post: https://discussions.citrix.com/topic/412586-microsoftwebwebview2-net-framework-48-winforms-application-published-application-run-time-error-regdb_e_classnotreg/

Please note in said post the platform is stated as XenApp 7.6, therefore this issue is not limited to a single version of Citrix.

**Comment by aledeniz** [comment]
Just to be clear about the version of the webview2 control:
![image](https://user-images.githubusercontent.com/439083/136071163-05bc05fd-dee0-4f19-b39b-993f20895e2f.png)

**Comment by victorhuangwq** [comment]
Closing issue as stale.
