### ISSUE TITLE
Clicking on embedded youtube video profile icon causes COMException.

### ISSUE THREAD

**Issue by ProSho93** [MicrosoftEdge/WebView2Feedback#2001]
Hello, I'm preventing any new windows from opening with the NewWindowRequested event but it looks like i've ran into a bug.
If i click on the profile icon in an embedded youtube video (see image) i get the below exception.
Im using Microsoft.Web.WebView2 Version 1.0.1054.31 and WebView2 Browser version 96.0.1054.43.

![image](https://user-images.githubusercontent.com/95708572/145078100-d305aed4-3643-4381-b6e5-0c038d833b81.png)

Here is my NewWindowRequested event.
private void NewWindowRequested(object sender, CoreWebView2NewWindowRequestedEventArgs e)
{
    try
    {
        e.NewWindow = (CoreWebView2)sender;
        e.Handled = true;
    }
    catch (Exception ex)
    {
        Log.Error("NewWindowRequested. {errorMessage}", ex.ToString());
    }
}

System.InvalidOperationException
  HResult=0x80131509
  Message=CoreWebView2 members cannot be accessed after the WebView2 control is disposed.
  Source=Microsoft.Web.WebView2.Core
  StackTrace:
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   at Microsoft.Web.WebView2.Wpf.WebView2.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

Inner Exception 1:
COMException: The group or resource is not in the correct state to perform the requested operation. (0x8007139F)

**Comment by ProSho93** [comment]
I think I've solved this one. There is no need for me to use "e.NewWindow = (CoreWebView2)sender;"
Removing that and setting handled to true (e.Handled = true;) resolves the issue.

Thanks.
