### ISSUE TITLE
Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. 

### ISSUE THREAD

**Issue by code667** [MicrosoftEdge/WebView2Feedback#2046]
I am trying to build an sample app using webview2 (winform .net framework)

But I always get:

> Unable to load DLL 'WebView2Loader.dll': The specified module could not be found.  (Exception from HRESULT: 0x8007007E)

I have already installed latest webview2 using Nuget in my project.

I am wondering why.

Here is the code and detail report:

```diff
        private void Form1_Load(object sender, EventArgs e)
        {
            InitBrowser();
        }

        async Task InitializeAsync()
        {
            await webView21.EnsureCoreWebView2Async(null);
        }

        async void InitBrowser()
        {
            await InitializeAsync();
            webView21.CoreWebView2.Navigate("https://www.google.com");
        }
```

> See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.
************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at myweb4.Form1.<InitializeAsync>d__2.MoveNext() in L:\c#_project\myweb4\Form1.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at myweb4.Form1.<InitBrowser>d__3.MoveNext() in L:\c#_project\myweb4\Form1.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

**Comment by code667** [comment]
I do have WebView2Loader.dll under

project_path\bin\Debug\runtimes\win-x64\native

**Comment by champnic** [comment]
Hey @code667 - would you be able to share the sample app which reproduces this issue? Thanks!

**Comment by code667** [comment]
Hey @champnic, Thanks for looking into it.  The sample code can be found here

https://github.com/code667/webview_test/blob/main/Form1.cs

I have installed MS Edge Canary, but it doesn't help.

**Comment by champnic** [comment]
Thanks for the sample app. I tried running it an it fails in the way you describe. I noticed that the nuget package is not included, and it looks like instead you have extracted the WebView2 binaries and are referencing them in your app separately. So in my case, I don't see the WebView2Loader.dll included in the bin\debug\... output. Are you manually adding the loader to that folder?

**Comment by code667** [comment]
@champnic 
Thanks for your help.

Here are my steps:
1.  Open visual studio 19
2.  create a new project - windows forms app(.net framework) c# - create ...
3.  tools - nuget package manager - install webview2 
4.  drag the new control "WebView2" to the form
5. add the codes as https://github.com/code667/webview_test/blob/main/Form1.cs
6. compile and run

I found the issue is related to the path. If I change the project's path to L:\ or c:\user\username\somedir   
It will be ok.

But if I change it to  my path L:\c#_project, it will report the error

**Comment by champnic** [comment]
Thanks for confirming @code667! This sounds like it's the same issue as #1236, which is fixed and should be in the next prerelease package (this week or next).

**Comment by syeldan** [comment]
download dll file an place it under system32
https://www.dll-files.com/webview2loader.dll.html
