### ISSUE TITLE
Restarting multiple WPF webview results in exception when calling EnsureCoreWebView2Async

### ISSUE THREAD

**Issue by nabils** [MicrosoftEdge/WebView2Feedback#2065]
**Description**
Restarting multiple WPF processes each containing a single webview (single browser process) results in error when calling EnsureCoreWebView2Async.

**Version**
SDK: 1.0.1054.31
Runtime: 94.0.992.50
Framework: WPF
OS: Win10

**Repro Steps**
Start multiple WPF apps each containing a single webview instance. 
On startup of each navigate to a web page.
Shutdown all the apps programmatically and start them again.
They will fail once restarted with exception:
System.Runtime.InteropServices.COMException (0x800700AA): The requested resource is in use. (Exception from HRESULT: 0x800700AA)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()

**Additional context**
It does not happen when each has a separate user data folder but that is way too much overhead as we can have many apps.

**Comment by champnic** [comment]
@nabils Hey Nabil - this is due to the browser processes still shutting down while trying to connect to them again. If you wanted to try handling this while shutting down the apps, you could try listening for the BrowserProcessExited event to know that the WebView2 processes have shut down. The caveat here is that you would need some coordination between your app instances, as if another app instance is open with a WebView2 sharing the processes, then those processes will stick around until all WebView2 controls sharing the UDF have been shut down.

Alternatively, you can wait and try again to spin up the WebView2 when you run into this error, to give time for the browser processes to complete their shutdown.

Do either of those work for you?
