### ISSUE TITLE
WebView2 Unable to cast COM object of type

### ISSUE THREAD

**Issue by jadav1982** [MicrosoftEdge/WebView2Feedback#2161]
I am getting below error.

System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{7CCC5C7F-8351-4572-9077-9C1C80913835}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
  Source=mscorlib
  StackTrace:
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.Close()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.Close()
   at Microsoft.Web.WebView2.WinForms.WebView2.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()

[AB#38123381](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38123381)

**Comment by Shujee** [comment]
Any update on this one? I'm facing it in a VSTO Word add-in. I'm using WebView2 version 1.0.1462.37 on top of .NET Framework 4.8. This is VS2022 (Version 17.4.4) if that has anything to do.

Interestingly I'm trying to call `Dispose()` on my WebView2 upon exit. Still this thing somehow comes up.

**Comment by champnic** [comment]
No update here. @novac42 FYI

**Comment by Manka-Muakido** [comment]
any solutions? i am with the exact same problem, everything works fine but when i close the app i get the error:
`System.InvalidCastException: 'Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{4D00C0D1-9434-4EB6-8078-8697A560334F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).'`

even if i put a event on the app exit:
AppDomain.CurrentDomain.ProcessExit += CurrentDomain_ProcessExit;
 to call dispose , i get the same error

**Comment by BarakSameshSuS** [comment]
I use version **1.0.2277.86** :
When I call `Dispose()` from the finalizer (on the GC Finalizer Thread), the exception is thrown.
When I call it from a function on Main Thread (that is called before the finalizers), the exception is not thrown.
This supports [champnic's comment](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2161#issuecomment-1035394511) from Feb 10, 2022:
> We have seen issues in the past where the finalizer calls dispose on a thread different than the UI thread. Can you try calling "Dispose" on the WebView2 control from the UI thread before the finalizer gets to it? We are looking into some potential fixes that would limit this issue.

Any update on this issue?

**Comment by AmirMahdyJebreily** [comment]
Hello there,
I have the same exception with this error message : 
`
Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoeWebView2Environment10'. This operation failed because the QueryInterfaace call on the COM component fir the interface with ID '{EE0EB9DF-6F12-46CE-B53F-3F47B9C928E0}' failed due to the following error: No such interface supported (Exception from HRESULT : 0x80004002 (E_NOINTERFACE))
`
it's occurred when i run my exe in another computer with windows 11

**Comment by champnic** [comment]
@AmirMahdyJebreily This could be due to an older runtime that doesn't support ICoreWebView2Environment10 functions. What WebView2 runtime version is on the other Win11 computer?

**Comment by AmirMahdyJebreily** [comment]
No i use the latest version

**Comment by abstractspoon** [comment]
For the record: As suggested, I disposed the webview2 from the UI thread in the parent form's OnHandleDestroyed() and that worked for me. And I'm using 0.9.579 (for reasons of my own)
