### ISSUE TITLE
An attempt to use two instances of WebView2 leads to app crash

### ISSUE THREAD

**Issue by alk-wt** [MicrosoftEdge/WebView2Feedback#2206]
**Description**
Using 2 WebView components in the solution leads to the app crash when trying to initialize the second instance. 

**Version**
SDK: Microsoft.Web.WebView2.1.0.1158-prerelease
Framework: WinForms, .NET 4.8
OS: Win10Pro 10.0.19043

**Repro Steps**
The test app is [HERE](https://github.com/alk-wt/ms-support-requests/tree/main/SimplestWebView2App)
Repro steps: run the app, double-click on the svg image - the second form is empty, closing the second form brings an app crash.

**Additional context**
Both WebView2 components serve the same html containing svg inside.

**Comment by champnic** [comment]
Hey @alk-wt - What exception or stack trace are you getting?

**Comment by alk-wt** [comment]
Hi @champnic,

  The stacktrace looks like this (reproducing on the same codebase as mentioned by the link in the original ticket's description):
```
  
  System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__90.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SimplestWebView2App.ZoomedSVGForm.<RenderHtml>d__2.MoveNext() in T:\Job\MyProj\github-alk@alk0.info\ms-support-requests\SimplestWebView2App\ZoomedSVGForm.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SimplestWebView2App.ZoomedSVGForm.<<-ctor>b__1_0>d.MoveNext() in T:\Job\MyProj\github-alk@alk0.info\ms-support-requests\SimplestWebView2App\ZoomedSVGForm.cs:line 13
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at SimplestWebView2App.Program.Main() in T:\Job\MyProj\github-alk@alk0.info\ms-support-requests\SimplestWebView2App\Program.cs:line 19
```
   
   
In addition to it:
 - running the app in Debug/AnyCPU configuration from Jetbrains Rider

**Comment by champnic** [comment]
Hey @alk-wt - It looks like the code is running into a deadlock. Because the ShowDialog() happens inside of WebMessageReceived, the WebView2 browser process is blocked. When you try to open the dialog and initialize the second WebView2, it can't because of the blocked process. At this point when you close the dialog it allows the initialization to continue in the browser process, but by then the second WebView2 control has been destroyed and so it crashes.

To fix, you need to make sure execution continues while the dialog is opening. Changing `ShowDialog()` to `Show()` fixes the issue, but makes it into a non-modal dialog. You could also dispatch the call to open the new dialog so that it happens and is modal outside of the WebMessageReceived handler. Thanks!

**Comment by alk-wt** [comment]
Hi Nic,

  Thank you  very much for the efforts and explanation!

**Comment by vmeganathan81** [comment]
@alk-wt ,

Can you put in sample code on how you resolved this ?

**Comment by vikramnagineni** [comment]
@alk-wt  Would you please share the code on how you resolved?

**Comment by alk-wt** [comment]
@vikramnagineni , @vmeganathan81 , well guys, @champnic had stated quite clearly that turning the second form's call to non-modal solves the issue. 

`MouseDoubleClicked += (_, __) => new ZoomedSVGForm{Html = Html}.Show();`

that's it. Feel free to adopt to your needs, as well as the second solution Nic had brought.

**Comment by vmeganathan81** [comment]
The error is coming inside Initialize complete event of webview2 control, e.IsSuccess is false, and we are not using modal popup, 

And the issue is random, and its pertending to be on some machines, and the machines where the issue happens on those machine is consistent.

![image](https://user-images.githubusercontent.com/19844029/161766879-5ac9de31-2c73-460f-bc0d-71ee6338ccc7.png)

**Comment by alk-wt** [comment]
@vmeganathan81, well, pal, that's your domain area. I'm just talking that @champnic have explained the roots clearly enough, and one may fix his own similar issue following the provided guidelines.
I could only suspect regarding your code that as soon as you do some processing within WebView2 event handler, and that probably locks WebView2, then the next WebView2 request runs into a dedlock in the same manner and leads to the similar result like described in this issue.

**Comment by vmeganathan81** [comment]
@alk-wt , I know that, we coded around it.
Anyways we have addressed but does not seem good solution, wherein if we use other controls chromium one's it works fine.

**Comment by vmeganathan81** [comment]
I have closed my issue at the cost of performanc, but if we can consider to address it would be good. Multiple instance seamless integration.

**Comment by GJStarCode** [comment]
Hi everybody
Have you tried this aproach?

private void CoreWebView2_WebMessageReceived(object sender,
CoreWebView2WebMessageReceivedEventArgs e)
{
 string msg = e.TryGetWebMessageAsString();
 if (msg == "Open Dialog")
 {
 // Show a modal dialog after the current event handler is completed,
to avoid potential reentrancy caused by running a nested message loop in the
WebView2 event handler.
 System.Threading.SynchronizationContext.Current.Post((_) => {
 Form1 form = new Form1();
 form.ShowDialog();
 form.Closed();
 }, null);
 }
}

private void Btn_Click(object sender, EventArgs e)
{
 // Post web message when button is clicked
 
this.webView2Control.ExecuteScriptAsync("window.chrome.webview.postMessage(\
"Open Dialog\");");
}

Regards!
