### ISSUE TITLE
Could not load the 'Microsoft.WebwebView2(0.9.515-prerelease ) control in VSTO (Word Add-In) project

### ISSUE THREAD

**Issue by prasad-yadav** [MicrosoftEdge/WebView2Feedback#225]
When I tried to add the new webView2 control in VSTO (Word Add-In) project then it is throwing below error.

at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(EventArgs e)
at System.Windows.Forms.Control.AssignParent(Control value)
at System.Windows.Forms.Control.ControlCollection.Add(Control value)
at System.Windows.Forms.Form.ControlCollection.Add(Control value)
at MyRibbonAddIn.Form1.InitializeComponent() in 
at MyRibbonAddIn.Form1..ctor() 
at MyRibbonAddIn.MyRibbon.OnTaskPaneButton(IRibbonControl control)

I have used the below configuration.

Webview2 library: The .NET WebView2 0.9.515-prerelease
.Net Framework: 4.6.2
Visual Studio 2015
Microsoft Edge (Chromium) Canary channel
Operating system: Windows 10

**Comment by david-risney** [comment]
Thanks for the feedback! We'll look into this crash.

**Comment by yanshuiting** [comment]
I faced the same issue，webView2 can work well in winformApp,but threw nullreferenceexception in vsto project

**Comment by champnic** [comment]
Closing out old issues. Please let me know if you are still running into this and we can revisit. Thanks!
