### ISSUE TITLE
Webview2 crashes windows Form crashing

### ISSUE THREAD

**Issue by vmeganathan81** [MicrosoftEdge/WebView2Feedback#2297]
**Description**
Happening on some machine, the application crashes after sometime, we are using WebView2 .Net control in Windows Forms.

Below is the error message that we got in eventviewer

Inner Exception: ,Error Message: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT)) ,Stack Trace: at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__37.MoveNext()

,Error Message: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT)) ,Stack Trace:    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at cwWebView2.WebView2Control.<InitializeAsync>d__9.MoveNext()
**Version**
SDK: 1.3.155.77 ( MicrosoftEdgeWebView2RuntimeInstallerX64.exe )
Runtime:  Evergreen, 
Framework: WinForms
OS:  Windows 10 

**Repro Steps**
Its happening on some machine but consistent on those machines.

**Screenshots**

**Additional context**

**Comment by vmeganathan81** [comment]
@champnic ,

We have production issue, let me know at the earliest.

**Comment by champnic** [comment]
Hey @vmeganathan81 - Can you see if you are hitting a similar issue as #2206?

**Comment by vmeganathan81** [comment]
@champnic, We are not using any show dialog or blocking thread.

But on some machine we are getting this error randomly, but the machines where this random issue comes its randomness loading of Webview2 issue is consistent with those machines only.

Most machines its working fine.

Please assist, seems like more of Webview2 issue on some machine

2022-04-05 08:15:49,995 [1] ERROR==> [cwWebView2.WebView2Control, Method: WebView2_CoreWebView2InitializationCompleted]==> Inner Exception:  ,Error Message: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT)) ,Stack Trace:    at cwWebView2.WebView2Control.WebView2_CoreWebView2InitializationCompleted(Object sender, CoreWebView2InitializationCompletedEventArgs e)
2022-04-05 08:15:49,996 [1] INFO ==> [cwWebView2.WebView2Control, Method: WebView2_CoreWebView2InitializationCompleted]==> Completed ...
2022-04-05 08:15:50,286 [1] ERROR==> [cwWebView2.WebView2Control+<InitializeAsync>d__9, Method: MoveNext]==> Inner Exception:  ,Error Message: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT)) ,Stack Trace:    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at cwWebView2.WebView2Control.<InitializeAsync>d__9.MoveNext()

**Comment by vmeganathan81** [comment]
@champnic ,
We do check for e.IsSuccess and its failed.
![image](https://user-images.githubusercontent.com/19844029/161767417-577b6caa-646e-459d-b354-adcab6b2d2ea.png)

**Comment by lamposu** [comment]
@champnic 
I am also get this error from one of our customer's client logs. And  only have problem in 64bit webview2 in his PC, we install 32bit it works good.

W use WPF and .net6 with Nuget package:
[Microsoft.Web.WebView2](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1072.54)
and
WebView2 Runtime fixed version: 97.0.1072.76

**Comment by vmeganathan81** [comment]
We have resolved this error, it was blocking thread, mentioned from @champnic , we need to code around for two instance. You can mark this issue closed.

**Comment by champnic** [comment]
Glad to hear you got it working @vmeganathan81!
