### ISSUE TITLE
vb.net WinForms EnsureCoreWebView2Async results in System.Runtime.InteropServices.COMException (0x80004004): Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))

### ISSUE THREAD

**Issue by JimWard2018** [MicrosoftEdge/WebView2Feedback#2298]
**Description**
Winforms application dies calling webView.EnsureCoreWebView2Async(m_environment)

The WebView2 control trys to intialise by calling InitializeWebView2 but only gets as far as calling webView.EnsureCoreWebView2Async which never returns asnd results in

14:45:49,433	1	Thunderhead.Web.WebView2Helper	?	System.Runtime.InteropServices.COMException (0x80004004): Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Thunderhead.Web.WebView2Helper.VB$StateMachine_29_InitializeWebView2.MoveNext() in C:\source\dotnetClient-Trunk\VB.NET\ThWeb\WebView2Helper.vb:line 225
14:46:01,833	1	Thunderhead.Web.WebView2Helper	!hi	Navigate uri: file:///C:\Users\jward\AppData\Local\Temp\tmpA026.html
14:46:02,055	1	Thunderhead.CMS.Dashboard.BaseDashboardHandler.WebView2	!hi	[Home Dashboard]RefreshDisplay: 
14:46:02,264	1	Thunderhead.CMS.Dashboard.BaseDashboardHandler.WebView2	!hi	[Home Dashboard]RefreshRegisteredComponents: dotNetRefresh(8000040);
14:46:02,584	1	Thunderhead.BusinessContentStudio.Forms.MainForm.Startup	?	System.Runtime.InteropServices.COMException (0x80004004): Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
   at Thunderhead.Web.WebView2Helper.VB$StateMachine_29_InitializeWebView2.MoveNext() in C:\source\dotnetClient-Trunk\VB.NET\ThWeb\WebView2Helper.vb:line 234
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Thunderhead.BusinessContentStudio.Forms.MainForm.Startup(String[] strArgs) in C:\source\dotnetClient-Trunk\VB.NET\BusinessContentStudio\Forms\MainForm.vb:line 5161[run main form]
14:56:32,475	1	Thunderhead.BusinessContentStudio.Forms.MainForm.Startup	?	System.Runtime.InteropServices.COMException (0x80004004): Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
   at Thunderhead.BusinessContentStudio.Forms.MainForm.Startup(String[] strArgs) in C:\source\dotnetClient-Trunk\VB.NET\BusinessContentStudio\Forms\MainForm.vb:line 5166[run main form]

Runtime: 101.0.1200.0 canary
Framework: WinForms .Net 4.8
OS: Windows 10 Enterprise Version 21H2

I expect the call to EnsureCoreWebView2Async to succeed and return allowing the control to display a help html file

**Additional context**

My application uses numerous WebView2 controls; they all use one shared CoreWebView2Environment and use this shared method to initialize

`
        Private Shared m_environment As CoreWebView2Environment = Nothing

        Private Shared Async Sub InitializeWebView2(ByVal webView As WebView2, ByVal pathOrHtml As String, Optional uriIsHtmlString As Boolean = False)
            Try
                If m_environment Is Nothing Then
                    m_environment = Await CoreWebView2Environment.CreateAsync(userDataFolder:=UserDataFolder, options:=New CoreWebView2EnvironmentOptions(additionalBrowserArguments:="--remote-debugging-port=9222"))
                End If
                Await webView.EnsureCoreWebView2Async(m_environment)
                If uriIsHtmlString Then
                    webView.NavigateToString(pathOrHtml)
                Else
                    webView.Source = New Uri(pathOrHtml)
                End If
            Catch ex As Exception
                m_dcWebView2Helper.Exception(ex)
                Throw ex
            End Try
        End Sub
`

In every use case so far the call to webView.EnsureCoreWebView2Async returns and I go on to successfully navigate to a uri or local file

In this case the call never returns and it kills my application

So what's going on here ... well there are two WebView2 controls in play
The first is used to navigate to a local html file which has links in it
When they are clicked, the NavigationStarting event intercepts and performs the required action, cancelling the navigation.
In this case the action involves displaying a modal form containing another WebView2 control displaying web help

**Comment by JimWard2018** [comment]
I now know this is caused by the two WebView2 controls being dead locked; I'll code around it

**Comment by champnic** [comment]
Thanks Jim, glad you found the fix. For others, the fix is described in #2206.

**Comment by vmeganathan81** [comment]
@JimWard2018 ,

May I know how you resolved this deadlock ?

**Comment by JimWard2018** [comment]
@vmeganathan81 

So my deadlock was caused by one WebView2 control intercepting a request in the WebView2 CoreWebView2 NavigationStarting event.

My requirement was to 

1) Launch a modal form which contained another WebVew2 control, lets say by calling LaunchModalForm()
2) Cancel the navigation by setting e.Cancel to True

Initilally step 1) was performed synchronously in the same thread which caused the deadlock 

I changed it to a MainForm.BeginInvoke(Sub() LaunchModalForm()) to execute the call asynchronously, letting step 2) go ahead and get the first WebView2 out of he equation.
