### ISSUE TITLE
WebView2 - Crashes after windows form launches

### ISSUE THREAD

**Issue by praburamb** [MicrosoftEdge/WebView2Feedback#2301]
2022-03-18 16:29:19,603 [1] ERROR==> [cwWebView2.WebView2Control+<InitializeAsync>d__9, Method: MoveNext]==> Inner Exception:  ,Error Message: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT)) ,Stack Trace:    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at cwWebView2.WebView2Control.<InitializeAsync>d__9.MoveNext()

**Comment by champnic** [comment]
Hey @praburamb - Can you see if you are hitting a similar issue to #2206?

**Comment by champnic** [comment]
Closed for inactivity.
