### ISSUE TITLE
Webview2 fails to initialize

### ISSUE THREAD

**Issue by SureshkPerumal** [MicrosoftEdge/WebView2Feedback#2302]
**Description**
Webview2 fails to initialize with below exception.
We are getting below exception in CoreWebView2InitializationCompleted event.
Please advice.

System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed. ---> System.Runtime.InteropServices.COMException: The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.add_AcceleratorKeyPressed(ICoreWebView2AcceleratorKeyPressedEventHandler eventHandler, EventRegistrationToken& token)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.add_AcceleratorKeyPressed(EventHandler`1 value)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.add_AcceleratorKeyPressed(EventHandler`1 value)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()

**Version**
SDK:1.0.1054.31
Runtime: 99.10.1150.46
Framework: WPF,.Net Framework 4.8
OS:win10

**Screenshots**

**Comment by champnic** [comment]
Hey @SureshkPerumal, thanks for the bug report. Do you have a sample app with demonstrates this issue? Can you share your initialization code where you're seeing this happen?

**Comment by SureshkPerumal** [comment]
@champnic ,
Issues is sporadic. Will try to create sample app and recreate the issue.
Can you please let me know when this error thrown from webview2 and its possible root cause?

System.Runtime.InteropServices.COMException: The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)

**Comment by joonasronn** [comment]
@champnic 
We can reproduce this issue while waiting for EnsureCoreWebView2Async() in WPF. From what I can see in the logs, it seems like the customer is simultaneously using a barcode scanner on another part of the window. Could it be that the browser is catching that while initiating? If so, any ideas on how to prevent this behavior?

System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed. ---> System.Runtime.InteropServices.COMException: Ryhmä tai resurssi ei ole pyydetyn toiminnon suorittamiseen vaaditussa tilassa. (HRESULT-poikkeus: 0x8007139F)
   kohteessa Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.add_AcceleratorKeyPressed(ICoreWebView2AcceleratorKeyPressedEventHandler eventHandler, EventRegistrationToken& token)
   kohteessa Microsoft.Web.WebView2.Core.CoreWebView2Controller.add_AcceleratorKeyPressed(EventHandler`1 value)
   --- Sisäisen poikkeuksen pinon jäljityksen loppu ---
   kohteessa Microsoft.Web.WebView2.Core.CoreWebView2Controller.add_AcceleratorKeyPressed(EventHandler`1 value)
   kohteessa Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- Pinon jäljityksen loppu aiemmasta sijainnista, jossa palautettiin poikkeus ---
   kohteessa System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   kohteessa System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   kohteessa System.Runtime.CompilerServices.TaskAwaiter.GetResult()

SDK: 1.0.1210.39
