### ISSUE TITLE
Exception when trying to use AddOrUpdateCookie(CoreWebView2Cookie cookie) to set cookies in WebView2

### ISSUE THREAD

**Issue by PriyankaSOracle** [MicrosoftEdge/WebView2Feedback#2360]
I am getting the following exceptions while updating the cookies.

COM object that has been separated from its underlying RCW cannot be used.
at System.StubHelpers.InterfaceMarshaler.ConvertToNative(Object objSrc, IntPtr itfMT, IntPtr classMT, Int32 flags)
at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2CookieManager.AddOrUpdateCookie(ICoreWebView2Cookie cookie)
at Microsoft.Web.WebView2.Core.CoreWebView2CookieManager.AddOrUpdateCookie(CoreWebView2Cookie cookie)
at oracle.apps.projects.foundation.integration.msp.client.pageflow.PageFlowRequest.WebView2_CoreWebView2InitializationCompleted(Object sender, CoreWebView2InitializationCompletedEventArgs e)

We are initializing the session in an independent thread (STA) and storing the cookies in a context object.
Later, we are getting the above exception when we try to update the cookies using AddOrUpdateCookie in another thread (our main thread) which invokes our functional flow.

The above exception is not observed when both login and navigate actions are performed in the same thread. Also, session information is persisted across requests.

Any pointers on how to avoid the above exception with multi thread model?

Thanks,
Priyanka

**Comment by champnic** [comment]
Hey @PriyankaSOracle - WebView2 is single-threaded, so WebView2 and relevant objects, like Cookies, need to be interacted with on the thread where the WebView2 was first created/initialized. In this case, you will probably need to interact with your cookies on the WebView2 thread, probably by using a dispatcher or posting a message. Thanks!
