### ISSUE TITLE
MoveFocus Crash seen with Secondary Dialog on top of EdgeWebView based WPF Window

### ISSUE THREAD

**Issue by prat-coder** [MicrosoftEdge/WebView2Feedback#2388]
Seeing crash when a secondary modal WPF dialog is given focus. This being a child of WPF window which has EdgeWebView loaded inside it.

EdgeBrowser version used is  : 100.0.1185.29.
.net target framework for WPF: 4.8

Call Stack as below
:  Value does not fall within the expected range.
:     at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
:     at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
:     at Microsoft.Web.WebView2.Wpf.WebView2.OnGotKeyboardFocus(KeyboardFocusChangedEventArgs e)
:     at System.Windows.UIElement.OnGotKeyboardFocusThunk(Object sender, KeyboardFocusChangedEventArgs e)
:     at System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
:     at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
:     at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
:     at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
:     at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
:     at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
:     at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
:     at System.Windows.Input.InputManager.ProcessStagingArea()
:     at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
:     at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
:     at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
:     at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
:     at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
:     at System.Windows.UIElement.Focus()
:     at System.Windows.FrameworkElement.OnPreviewGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
:     at System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
:     at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
:     at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
:     at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
:     at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
:     at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
:     at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
:     at System.Windows.Input.InputManager.ProcessStagingArea()
:     at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
:     at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
 :     at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
 :     at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
 :     at System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr hwnd)
 :     at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
 :     at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
 :     at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
 :     at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
 :     at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
 :     at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
 :     at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
 :     at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by champnic** [comment]
Thanks for the bug report @prat-coder - do you have a small sample app that reproduces this issue?

**Comment by prat-coder** [comment]
@champnic Will try to provide a sample app in sometime. Could there be something deduced from the call stack and steps and other info mentioned?

**Comment by prat-coder** [comment]
It is still reproducible with EdgeWebView version104.0.1293.54.

**Comment by champnic** [comment]
@prat-coder Did you try out the 1.0.1248-prelease (or newer) WebView2 SDK?

**Comment by frankdekker** [comment]
@champnic  I've ran into the same error:
.Net 6.0.8
Edge: 106.0.1356.0 canary
Webview2:  1.0.1293.44
Windows: 10

```
System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   at Microsoft.Web.WebView2.Wpf.WebView2.OnGotKeyboardFocus(KeyboardFocusChangedEventArgs e)
   at System.Windows.UIElement.OnGotKeyboardFocusThunk(Object sender, KeyboardFocusChangedEventArgs e)
   at System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.UIElement.Focus()
   at WebView2.UserControls.WebView2.WebView2_CoreWebView2Ready(Object sender, EventArgs e) in
```

My reproduction:
1) have an application with Webview2 and another element in the same window with a context menu.
2) Start the application
3) call `Webview.Focus()` on `WebView2_CoreWebView2Ready`
4) And when the application is starting and Webview2 is loading, right click on the element to show the context menu.
5) the error will occur.

I can make a separate bug if needed, if this is not related.

**Comment by champnic** [comment]
@frankdekker Would you have a sample app which reproduces the issue you are seeing?

**Comment by frankdekker** [comment]
@champnic  Hi, I _think_ the issue resolved itself. I'm unable to reproduce it anymore with:
WebView2 version: 1.0.1340.0
MS Edge version: 106.0.1368.0 canary

**Comment by champnic** [comment]
That's good news! I'll tentatively mark this issue closed, but please let me know if you see it again and we can reopen. Thanks!

**Comment by prat-coder** [comment]
Issue is observed again when a secondary modal WPF dialog is given focus. This being a child of WPF window which has EdgeWebView loaded inside it.

EdgeBrowser version used is : 110.0.1587.57.
.net target framework for WPF: 4.8

Call Stack as below
Value does not fall within the expected range.
Value does not fall within the expected range.
    at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
    at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
    at Microsoft.Web.WebView2.Wpf.WebView2.OnGotKeyboardFocus(KeyboardFocusChangedEventArgs e)
    at System.Windows.UIElement.OnGotKeyboardFocusThunk(Object sender, KeyboardFocusChangedEventArgs e)
    at System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
    at System.Windows.Input.InputManager.ProcessStagingArea()
    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
    at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
    at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
    at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
    at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
    at System.Windows.UIElement.Focus()
    at System.Windows.FrameworkElement.OnPreviewGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
    at System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
    at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
    at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
    at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
    at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
    at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
    at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
    at System.Windows.Input.InputManager.ProcessStagingArea()
    at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
    at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
    at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
    at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
    at System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr hwnd)
    at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
    at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
    
    
    Were there any recent changes on the Movefocus side? I see release note "Fixed a bug where the app crashes when trying to move focus to WebView2 when it is disabled." in 1.0.1549-prerelease version.
 Can we reopen this issue?

**Comment by champnic** [comment]
@prat-coder Could you move that to a new issue? It's possible it's related.

**Comment by prat-coder** [comment]
@champnic Opened a new issue for the new instance of the crash
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3256
