### ISSUE TITLE
System.Runtime.InteropServices.COMException HRESULT: 0x800700AA

### ISSUE THREAD

**Issue by fdzatdtv** [MicrosoftEdge/WebView2Feedback#2446]
We are registering this exception since several runtime versions. An update of the sdk version from 1.0.705.50 to 1.0.1054.31 and improvement of our WebView2 initialization reduced the occurences, but not at all. Still too many to ignore them.

**Callstack**
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__54.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at Microsoft.Web.WebView2.Core.CoreWebView2CreateCoreWebView2ControllerCompletedHandler.Invoke(Int32 errCode, ICoreWebView2Controller createdController)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at our code Main(String[] args)

**Inner callstack**
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__18.MoveNext()

ErrorCode: -2147024726 (Hex: FFFFFFFF800700AA)

**Environment**
Runtime: Evergreen 101.0.1210.39
SDK: 1.0.1054.31
OS: Windows Server 2016 Standard
Application: WinForms (x86) running virtualized in RDP / WTS or Citrix
UDF user and dpi dependent: C:\Users\someuser\AppData\Local\OurApplication\WebView2\dpiAware

**Question**
Any thoughts what is going wrong?
What we can do better?

**Comment by david-risney** [comment]
800700AA is HRESULT_FROM_WIN32(ERROR_BUSY) which can come up when WebView2 has found an existing WebView2 browser process running for the user data folder and so it needs to connect to the existing browser process, but the browser process isn't responding and appears to be busy or hung.

One common way this can happen is if in your app you have a UI transition from one WebView2 to another. If you tear down an old WebView2 and then create a new WebView2 and there are no other WebView2s running then in between the browser process may shut down as it has no running WebView2s. If the new WebView2 is created while the browser process is shutting down you can hit this state. If this is the case you can try keeping the old WebView2 alive longer or reusing the same WebView2 to avoid this situation.

Or if you don't think you're in that sort of situation, do you know why else the WebView2 browser process might be very busy or seem hung?

**Comment by david-risney** [comment]
I've marked it as a feature request so we can investigate what we might be able to do to make this easier to solve.
