### ISSUE TITLE
EnsureCoreWebView2Async throws "ArgumentException: The path is not of a legal form." on versions newer than 1.0.1072.54

### ISSUE THREAD

**Issue by andrejapotic** [MicrosoftEdge/WebView2Feedback#2447]
**Description**

We tried updating our WebView2 control to the latest version but after installing it our program throws this exception (nothing else was changed in code): ArgumentException: The path is not of a legal form.

To test whether or not this bug will persist, we made a separate WinForms app and copied the exact same code to it (with the latest version 1.0.1210.39 installed) and it worked without problems. Below, I will provide screenshots of both apps.

**Version**
SDK: 1.0.1210.39 (and down to 1.0.1072.54)
Framework: WinForms
OS: Win10

**Repro Steps**

Make a function for initializing the WebView2 Control:

```cs
async void InitWebView()
        {
            await webView21.EnsureCoreWebView2Async(CoreWebView2Environment.CreateAsync(null, null, new CoreWebView2EnvironmentOptions { Language = "de-DE" }).Result);
            webView21.CoreWebView2.Navigate(Path.GetFullPath("C:\\Users\\Asus\\source\\repos\\WebView2 New version test\\WebView2 New version test\\bin\\Debug\\webview21.html"));
        }
```

Should initialize the component but instead throws the error that path is not of a legal form.

**Screenshots**
The dummy app which does NOT cause any errors:
![dummyApp](https://user-images.githubusercontent.com/56340280/167862918-5e4aaa0a-d8f1-4b98-8c65-888f4c1f4e85.PNG)
![dummyAppForm](https://user-images.githubusercontent.com/56340280/167862944-2189a24f-e74f-4e07-a902-cdb16cd29b57.PNG)

This app runs fine and throws no exceptions. It is basically a form with a webView2 on it and navigates to a local html file.

Our app is a bit more complex but it basically adds a webView2 control (which we called TextBox2Control) to the panel and is used as a text editor.
This is what happens when we try to add it after updating our webView2 to 1.0.1210.39 (or any other version higher than the original one it was made on, which is 1.0.1072.54).
![TextEditorApp](https://user-images.githubusercontent.com/56340280/167863527-3498f490-83a7-4f36-ba47-17b732202eb8.PNG)
![ErrorMessage](https://user-images.githubusercontent.com/56340280/167863550-6a1d5784-a9bd-4004-836c-74ffc8e37957.PNG)

This is obviously not intended, this is the app when we return the version to 1.0.1072.54:
![Panel](https://user-images.githubusercontent.com/56340280/167863701-20b6300b-2fea-4e8f-a91f-91f750a6e781.PNG)

**Additional context**
The component is being used as a textbox, it worked perfectly fine on version 1.0.1072.54 (the version it was made on, and it works for previous versions as well, meaning we tried downgrading below 1.0.1072.54 and it still worked, when trying to update it however, error arises as seen in the screenshots).

**Comment by champnic** [comment]
Hey @andrejapotic - thanks for the bug report, and sorry you are running into this. This feels like it might be related to #2372. When you hit this, can you share the $exception.InnerException.StackTrace?

**Comment by protegesolutions** [comment]
I struggled with something similar for two days - drat this over-complicated control! - and in the end it "appears" to have been related to the project configs, though I haven't quite worked out what the specifics are. I, too, had a problem with my actual app (in my case, it was an _InvalidCastException_ issue), so I set up a simple test app that resembled the structure, etc of the main app. And, of course, the test app worked flawlessly; I couldn't seem to make changes that broke the test app and I couldn't find what changes to make to the main app to get it to work.

Then, in desperation I changed the compilation from _Any CPU_ to _x64_ and it worked. I changed it back and forth and it sometimes worked, sometimes, didn't. Then I removed some "junk" from the configs and it worked with _Any CPU_ and _Prefer 32 bit_, which is what I wanted. So, my suggestion to you is to check/play around with/compare your project configs.

I'm really nervous about deploying our class library - used in third-party apps - with _WebView2_ to be honest. It just seems to be fussy and fragile. We had to move from the old _WebBrowser_ control - easiest thing in the world to integrate! - due to end-of-life and increasing compatibility issues. We tried _WebView_ but that doesn't work if the app runs as Administrator (!!!) I sure wish they'd keep things simpler.

**Comment by Pronner** [comment]
> I struggled with something similar for two days - drat this over-complicated control! - and in the end it "appears" to have been related to the project configs, though I haven't quite worked out what the specifics are. I, too, had a problem with my actual app (in my case, it was an _InvalidCastException_ issue), so I set up a simple test app that resembled the structure, etc of the main app. And, of course, the test app worked flawlessly; I couldn't seem to make changes that broke the test app and I couldn't find what changes to make to the main app to get it to work.
> 
> Then, in desperation I changed the compilation from _Any CPU_ to _x64_ and it worked. I changed it back and forth and it sometimes worked, sometimes, didn't. Then I removed some "junk" from the configs and it worked with _Any CPU_ and _Prefer 32 bit_, which is what I wanted. So, my suggestion to you is to check/play around with/compare your project configs.
> 
> I'm really nervous about deploying our class library - used in third-party apps - with _WebView2_ to be honest. It just seems to be fussy and fragile. We had to move from the old _WebBrowser_ control - easiest thing in the world to integrate! - due to end-of-life and increasing compatibility issues. We tried _WebView_ but that doesn't work if the app runs as Administrator (!!!) I sure wish they'd keep things simpler.

Tried everything, even tried changing the compilation to *x64* and *x86*, tried making the app run in Administrator only, tried updating to an older version, Nothing has worked.

The issue mentioned above is where my problem is found. I would love to get this fixed asap

**Comment by protegesolutions** [comment]
@Pronner FYI, we abandoned ship on this control. It's too fussy and way to over-designed for what we needed. The deal-breaker was the need to provide the loaders, which cannot be embedded as resources. (Well, they can, but you have to write them out to use them due to them being natively coded.) Maybe if a "lite" version is released we might revisit it.

**Comment by champnic** [comment]
@Pronner Does you problem match the quoted text from protegesolutions, or the originally posted issue with "The path is not of a legal form"? If not the original issue, can you open a separate GitHub issue?

Also, do you have a sample app that reproduces the issue that we could take a look at? Thanks!

**Comment by Pronner** [comment]
> @Pronner Does you problem match the quoted text from protegesolutions, or the originally posted issue with "The path is not of a legal form"? If not the original issue, can you open a separate GitHub issue?
> 
> Also, do you have a sample app that reproduces the issue that we could take a look at? Thanks!

Yes it does match, it's the same exception "The path is not of a legal form", and currently I cannot send in a sample application but it's on the issue mentioned on top: https://github.com/CmlLib/CmlLib.Core.Auth.Microsoft/issues/11

**Comment by Demotron** [comment]
@Pronner I'm having the same issue but only in Release mode. I was able to fix this issue by copying files to the Release directory. I noticed that in Debug folder I'm having such files but in Release I have a folder called runtimes/win-x64/native with WebView2Loaded.dll file.
<img width="178" alt="image" src="https://user-images.githubusercontent.com/9497457/186147672-bd903f84-78d5-4bbb-8e86-b1919474e3c7.png">

**Comment by Pronner** [comment]
> 

Nope, I've received a different exception now.

```csharp
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=mscorlib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at CmlLib.Core.Auth.Microsoft.UI.WinForm.MicrosoftLoginForm.<ShowLoginDialog>d__31.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ElixirClient.Form2.<guna2Button1_Click>d__1.MoveNext() in C:\Users\pronn\Desktop\Elixir Client\Ruby Client\Form2.cs:line 25

Inner Exception 1:
MissingMethodException: Method not found: 'System.Threading.Tasks.Task Microsoft.Web.WebView2.WinForms.WebView2.EnsureCoreWebView2Async(Microsoft.Web.WebView2.Core.CoreWebView2Environment)'.
```

**Comment by Demotron** [comment]
> > 
> 
> Nope, I've received a different exception now.
> 
> ```cs
> System.Reflection.TargetInvocationException
>   HResult=0x80131604
>   Message=Exception has been thrown by the target of an invocation.
>   Source=mscorlib
>   StackTrace:
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Delegate.DynamicInvokeImpl(Object[] args)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>    at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
>    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
>    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>    at System.Windows.Forms.Application.RunDialog(Form form)
>    at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
>    at System.Windows.Forms.Form.ShowDialog()
>    at CmlLib.Core.Auth.Microsoft.UI.WinForm.MicrosoftLoginForm.<ShowLoginDialog>d__31.MoveNext()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at ElixirClient.Form2.<guna2Button1_Click>d__1.MoveNext() in C:\Users\pronn\Desktop\Elixir Client\Ruby Client\Form2.cs:line 25
> 
> Inner Exception 1:
> MissingMethodException: Method not found: 'System.Threading.Tasks.Task Microsoft.Web.WebView2.WinForms.WebView2.EnsureCoreWebView2Async(Microsoft.Web.WebView2.Core.CoreWebView2Environment)'.
> ```

Yes, this hack doesn't work for my client as well but he has a different error. When did this issue come from? I mean can I revert to the previous version because I believe we didn't have it before.

**Comment by Pronner** [comment]
> > > 
> > 
> > 
> > Nope, I've received a different exception now.
> > ```cs
> > System.Reflection.TargetInvocationException
> >   HResult=0x80131604
> >   Message=Exception has been thrown by the target of an invocation.
> >   Source=mscorlib
> >   StackTrace:
> >    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
> >    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
> >    at System.Delegate.DynamicInvokeImpl(Object[] args)
> >    at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
> >    at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
> >    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> >    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> >    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> >    at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
> >    at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
> >    at System.Windows.Forms.Control.WndProc(Message& m)
> >    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
> >    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
> >    at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> >    at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
> >    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
> >    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
> >    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
> >    at System.Windows.Forms.Application.RunDialog(Form form)
> >    at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
> >    at System.Windows.Forms.Form.ShowDialog()
> >    at CmlLib.Core.Auth.Microsoft.UI.WinForm.MicrosoftLoginForm.<ShowLoginDialog>d__31.MoveNext()
> >    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> >    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> >    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
> >    at ElixirClient.Form2.<guna2Button1_Click>d__1.MoveNext() in C:\Users\pronn\Desktop\Elixir Client\Ruby Client\Form2.cs:line 25
> > 
> > Inner Exception 1:
> > MissingMethodException: Method not found: 'System.Threading.Tasks.Task Microsoft.Web.WebView2.WinForms.WebView2.EnsureCoreWebView2Async(Microsoft.Web.WebView2.Core.CoreWebView2Environment)'.
> > ```
> 
> Yes, this hack doesn't work for my client as well but he has a different error. When did this issue come from? I mean can I revert to the previous version because I believe we didn't have it before.

It came when I used CmlLib.Core.Auth.Microsoft, there's an issue I made here: https://github.com/CmlLib/CmlLib.Core.Auth.Microsoft/issues/11

**Comment by Demotron** [comment]
Okay, I was able to resolve this issue setting up WebView2Loader.dll path explicitly. Here's the code

`CoreWebView2Environment.SetLoaderDllFolderPath(loaderPath);`
Where loaderPath value is dependent of the process architecture and in my case has the following format '{Release_program_path}\runtimes\win-x86\native'. It contains WebView2Loader.dll file.
It looks like the issue is in `CoreWebView2Environment` when it tries to build such path using current Assembly.Location.
