### ISSUE TITLE
Winforms and Wpf not works together in one process

### ISSUE THREAD

**Issue by RachamimYaakobov** [MicrosoftEdge/WebView2Feedback#245]
I took the `WebView2WindowsFormsBrowser` example project
And I set it to `<UseWPF>true</UseWPF>` in csproj file
And I imported `MainWindow.xam` from the `WebView2WpfBrowser` example project
I run the project, if I run the WPF WebView first and then the Winforms WebView everything works fine
But if you run Winforms WebView first then WPF WebView doesn't work.
In both cases when closing the main window there is an error:
`System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'`
```
   at System.Windows.Forms.UnsafeNativeMethods.ThemingScope.DeactivateActCtx(Int32 dwFlags, IntPtr lpCookie)
   at System.Windows.Forms.UnsafeNativeMethods.ThemingScope.Deactivate(IntPtr userCookie)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at WebView2WindowsFormsBrowser.Program.Main() in C:\programming\WebView2Samples-master\WebView2Samples-master\WebView2WindowsFormsBrowser\Program.cs:line 19
```

**Comment by pagoe-msft** [comment]
@RachamimYaakobov 

Thanks for submitting this feedback. I've filed a bug in our system.

**Comment by champnic** [comment]
Closing out old issues. Please let me know if you are still running into this and we can revisit. Thanks!
