### ISSUE TITLE
WebView2 in .Net classlibrary

### ISSUE THREAD

**Issue by bobkumar-a** [MicrosoftEdge/WebView2Feedback#2476]
I'm using WebView2 in .Net classlibrary, but its giving the following error while calling

var env = await CoreWebView2Environment.CreateAsync(@"C:\Users\USERID\AppData\Local\\Plug_ins"); //here I have webview2  runtime folder copied along with my dll
"Couldn't find a compatible Webview2 Runtime installation to host WebViews"
stack trace:
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KMOutlookPlugin.WebForm.<InitCtrl>d__11.MoveNext()

if I avoid the abve call and simply make, then I get a different error
await webBrowser.EnsureCoreWebView2Async(null);
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

Stack trace as follows

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at KMOutlookPlugin.WebForm.<InitCtrl>d__11.MoveNext()

**Comment by bobkumar-a** [comment]
Thank you for the reply. Now I'm getting a different exception when calling 

var env = await CoreWebView2Environment.CreateAsync(browserExecFolder, userDataFolder ); // This line worked
await webBrowser.EnsureCoreWebView2Async(env); // Throws below exception

System.NotImplementedException: Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller4.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning ---> System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller4'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{97D418D5-A426-4E49-A151-E1A10F327D9E}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get__nativeICoreWebView2Controller4()
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get__nativeICoreWebView2Controller4()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_AllowExternalDrop(Boolean value)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at KMOutlookPlugin.WebForm.<InitCtrl>d__11.MoveNext() in I:\GIT Source\kmoutlookplugin\KMOutlookPlugin\KMOutlookPlugin\WebForm.cs:line 72


But its working in .net windows application code without any issues with just the below call
await webView21.EnsureCoreWebView2Async(null);

**Comment by champnic** [comment]
Looks like this is fixed in the [1.0.1248-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1248-prerelease) SDK. It should be fixed in the next release SDK.

**Comment by bobkumar-a** [comment]
Thank you all for your help. I used 1.0.1108.44 and issue got resolved.

**Comment by champnic** [comment]
Glad to hear you got it working @bobkumar-a :)
