### ISSUE TITLE
System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed

### ISSUE THREAD

**Issue by fdzatdtv** [MicrosoftEdge/WebView2Feedback#2706]
**Description**
We're registering constantly the following exception (automatically sent from our customers):
**System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed**.

We don't know when the WebView2 receives focus. But from the error message it must be after it is diposed. Our code is not in the call stack except for the main method. It's completely Microsoft code.

Could you ignore the MoveFocus and don't throw an exception at all when the control is disposed?

**Callstack**
at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
at Microsoft.Web.WebView2.WinForms.WebView2.OnGotFocus(EventArgs e)
at System.Windows.Forms.Control.InvokeGotFocus(Control toInvoke, EventArgs e)
at System.Windows.Forms.Control.WmSetFocus(Message& m)
at System.Windows.Forms.Control.WndProc(Message& m)
at Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
at System.Windows.Forms.UnsafeNativeMethods.SetFocus(HandleRef hWnd)
at System.Windows.Forms.ContainerControl.FocusActiveControlInternal()
at System.Windows.Forms.Form.set_Active(Boolean value)
at System.Windows.Forms.Form.WmActivate(Message& m)
at System.Windows.Forms.Form.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
at System.Windows.Forms.UnsafeNativeMethods.PeekMessage(MSG& msg, HandleRef hwnd, Int32 msgMin, Int32 msgMax, Int32 remove)
at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
...

**Version**
SDK: 1.0.1054.31
Runtime: 104.0.1293.54 evergreen
Framework: WinForms (x86)
OS: Windows Server 2016 Standard
.NET: Framework 4.8

**Repro Steps**
unknown

**Screenshots**

**Additional context**

**Comment by LiangTheDev** [comment]
Could you try to update WebView2 SDK to >= 1.0.1264.42? We've made some changes in newer SDK to ignore this failure and not throw.

**Comment by fdzatdtv** [comment]
Thanks for the answer. Our update cycle for the SDK is very long unless it's a security update. So, we will try it with our next update.
You can close this issue. If the problem still exists after the update, we can reopen the issue.

**Comment by LiangTheDev** [comment]
Closing the issue. Please re-open if the issue still exists.
