### ISSUE TITLE
System.ArgumentException after call HostObject method that returns non-generic Task

### ISSUE THREAD

**Issue by Vampire2008** [MicrosoftEdge/WebView2Feedback#2787]
**Description**

When I try to call method from JS side in HostObject that return Task it throws System.ArgumentEception with message "Value does not fall within the expected range"
Stack trace:
```
   at System.StubHelpers.ObjectMarshaler.ConvertToNative(Object objSrc, IntPtr pDstVariant)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2PrivateHostObjectAsyncMethodContinuation.Invoke(Int32 errorCode, Object& result)
   at Microsoft.Web.WebView2.Core.CoreWebView2PrivateHostObjectHelper.RawHelper.<>c__DisplayClass9_0.<SetAsyncMethodContinuation>b__0()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()
   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c__DisplayClass6_0.<GetActionLogDelegate>b__0()
   at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.<>c.<.cctor>b__8_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WpfApp1.App.Main()
```

**Version**
SDK: 1.0.1343.33
Runtime: WebView2 Runtime 105.0.1343.33
Framework: .NET Framework 4.8 WPF
OS: Win11

**Repro Steps**

1) Create Service with method that returns `Task`. Example:
```csharp
[ClassInterface(ClassInterfaceType.AutoDual)]
[ComVisible(true)]
public class Service {
    public async Task SomeLongMethod()
    {
        await Task.Delay(500);
    }
}
```
2) Add this Service as Host Object:
```
WebView2Instance.CoreWebView2.AddHostObjectToScript("service", new Service());
```
3) Run app
4) Open console and invoke
```
chrome.webview.hostObjects.service.SomeLongMethod()
```

**Workaround**
Change return type to generic Task:
```csharp
public async Task<int> SomeLongMethod()
{
    await Task.Delay(500);
    return default;
}
```

[AB#41761346](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41761346)

**Comment by ElyssaJyu** [comment]
Hi @Vampire2008 Please try to set assembly COM visible in the first place when you custom the WebView2HostObject class, otherwise JS cannot access the class.

`[ClassInterface(ClassInterfaceType.AutoDual)]
    [ComVisible(true)]
    public class Service
    {
        ...
    }`

**Comment by Vampire2008** [comment]
I used they. Problem exists. I just forgot to put them in example in post.

**Comment by ElyssaJyu** [comment]
I reproduced your code with setting COM visible property, but there is no such "System.ArgumentEception" pop-up. Could you provide more details?

**Comment by Vampire2008** [comment]
Sample project. Nothing else than I described in top post.
In this sample I put executing script that thows `System.ArgumentException` after navigation completed.
[WpfApp2.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9581597/WpfApp2.zip)

**Comment by plantree** [comment]
Hi @Vampire2008,

Following this doc [CoreWebView2.AddHostObjectToScript(String, Object) Method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=webview2-dotnet-1.0.1293.44#microsoft-web-webview2-core-corewebview2-addhostobjecttoscript(system-string-system-object)), we know that 
> Calling a method and pass in a parameter, the result is a proxy promise so you must await to get the result.

The example you showed using the `return Task`, it will not include a explicit result. Maybe the better way is like this:
```c#
public async Task<int> SomeLongMethod()
{
    await Task.Delay(500);
    return default;
}
```
and js is:
```javascript
var result = await window.chrome.webview.hostObjects.service.SomeLongMethod();
```
Hope to solve your issue.

**Comment by Methuselah96** [comment]
@plantree I am also running into this issue. Are you say there is no way to have a method on a host object that returns a non-generic task?

**Comment by plantree** [comment]
Hi @Methuselah96,

Do you have any reasons that the method must return a `Task` without result?
Can you provide more information about the usage scenarios to help us learn more?

**Comment by Vampire2008** [comment]
It will be good if we can use long methods, that just return Task (as other long methods in code without result) without any special workarounds.

**Comment by Methuselah96** [comment]
@plantree There's no reason I can't return a result, but it's a painful gotcha especially since the error message does not explain the problem.

My usage scenario is that I'm making a server call from the host object, but I don't need to return anything.

**Comment by plantree** [comment]
Hi @Methuselah96,

What you said might be a potential problem, and I have added it to our backlog and will try to find a solution. I will sync with you then.

Meanwhile, `return Task<T>` could be used as a temporary workaround.

**Comment by plantree** [comment]
Hi @Methuselah96,

[A new release](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#101671-prerelease) is available now. Hope to solve your problem.
