### ISSUE TITLE
InvalidCastException when Environment.Exit()

### ISSUE THREAD

**Issue by incheon-kim** [MicrosoftEdge/WebView2Feedback#2824]
**Description**
When I call Environment.Exit() with some opened windows contain webview2 control, it throws InvalidCastException.

I tried implementing IDisposable, call Dispose() during Closing/Closed events or overrided OnClosed()/OnClosing().
None of them worked.

== Exception, Error Message, Call stack ==
System.InvalidCastException
Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{4D00C0D1-9434-4EB6-8078-8697A560334F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Wpf.WebView2.Uninitialize(Boolean browserCrashed)
   at Microsoft.Web.WebView2.Wpf.WebView2.Dispose(Boolean disposing)
   at System.Windows.Interop.HwndHost.Finalize()
=============================

**Version**
SDK: 1.0.1342.22
Runtime: Edge 105.0.1343.50 (Official) 64-bit
Framework: WPF
OS: Win10 21H1

**Repro Steps**
1. Let window with webview2 control open
2. call Environment.Exit()

**Screenshots**

**Additional context**

**Comment by victorthoang** [comment]
Hello @incheon-kim, 

We will have these tasks triaged to the right developers to take a look at the issue soon.

Thanks!

**Comment by incheon-kim** [comment]
Actually, I found workaround. Just close the window that contains webview2 control when process exit.

AppDomain.CurrentDomain.ProcessExit event helps it.

When the Name property of WebView2 control is "webView", code would be like this.

```csharp
public SomeWindow() : Window
{
    Unload += (s, e) => { webView.Dispose(); }
    AppDomain.CurrentDomain.ProcessExit += (s,e) => 
    {
        App.Current.Dispatcher.Invoke(() => this.Close());
    };
}
```

**Comment by ElyssaJyu** [comment]
Hi @incheon-kim Since you have fixed this issue, is there any following issue you have?
