### ISSUE TITLE
WebVew2: BrowserExecutableFolder is not working

### ISSUE THREAD

**Issue by djsakariya** [MicrosoftEdge/WebView2Feedback#2864]
Hi there,

I would like to use fixed version as per https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#deploying-the-evergreen-webview2-runtime

I have set properties in xmls  as below
![image](https://user-images.githubusercontent.com/110444282/195093992-d47fa113-b16c-4d27-b3f7-096b9c9ffae2.png)

I created MSI and installed it.
At runtime it throws an exception "The path is not of a legal form." when executes CoreWebView2Environment.CreateAsync()

I have also tried 
![image](https://user-images.githubusercontent.com/110444282/195094541-6ffd14e4-7aa8-4eec-8e7e-96638cf21d8a.png)

But getting the same error.

Can you please suggest me what is missing here.

Note: 
WebView2 SDK 1.0.1343.22
.Net Framework version : 4.5.2

With Regards,
Dhiraj

**Comment by victorthoang** [comment]
Hello @djsakariya,

Thanks for your question. I've assigned your question to a dev that might best answer your question.

**Comment by LiangTheDev** [comment]
Could you share the stack of the exception? I am thinking whether the exception is for something else. I don't see WebView2 code throw that exception for BrowserExecutableFolder.

**Comment by djsakariya** [comment]
Hi @LiangTheDev 
Below is the log :
ERROR  - DaloopaExcelAddin.Views.SelectFundamentalsView+<InitializeWebView2Async>d__1 : The path is not of a legal form. :    at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAssemblyLocationDirectory()
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.LoadWebView2LoaderDll()
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DaloopaExcelAddin.Views.SelectFundamentalsView.<InitializeWebView2Async>d__1.MoveNext()

**Comment by LiangTheDev** [comment]
The issue is about failure to get directory of the WebView2 SDK dll (Microsoft.Web.WebView2.Core.dll). It should be a bug. Since you are under debugger, could you check what is the value of path in System.IO.Path.InternalGetDirectoryName(String path)?

To workaround this issue, you could specify the folder where WebView2Loader.dll is located by calling the static [CoreWebView2Environment.SetLoaderDllFolderPath](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.setloaderdllfolderpath?view=webview2-dotnet-1.0.1343.22) before WebView is created, like at the beginning of the program.
