### ISSUE TITLE
CoreWebView2 members cannot be accessed after the WebView2 control is disposed Exception in CoreWebView2.Reload

### ISSUE THREAD

**Issue by kirsan31** [MicrosoftEdge/WebView2Feedback#2872]
**Description**
The bug is sporadic on several machines. It seems that it is tied to the simultaneous initialization of several WebView2...
```
UnhandledException details: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed.
 ---> System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.Reload()
   at Microsoft.Web.WebView2.Core.CoreWebView2.Reload()
```

**Version**
SDK: 1.0.1343.22
Runtime: 106.0.1370.34 and 106.0.1370.37
Framework: WinForms .Net6
Windows 10 Pro (Microsoft Windows 10.0.19043) and Windows 10 Pro x64 (6.1.7601 Service Pack 1).

**Repro Steps**

Unfortunately, I could not make a 100% repro app :( But core code like this:
```cs
var envO = new Microsoft.Web.WebView2.Core.CoreWebView2EnvironmentOptions() { AdditionalBrowserArguments = "--disable-features=msWebOOUI,msPdfOOUI" };
var env = await CoreWebView2Environment.CreateAsync(options: envO).ConfigureAwait(true);
_webView2.CoreWebView2InitializationCompleted += _webView2_CoreWebView2Ready;
await _webView2.EnsureCoreWebView2Async(env).ConfigureAwait(true);
if (_webView2.CoreWebView2 is not null)
{
    await _webView2.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("document.addEventListener('keydown',event => { if (event.isComposing || event.keyCode === 229) return; " +
        "if(event.ctrlKey && event.code === 'KeyG') window.chrome.webview.postMessage('CtrlG'); " +
        "else if (event.ctrlKey && event.code === 'KeyD') window.chrome.webview.postMessage('CtrlD');" +
        "else if (event.ctrlKey && event.code === 'KeyS') window.chrome.webview.postMessage('CtrlS');});" +
        "document.addEventListener('dblclick', event => { window.chrome.webview.postMessage('dblclick');});").ConfigureAwait(true);
    _webView2.Reload(); // Exception here
}

private void _webView2_CoreWebView2Ready(object sender, CoreWebView2InitializationCompletedEventArgs e)
{
    if (!e.IsSuccess)
    {
        //_Logger.Error(e.InitializationException, "WebView2 Initialization Exception");
        return;
    }

    //_Logger.Info($"WebView2 ready. RuntimeVersion {_webView2.CoreWebView2.Environment.BrowserVersionString}; UserDataFolder {_webView2.CoreWebView2.Environment.UserDataFolder}.");
    _webView2.CoreWebView2.Environment.NewBrowserVersionAvailable += Environment_NewBrowserVersionAvailable;
    _webView2.CoreWebView2.ProcessFailed += CoreWebView2_ProcessFailed;
    _webView2.CoreWebView2.ContextMenuRequested += CoreWebView2_ContextMenuRequested;
}
```

**Additional context**
No `ProcessFailed` before this exception.
Similar issues I found:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2302
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2311
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2398
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2631

**Comment by victorthoang** [comment]
Hello @kirsan31,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by oggy22** [comment]
Hi @kirsan31, you mentioned that the problem is "tied to the simultaneous initialization of several WebView2" but your repro code has only one instance. Can you please clarify that?

**Comment by kirsan31** [comment]
> Hi @kirsan31, you mentioned that the problem is "tied to the simultaneous initialization of several WebView2" but your repro code has only one instance. Can you please clarify that?

This is the code from the form, our app can opens any number of this forms.

**Comment by kirsan31** [comment]
Got it today in debug with **only one** WebView2 form...
![image](https://user-images.githubusercontent.com/17767561/231513950-23d73eb9-3276-42b8-941b-c7a2c3fc5344.png)

**Comment by Shangminx** [comment]
Hi @kirsan31 , According to issue 2631, This should be fixed in SDK [1.0.1369-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1369-prerelease)+. Can you give that a try and verify it fixes your scenario? Thanks!

**Comment by kirsan31** [comment]
@Shangminx 
We are currently using `1.0.1370.28` (screen above with this version). I will update 1 post...

**Comment by 4vomAst** [comment]
Same here, we are using 1.0.1661.34

`<html><body>


System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed.
--
---> System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
--- End of inner exception stack trace ---
at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
at Microsoft.Web.WebView2.Wpf.WebView2.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
 


</body>
</html>`

**Comment by kirsan31** [comment]
> Hi @kirsan31 , I couldn't repro this issue by **Repro steps**. 

Me too :
> Unfortunately, I could not make a 100% repro app :( But core code like this:

This is very sporadic issue :(

**Comment by plantree** [comment]
Hi @kirsan31,

Could you add a `try...catch` to wrap `webview2.Reload()`? 

It seems that when you want to reload the page, this webview2 control is not in the right state, and by the way, what is the probabiliy that the issue occurs?

**Reference:**

- https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.reload?view=webview2-dotnet-1.0.1722.45#exceptions

**Comment by kirsan31** [comment]
> Hi @kirsan31,
> 
> Could you add a `try...catch` to wrap `webview2.Reload()`?
> 
> It seems that when you want to reload the page, this webview2 control is not in the right state,

Of course, [we added](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2872#issuecomment-1505530049), otherwise this problem cannot be bypassed...

> and by the way, what is the probabiliy that the issue occurs?

Sometimes several times a week, sometimes several times a day. After we added try-catch it became more difficult to track.
I tried opening many windows on purpose, tried loading many windows from a saved config - it didn't help reproduce the problem more often :(

**Comment by plantree** [comment]
Hi @kirsan31,

Could you provide a `.sln` project which could help us to reproduce locally? We'll be very appreciate.

**Comment by ghord** [comment]
For me, this reproduces 100% on first page load if following code is used:

```c#
await webView.EnsureCoreWebView2Async();
webView.Source = uri;
webView.Reload(); //caling reload after just assigning source
 ```

**Comment by LiangTheDev** [comment]
@ghord could you add an event handler for webView.CoreWebView2.ProcessFailed before setting webview.Source and see whether it fired before the exception and take an ETW trace (https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md) of the repro if no prococess failed event fired?

**Comment by LiangTheDev** [comment]
@ghord no need to test it out or collect the trace. I can repro it. I'll create an internal bug to track this.

**Comment by LiangTheDev** [comment]
Figured out why. Reload would throw if we have not loaded any page yet. Setting the Source only starts the navigation and the navigation has not completed yet. The exception message is confusing and that was come from translating the native invalid state error code. We'll investigate what is the reasonable behavior and make changes accordingly.

**Comment by kirsan31** [comment]
@LiangTheDev 

> Setting the Source only starts the navigation and the navigation has not completed yet.

We don't use `Source` property at all. But I hope that root case the same...
