### ISSUE TITLE
  UnauthorizedAccessException: 0x80070005 (E_ACCESSDENIED) in Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>

### ISSUE THREAD

**Issue by ShaunLoganOracle** [MicrosoftEdge/WebView2Feedback#2938]
**Description**
We have a large customer that is encountering an exception when our VSTO Excel add-in attempts to initialize the WebView2 control. This is blocking them so as you can imagine, it is a very hot/escalated issue.

**Exception Stack:**
```
UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
Source: mscorlib
Stack:
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
```

**Version**
SDK: 1.0.1343.22
Runtime: 107.0.1418.26
Framework: WinForms
OS: Windows 10 Enterprise (10.0.19041)

**Repro Steps**
Our code does in essence, the following.

In our Winform that hosts the WV2 control:
```
      private void HandleFormLoaded (object sender, EventArgs e)
      {
            await WebView2Control.InitializeWebView2Async (); // WebView2Control is an instance of our subclass of WebView2
            // once init is complete, we navigate to a URL in the WV2
      }
```
In our subclass of `Microsoft.Web.WebView2.WinForms.WebView2`:
```
      public async Task InitializeWebView2Async ()
      {
         CoreWebView2EnvironmentOptions options = new CoreWebView2EnvironmentOptions ()
         {
            AdditionalBrowserArguments = // <snip> nothing interesting
            Language = // something appropriate,
            AllowSingleSignOnUsingOSPrimaryAccount = true,
         };

         string userDataFolder = // something that resolves to %LocalAppData%\MyCompany\Our Addin Name\
         CoreWebView2Environment webView2Environment = await CoreWebView2Environment.CreateAsync (null, userDataFolder, options);

         await EnsureCoreWebView2Async (webView2Environment); // this is the base class impl: WebView2.EnsureCoreWebView2Async
      }
```

**Additional context**
Our code is running as a VSTO add-in in Excel
Customer has: Windows 10 Enterprise (10.0.19041)
Each user has their own User Data Folder; all instances of WV2 that we create share the same CoreWebView2EnvironmentOptions 
We saw this GH issue: #2476 but that does not seem related.

Edit: Are there any additional logs we can capture and examine to help diagnose this issue?

**Comment by ShaunLoganOracle** [comment]
Update from our customer: they had applied a patch applied to their endpoint management software which turned out to be the cause. Rolling back the patch resolved the issue.
