### ISSUE TITLE
Value does not fall within the expected range

### ISSUE THREAD

**Issue by fxl31** [MicrosoftEdge/WebView2Feedback#3059]
at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
   at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   at System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr hwnd)
   at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

my  wpf code：

1、MainWindow 
`private async void Window_Loaded(object sender, RoutedEventArgs e)
        {
            webBrw.CoreWebView2InitializationCompleted += WebBrw_CoreWebView2InitializationCompleted;
          
            if (webBrw.CoreWebView2 == null)
            {
                var env = await CoreWebView2Environment.CreateAsync();
                await webBrw.EnsureCoreWebView2Async(env);
            }
        }
        private async void WebBrw_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            if (e.IsSuccess)
            {
                webBrw.CoreWebView2.AddHostObjectToScript("Common", new CommonBridge(webBrw));

                webBrw.CoreWebView2.Navigate("http://localhost:8011/");
            }
        }
`
2、Window1
`
private async void Window_Loaded(object sender, RoutedEventArgs e)
        {
            webBrw.CoreWebView2InitializationCompleted += WebBrw_CoreWebView2InitializationCompleted;

            if (webBrw.CoreWebView2 == null)
            {
                var env = await CoreWebView2Environment.CreateAsync();
                await webBrw.EnsureCoreWebView2Async(env);// error occurred 
            }
        }

        private async void WebBrw_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            if (e.IsSuccess)
            {
                webBrw.CoreWebView2.Navigate(WebUrl);
            }
        }
`
3、CommonBridge
`
[ClassInterface(ClassInterfaceType.AutoDual)]
    [ComVisible(true)]
    public class CommonBridge
    {

        private Microsoft.Web.WebView2.Wpf.WebView2 webView = null;

        public CommonBridge()
        {
        }

        public CommonBridge(Microsoft.Web.WebView2.Wpf.WebView2 view)
        {
            webView = view;
        }
        public void OpenZoom(string url)
        {
            Window1 wd = new Window1(url);
            wd.ShowDialog();
        }
       
    }
`

**Comment by nishitha-burman** [comment]
Hello,

Can you please provide more details on the issue and how you are reproing it?

**Comment by champnic** [comment]
Hey @fxl31 - We sometimes see this if the environments don't match up when they have the same user data folder. Sharing a user data folder makes the WebView2 instances use the same browser processes, so the rest of the environment configuration much match up. Can you try this scenario without creating a new environment, and just leaving it to use the default one? ie. don't pass in the environment.

**Comment by BobbyShoe** [comment]
Just sharing I am getting this same crash at times.  Here is my stack trace.  Can some value checking be added to the MoveFocus call?  It appears to be happening rather randomly, but causes the application to crash.

Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   at Microsoft.Web.WebView2.Wpf.WebView2.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by jairbubbles** [comment]
I'm seeing this too with pretty much the same stack trace:
```
System.ArgumentException: Value does not fall within the expected range.
  ?, in void ICoreWebView2Controller.MoveFocus(in COREWEBVIEW2_MOVE_FOCUS_REASON reason)
  ?, in void CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
  ?, in IntPtr WebView2.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
  ?, in IntPtr HwndHost.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
  ?, in object HwndSubclass.DispatcherCallbackOperation(object o)
  ?, in object ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
  ?, in object ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
  ```

**Comment by Elisa-Adela** [comment]
When is the fix scheduled?

**Comment by Elisa-Adela** [comment]
Kind reminder. @champnic is there a fix scheduled?

**Comment by champnic** [comment]
@Elisa-Adela There isn't a specific issue here for us to fix. Unless you have exactly the same app setup and error as this thread, it might help to open a new issue and/or include a sample app which demonstrates the crash, a crash dump, stack trace, repro steps etc.
