### ISSUE TITLE
108.0.1462.54 doesn't work on SERVER 2012 R2 RDS

### ISSUE THREAD

**Issue by miklosgaspar** [MicrosoftEdge/WebView2Feedback#3084]
**Description**

Webview2 Runtime 108.0.1462.54 fails on Windows 2012 R2 RDS servers (works great on newer OSs)
CoreWebView2InitializationCompletedEventArgs.IsSuccess = FALSE   on Windows 2012 R2 RDS servers
The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
107.0.1418.62 works on 2012 R2 RDS
 

Stack:
System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

See attached project and comments inside (remember to restore nuget package before building)

1) build projects run exe from debug folder ..  no issues displaying microsoft.com site.
2) copy debug folder to Windows 2012 R2 server with WebView2 Runtime 108.0.1462.54 installed.
     CoreWebView2InitializationCompletedEventArgs.IsSuccess  returns false   and WebView2 is useless :<

3)   I rolled back all the recent Dec 2022 updates servers received (no change) .
      I was able to "Fix" by restoring a backup of "C:\Program Files (x86)\Microsoft\EdgeWebView\Application\107.0.1418.62"
      into the "C:\Program Files (x86)\Microsoft\EdgeWebView\Application\108.0.1462.54" folder.
       on the 2012 R2 server so I'm semi-confident this is a breaking change between 107 and 108.

**Additional context**
We still have a few locations who refuse to upgrade their 2012 R2 until official end of life.
In one Location App works when run under administrator login but not under user's (non admin rights) login.
Initially I thought it was a profile/permission/registry issue. until following day 3 other locations called in with the issue/blank webview2 forms.

[Webview2012r2.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10289584/Webview2012r2.zip)

**Comment by sln162** [comment]
Same problem, please pay attention  #3029

**Comment by victorthoang** [comment]
Hello @sln162,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this. With holidays over and new year's approaching, I appreciate your patience!

**Comment by sln162** [comment]
Edge Beta, version 109.0.1518.44, fixes this issue. It is not easy to find customers to cooperate with. I only found a Win7, and the test passed. I hope that more people who encounter this problem will test whether this version solves the problem.

**Comment by miklosgaspar** [comment]
Good news, per @sln162 suggestion

I just Uninstalled WebView2 and "regular edge" and installed Edge Beta 109.0.1518.44 on a 2012R2 RDS server.
**The Test program "WebView2012R2.exe"** included in this issue now works as Administrator **and regular a user**.
I'll be able to test on a few more machines Monday (EST) as they come online, and I am able to contact customers.

So, I'll be eagerly waiting for the Webview2 109.0.1518.44 runtime to allow few stragglers to limp along this they upgrade their servers.

note: Original program (huge application) still has issues (CoreWebView2InitializationCompleted e.IsSuccess=false) But I believe that is now due to old initialization code.)

**Comment by sln162** [comment]
@miklosgaspar   Looking forward to more tests from you, and also look forward to the arrival of version 109. Before uninstalling WebView2, make sure there are still bugs, and then install Bdge Beta as a comparison after uninstalling, which is more rigorous.

**Comment by miklosgaspar** [comment]
server1: verified issue still present in webview2(108).  Uninstalled Webview2 and Edge (108) and installed EdgeDEV (109) issue resolved (as administrator and regular user).
server2: same process, but issue was NOT resolved. 

Stack trace same except __40.MoveNext()  vs __80.MoveNext()
I've asked for server2 to left on after hours so I can resume testing
So, at this point the Install EdgeDev109 work around is inconsistent for me, but is cleaner than overwriting WebView2 108 directory with Webview2 107 files.

**Comment by sln162** [comment]
@miklosgaspar It seems that the fix code exists only in Edge Beta, version 109.0.1518.44. It is not clear whether there is a repair code in Dev, try to use Edge Beta as a basis for judgment

**Comment by fgjruiz** [comment]
Installing Edge beta version 109.0.1518.44 fixed a Windows Server 2012 terminal server for me.  Waiting on an IT guy to try the fix on a Windows 2008 R2 terminal server (I know EOL, but we are looking for info on whether the fix works, right)
