### ISSUE TITLE
WPF FileNotFoundException on initialisation

### ISSUE THREAD

**Issue by max-jacobs** [MicrosoftEdge/WebView2Feedback#3222]
**Description**
Hello!
We're seeing `FileNotFoundException`s occurring a low level (~0.1% of uses) during the initialisation routine. It's not clear from the exception what exactly can't be found.

The users who are getting this exception are also using it without a problem in the same session.

Anyone have any idea what might be happening here?

Thanks!

**Version**
SDK: 1.0.1518.46
Runtime: 109.0.1518.78
Framework: WPF
OS: Windows 10

**Repro Steps**
We haven't been able to reproduce this

**Additional Context**
- We're currently packaging `WebView2Loader.dll` at root level and not in `runtimes\win-x86\native`, though that shouldn't be an issue as `CoreWebView2Environment.LoadWebView2LoaderDll()` specifically checks the app root level, as well as the `runtimes` path
- We're using `CoreWebView2Environment.GetAvailableBrowserVersionString()` to verify that a user has WebView2 installed on their machine before continuing, which finishes without throwing every time

**Stack Trace**
```
System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass33_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
```

**Comment by max-jacobs** [comment]
We're also seeing this, related exception

```
System.Runtime.InteropServices.COMException (0x80004004): Class not registered

Class not registered

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass33_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at accuRx.UI.WebViews.StaticWebViewView.<_InitializeAsync>d__13.MoveNext()
```

**Comment by plantree** [comment]
Hi @max-jacobs,

Could you share some code about how did you initialize the `WebView2` object, which will help us a lot in locating the problem. Thanks.

**Comment by bertbsky** [comment]
I am seeing the same FileNotFoundException/stacktrace as in the initial post. When looking at the process activity with Process Monitor, I can see that my process is calling `CreateFile` resulting in `NAME NOT FOUND` for C:\Program Files (x86)\Microsoft\EdgeWebView\Application\110.0.1587.**49**\msedgewebview2.exe. This file probably existed at the time my application started up and used a webbrowser instance for the first time. However, we are now 2 days later and all files in this folder have been deleted (aside from `icudtl.dat` which has open file handles) because Edge has been updated to version 110.0.1587.**50**.

What would be the proper way to handle Edge/WebView2 background updates for long-running processes? Should the WebView2 runtime automatically detect this and launch the latest version? Or is a full application restart required?

**Comment by max-jacobs** [comment]
@plantree sure thing, happy to share, we don't do anything out of the ordinary. The only difference with the docs is that instead of calling `_InitializeAsync()` without `await`ing (as that's specifically not advised by Microsoft elsewhere), we shuttle the async work onto the dispatcher thread using [Reactive](https://github.com/dotnet/reactive) Observables and awaiting it there.

`_RegisterOnDataContextChanged` adds handling for `CoreWebView2InitializationCompleted` and `NavigationStarting` events. We initiate navigation (i.e. `View.Source = new Uri("...")` at end of the `CoreWebView2InitializationCompleted` handler.

**Note** I've removed the handling of the subscriptions and other boilerplate code for readability.

```
public partial class View : UserControl
{
    public View()
    {
        Observable.FromEventPattern<EventHandler, EventArgs>(
                e => Initialized += e,
                e => Initialized -= e)
            .SubscribeAsync(
                DispatcherScheduler.Current,
                async _ => await _InitializeAsync());

        InitializeComponent();

        Observable.FromEventPattern<DependencyPropertyChangedEventHandler, DependencyPropertyChangedEventArgs>(
                e => DataContextChanged += e,
                e => DataContextChanged -= e)
            .Subscribe(x => _RegisterOnDataContextChanged());
    }

    private async Task _InitializeAsync()
    {
        try
        {
            var additionalArgs = "...";
            var envOptions = new CoreWebView2EnvironmentOptions(additionalArgs);

            var environment = await CoreWebView2Environment.CreateAsync(null, null, envOptions);

            var options = environment.CreateCoreWebView2ControllerOptions();
            options.ProfileName = "profileName";

            await View.EnsureCoreWebView2Async(environment, options);
        }
        catch (Exception)
        {
            await _OnFail();
        }
    }
}
```

**Comment by plantree** [comment]
Hi @max-jacobs,

According to [this](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3222#issue-1587994460), it seems that you used methods such as `SetLoaderDllFolderPath` and `GetAvailableBrowserVersionString`. Have you catched the exception raised by these?

Combined with @bertbsky's issue, perhaps it's caused by a runtime update too and I need internal confirmation.

**Comment by plantree** [comment]
Hi @bertbsky,

In my story, your application need to run for a long time, even with WebView2 runtime updates. After update, have you checked wether your application is restarted?

**Comment by max-jacobs** [comment]
> According to [this](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3222#issue-1587994460), it seems that you used methods such as `SetLoaderDllFolderPath` and `GetAvailableBrowserVersionString`. Have you catched the exception raised by these?

We don't use `SetLoaderDllFolderPath()`. We just package the DLL into the root of our application, alongside all of our other DLLs and the initialisation I've shown above works 99.9% of the time.

We do use `GetAvailableBrowserVersionString`, however this never throws an exception, and only fails it seems when users genuinely don't have WebView2 installed.

Is there any more information I can get for you to help diagnose this?

Thanks!

**Comment by plantree** [comment]
Hi @max-jacobs,

Thanks for you information.

I am researching the mechanism of auto-update and I have one thing to confirm: under what circumstances does the problematic machine report this error? During operation or the first start-up? After crash, will restarting the program succeed?

**Comment by plantree** [comment]
Hi @max-jacobs,

Did you mean, the exception is raised very occasionally and hard to reproduce? Restart the program may solve?

Suppose we have a machine with this problem, will it occur when you start the program repeatedly?

**Comment by max-jacobs** [comment]
> very occasionally and hard to reproduce?

Yes, though there are a handful of users who have had this a number of times over the last few weeks

> Restart the program may solve?

We've seen the issue resolve within the same session i.e. the user hasn't had to restart, they've just closed/reopened the modal which contains the Webview, thereby re-initialising.

The fact that it can resolve is a good thing, but keen to put this on your radar so that you can look into it. Ideally it wouldn't appear in the first place.

> will it occur when you start the program repeatedly

In just one case yes. All others appear to resolve.

**Comment by plantree** [comment]
Hi @max-jacobs,

According to my understanding, your program uses WebView2 in a modal window, and it sometimes encounters the issue of `Not Found`, but reopening it can solve. Can you provide a working demo for illustrating?

**Comment by max-jacobs** [comment]
Hey @plantree, apologies for the delay, took a while to find the time to put something together
I've shared a private repository with you which has a very simplified version of our implementation.

In any case, I'm not convinced there is a link between our webview being in a modal, and the not found exception that our users are experiencing. We could easily add a retry loop around this exception, as it only appears to happen occasionally, but it would be good to understand the root cause, before we roll this out to more of our users.

**Comment by plantree** [comment]
Hi @max-jacobs,

Thanks for you demo!

I have got the access to the repository, and I'll check that ASAP.

**Comment by plantree** [comment]
Hi @max-jacobs,

Sorry for my late reply. Have your ever tried [SetLoaderDllFolderPath](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.setloaderdllfolderpath?view=webview2-dotnet-1.0.1774.30#microsoft-web-webview2-core-corewebview2environment-setloaderdllfolderpath(system-string)) to explicitly set the path of the folder containing the `WebView2Loader.dll`?

**Comment by max-jacobs** [comment]
Hi @plantree, we haven't no. Should there be a need for this? Would you expect different machines to pick up the DLL differently?

**Comment by plantree** [comment]
Hi @max-jacobs,

If you want to use `WebView2Loader.dll` under a given directory, this method shoule be helpful. You can test it locally freely. If you come across any questions, please let me know.

**Comment by max-jacobs** [comment]
Hi @plantree, I think my question was trying to get at why would we need to set this explicitly? If our software is working for the majority of the time without it, that's because WebView2 SDK is happily picking up the install location of the DLL without needing to set the location explicitly.

I'm trying to get to the bottom of why it doesn't work, seemingly randomly, only to resolve itself the next time the webview is initialised. In the meantime, I'll try using the method you have suggested, but I do think this should be tracked as a bug.

**Comment by plantree** [comment]
Hi @max-jacobs,

You're right. 

There are some mechanisms inside WebView2 to find the DLL, and they work fine most of the time. However, the users' environment are very diverse, and explicitly set the DLL path could be better. 

You could read the [remark](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.setloaderdllfolderpath?view=webview2-dotnet-1.0.1774.30#remarks) to learn more.
