### ISSUE TITLE
PrintToPdfAsync

### ISSUE THREAD

**Issue by scottgurvey** [MicrosoftEdge/WebView2Feedback#3249]
I have a webview2 which seems to be working as expected, I have loaded it with an HTML string which it displays as expected. I have a print button, which triggers a call to PrintToPdfAsync. While debugging this hits an error "SystemArgumentException: Value Does Not Fall Within the Expected Range."

I can't step into it. I can't find the source to inspect it. 

private async void PrintClicked(object sender, RoutedEventArgs e)
        {
            await webView.CoreWebView2.PrintToPdfAsync(@"test.pdf");
        }

I'm lost. Can anyone help?

**Comment by mikeduglas** [comment]
I call it this way:
`bool isSuccess = await this.webView.CoreWebView2.PrintToPdfAsync(pResultFilePath, printSettings);
`

**Comment by scottgurvey** [comment]
Thank you for responding.

 

How do you generate the printSettings?

 

I thought if you just didn’t add the second parameter or passed a null it would work with default settings. But that did not work. 

 

Nor does this:

 

private async void PrintClicked(object sender, RoutedEventArgs e)

        {

            CoreWebView2Environment CWV2e = await CoreWebView2Environment.CreateAsync();

            CoreWebView2PrintSettings? printSettings = null;

            printSettings = CWV2e.CreatePrintSettings();

            bool isSuccess = await this.webView.CoreWebView2.PrintToPdfAsync(@"test.pdf", printSettings);

        }

 

Regards,

Scott

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by scottgurvey** [comment]
Thank you for responding.

I’m afraid that doesn’t solve the problem.

 

The code is now:

 

private async void PrintClicked(object sender, RoutedEventArgs e)

        {

            CoreWebView2PrintSettings printSettings = webView.CoreWebView2.Environment.CreatePrintSettings();

            bool isSuccess = await this.webView.CoreWebView2.PrintToPdfAsync(@"test.pdf", printSettings);

        }

 

 

The exception stack is:

 

System.ArgumentException

  HResult=0x80070057

  Message=Value does not fall within the expected range.

  Source=Microsoft.Web.WebView2.Core

  StackTrace:

   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_7.PrintToPdf(String ResultFilePath, ICoreWebView2PrintSettings printSettings, ICoreWebView2PrintToPdfCompletedHandler handler)

   at Microsoft.Web.WebView2.Core.CoreWebView2.<PrintToPdfAsync>d__0.MoveNext()

   at WpfApp4.MainWindow.<PrintClicked>d__2.MoveNext() in C:\Users\Scott\source\repos\MailKit\WpfApp4\MainWindow.xaml.cs:line 78

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   at System.Windows.Threading.Dispatcher.Run()

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at System.Windows.Application.Run()

   at WpfApp4.App.Main()

**Comment by mikeduglas** [comment]
Hmm, same code works for me. I use WinForms, but don't think it does matter.
Are you calling PrintClicked on the thread which WebView2 is created on?

**Comment by scottgurvey** [comment]
That is interesting.

 

I am not using WinForms. I am using WPF.

 

I have not done anything in the code, which is simple for test purposes, to create any additional threads. My WebView2 is an element on the MainWindow, defined in XAML, as are two buttons used to trigger events for testing. I confess I am not an expert on multi-threading.

**Comment by mikeduglas** [comment]
WebView2Samples\SampleApps\WebView2WpfBrowser example has menu item "File | Print" which calls PrintToPdfAsync.

**Comment by vickiez** [comment]
Hi @scottgurvey, can you try using an absolute path instead of a relative path?

**Comment by scottgurvey** [comment]
Hi Viktoria,

 

That solved my problem. And I now see the documentation specifies an absolute path is to be used. I just missed that requirement.

 

Thank you for your help.

 

Scott Gurvey

**Comment by scottgurvey** [comment]
My problem was using a relative path. The documentation specifies an absolute path is required.

 

 

Thanks for your help.
