### ISSUE TITLE
MoveFocus Crash seen with Secondary Modal Dialog on top of EdgeWebView based WPF Window

### ISSUE THREAD

**Issue by prat-coder** [MicrosoftEdge/WebView2Feedback#3256]
Issue is observed when a secondary modal WPF dialog is given focus. This being a child of WPF window which has EdgeWebView loaded inside it.

EdgeBrowser version used is : 110.0.1587.57.
.net target framework for WPF: 4.8

Call Stack as below
Value does not fall within the expected range.
Value does not fall within the expected range.
at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
at Microsoft.Web.WebView2.Wpf.WebView2.OnGotKeyboardFocus(KeyboardFocusChangedEventArgs e)
at System.Windows.UIElement.OnGotKeyboardFocusThunk(Object sender, KeyboardFocusChangedEventArgs e)
at System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
at System.Windows.Input.InputManager.ProcessStagingArea()
at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
at System.Windows.Input.KeyboardDevice.ChangeFocus(DependencyObject focus, Int32 timestamp)
at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
at System.Windows.UIElement.Focus()
at System.Windows.FrameworkElement.OnPreviewGotKeyboardFocus(Object sender, KeyboardFocusChangedEventArgs e)
at System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
at System.Windows.Input.InputManager.ProcessStagingArea()
at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
at System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
at System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
at System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
at System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr hwnd)
at System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr hwnd, WindowMessage message, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

Were there any recent changes on the Movefocus side? I see release note "Fixed a bug where the app crashes when trying to move focus 
to WebView2 when it is disabled." in 1.0.1549-prerelease version.

**Comment by champnic** [comment]
@prat-coder Thanks for opening a new bug. What WebView2 SDK version are you seeing this behavior on? If you use an older SDK (pre-1.0.1549-prerelease mentioned in your comment) do you see the same crash? Do you have a simple app you can share that reproduces this issue? Thanks!

**Comment by prat-coder** [comment]
Evergreen WebView2 Runtime is used. In release notes and in nuget site, latest WebView2 sdk version specified is 1.0.1587.40(https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1587.40). 
But runtime installed is 110.0.1587.57. 

This issue has been seen intermittently. Cannot actually confirm whether older SDK had zero instances of this issue. Since I saw mention of the MoveFocus issue in pre-1.0.1549-prerelease, just asked about it as a possibility.
Can the stack trace not help in analyzing more about this issue.

**Comment by champnic** [comment]
Thanks for the info. The stack trace is helpful, but this info and a sample app also helps provide clues. I'm adding this bug to our work backlog.

**Comment by zhuhaichao518** [comment]
@prat-coder Hi, the release note in 1.0.1549-prerelease is about focusing on WebView when it is disabled. When a modal dialog is opened, the owner window of this dialog (which contains WebView) is disabled (which means it does not expect to receive user inputs). If user tries to focus on WebView somehow without closing this dialog, it will crash because of [ERROR_INVALID_PARAMETER](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setfocus). This was a SDK fix and not related to runtime.
I am not how that effects your scenario. Could you please give me the HRESULT of that excpection (click on _view details_ on debugging when the exception happens)? I expect ERROR_INVALID_PARAMETER(-2147024809, or 0x80070057) not happen in SDKs after that.

**Comment by prat-coder** [comment]
@zhuhaichao518 and @champnic Tried to decode the stack again using windbg. Below is the stack:
-------------------------------------------------
Exception type:   System.ArgumentException
Message:          Value does not fall within the expected range.
InnerException:   <none>
StackTrace (generated):
    SP       IP       Function
    00000000 00000001 Microsoft_Web_WebView2_Core!Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_MOVE_FOCUS_REASON)+0x2
    016FDF80 0B3BED9E Microsoft_Web_WebView2_Core!Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(Microsoft.Web.WebView2.Core.CoreWebView2MoveFocusReason)+0x26
    016FDFA8 0B3BED63 Microsoft_Web_WebView2_Wpf!Microsoft.Web.WebView2.Wpf.WebView2.OnGotKeyboardFocus(System.Windows.Input.KeyboardFocusChangedEventArgs)+0x13
    016FDFAC 62E05096 PresentationCore_ni!System.Windows.UIElement.OnGotKeyboardFocusThunk(System.Object, System.Windows.Input.KeyboardFocusChangedEventArgs)+0x76
    016FDFC0 62E3B0C1 PresentationCore_ni!System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(System.Delegate, System.Object)+0x31
    016FDFCC 62E120FE PresentationCore_ni!System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)+0x2e
    016FDFF0 62E12070 PresentationCore_ni!System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)+0x40
    016FE004 62E11E90 PresentationCore_ni!System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)+0xc0
    016FE070 62E10C29 PresentationCore_ni!System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)+0x79
    016FE0AC 62E20499 PresentationCore_ni!System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)+0x49
    016FE0D8 62E10B8B PresentationCore_ni!System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)+0x1b
    016FE0E8 62E3A0FD PresentationCore_ni!System.Windows.Input.InputManager.ProcessStagingArea()+0x20d
    016FE140 62E39DE9 PresentationCore_ni!System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)+0x49
    016FE150 62E3BA55 PresentationCore_ni!System.Windows.Input.KeyboardDevice.ChangeFocus(System.Windows.DependencyObject, Int32)+0x761
    016FE1E4 62E3AF55 PresentationCore_ni!System.Windows.Input.KeyboardDevice.TryChangeFocus(System.Windows.DependencyObject, System.Windows.Input.IKeyboardInputProvider, Boolean, Boolean, Boolean)+0x211
    016FE21C 62E3AB9C PresentationCore_ni!System.Windows.Input.KeyboardDevice.Focus(System.Windows.DependencyObject, Boolean, Boolean, Boolean)+0xb0
    016FE244 62E3AA93 PresentationCore_ni!System.Windows.Input.KeyboardDevice.Focus(System.Windows.IInputElement)+0x5f
    016FE258 62DFB812 PresentationCore_ni!System.Windows.UIElement.Focus()+0x1a
    016FE268 6284E60B PresentationFramework_ni!System.Windows.FrameworkElement.OnPreviewGotKeyboardFocus(System.Object, System.Windows.Input.KeyboardFocusChangedEventArgs)+0xd3fabf
    016FE27C 62E3B0C1 PresentationCore_ni!System.Windows.Input.KeyboardFocusChangedEventArgs.InvokeEventHandler(System.Delegate, System.Object)+0x31
    016FE288 62E120FE PresentationCore_ni!System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)+0x2e
    016FE2AC 62E12070 PresentationCore_ni!System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)+0x40
    016FE2C0 62E11F6A PresentationCore_ni!System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)+0x19a
    016FE32C 62E10C29 PresentationCore_ni!System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)+0x79
    016FE368 62E20499 PresentationCore_ni!System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)+0x49
    016FE394 62E10B8B PresentationCore_ni!System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)+0x1b
    016FE3A4 62E3A0FD PresentationCore_ni!System.Windows.Input.InputManager.ProcessStagingArea()+0x20d
    016FE3FC 62E39DE9 PresentationCore_ni!System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)+0x49
    016FE40C 62E3AE10 PresentationCore_ni!System.Windows.Input.KeyboardDevice.TryChangeFocus(System.Windows.DependencyObject, System.Windows.Input.IKeyboardInputProvider, Boolean, Boolean, Boolean)+0xcc
    016FE444 62E3AB9C PresentationCore_ni!System.Windows.Input.KeyboardDevice.Focus(System.Windows.DependencyObject, Boolean, Boolean, Boolean)+0xb0
    016FE46C 62E3AA93 PresentationCore_ni!System.Windows.Input.KeyboardDevice.Focus(System.Windows.IInputElement)+0x5f
    016FE480 62E33F8B PresentationCore_ni!System.Windows.Interop.HwndKeyboardInputProvider.OnSetFocus(IntPtr)+0xaf
    016FE4B8 62E0CA8E PresentationCore_ni!System.Windows.Interop.HwndKeyboardInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)+0x30e
    016FE564 62E0C211 PresentationCore_ni!System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)+0xb1
    016FE58C 6392E771 WindowsBase_ni!MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)+0xa1
    016FE5C8 6392EA5C WindowsBase_ni!MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)+0x6c
    016FE5D8 6392EF52 WindowsBase_ni!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)+0x52
    016FE5F8 6392EE95 WindowsBase_ni!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)+0x35
    016FE63C 6392D072 WindowsBase_ni!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)+0x142
    016FE698 6392E5C4 WindowsBase_ni!MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)+0xf4

StackTraceString: <none>
HResult: 80070057
---------------------------

Looks like HResult is 80070057

**Comment by zhuhaichao518** [comment]
Thanks for the information. Could you please specify the SDK version you
are using？

prat-coder ***@***.***>于2023年3月6日 周一17:55写道：

**Comment by prat-coder** [comment]
@zhuhaichao518 [1.0.1587.40](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1587.40) looks like the latest released sdk. 

[1.0.1619-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1619-prerelease) has the move focus fix as per release notes.
Do you recommend updating to [1.0.1587.40] version?

**Comment by zhuhaichao518** [comment]
@prat-coder Yes, it will be helpful if you can try it out and tell us if the bug still happens.
