### ISSUE TITLE
use wpf webview in excel vsto program issue error 0x80004002 when closing excel

### ISSUE THREAD

**Issue by zhizhuowq** [MicrosoftEdge/WebView2Feedback#3261]
I create wpf usercontrol  with webview2(version 1.0.1587.40), the control is defined like this
` public partial class WebView2Wrapper : UserControl
    {
        private CoreWebView2 CoreWebView2 => WebView2.CoreWebView2;
        private  CoreWebView2Settings Settings=>CoreWebView2.Settings;
        private  CoreWebView2Environment Environment => CoreWebView2.Environment;

        public static readonly DependencyProperty SourceProperty = DependencyProperty.Register(
            nameof(Source), typeof(Uri), typeof(WebView2Wrapper), new PropertyMetadata(default(Uri)));

        public Uri Source
        {
            get { return (Uri)GetValue(SourceProperty); }
            set { SetValue(SourceProperty, value); }
        }   
        public WebView2Wrapper()
        {
            InitializeComponent();
            WebView2.CreationProperties = new CoreWebView2CreationProperties()
                { UserDataFolder = AppDomain.CurrentDomain.BaseDirectory };
            DataContext = this;
            WebView2.CoreWebView2InitializationCompleted += CoreWebView2InitializationCompleted;
        }

        private void CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            if (e.IsSuccess)
            {
                Settings.IsPasswordAutosaveEnabled=true;
                IsInitialized=true;
                InitializeAction?.Invoke();
            }
            else
            {
                var ex = e.InitializationException;
                MessageBox.Show($"{ex.Message}\n{ex.StackTrace}");
            }
        }

        public bool IsInitialized;
        public Action InitializeAction;
        public  void ShowDialog()
        {
            
            var window= new Window()
            {
                Content = this,
                Topmost = true,
                WindowStartupLocation = WindowStartupLocation.CenterScreen,
                Width = 600,
                Height = 650
            };
            if (IsInitialized)
            {
                CoreWebView2.Navigate(Source.ToString());
            }
            //Source = Source;
            window.ShowDialog();
        }
    }`
`<UserControl
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:WebView2"
             xmlns:Wpf="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf" x:Class="WebView2.WebView2Wrapper"
             mc:Ignorable="d" 
             d:DesignHeight="450" d:DesignWidth="800">
    <Grid>

        <Wpf:WebView2 x:Name="WebView2" x:FieldModifier="public" Margin="5" Source="{Binding Source}"/>

    </Grid>
</UserControl>
`
 And then used it in excel vsto as follows, it works fine. but if I have ever actived the webview2 by clicking the button1, it will issue the error 0x80004002 like follows
` 
 public partial class Ribbon1
   {
 private WebView2Wrapper webView2;
  private void button1_Click(object sender, RibbonControlEventArgs e)
        {
            webView2 =webView2 ?? new WebView2Wrapper()
            {
                Source = new Uri(
                    "https://www.bing.com")
            };
            webView2.ShowDialog();
            
        }
}`
Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{7CCC5C7F-8351-4572-9077-9C1C80913835}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).

   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
  at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
  at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
 at  Microsoft.Web.WebView2.Wpf.WebView2.Uninitialize(Boolean browserCrashed)
 at Microsoft.Web.WebView2.Wpf.WebView2.Dispose(Boolean disposing)

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by ElyssaJyu** [comment]
Hi @zhizhuowq, It seems the issue will happen when you click on button1, then close excel. If I understand correctly and we are on the same page, I would like to confirm what your workaround about this issue. 

- After you click button1, does webview2 install successfully and show the bing website? 
- After clicking button1(if webview2 has installed successfully), does webview2 dispose when closing dialog in the excel?
- Do you leave webview2 launching when closing excel?
- Does the issue occur only at the time when you close excel? 

The cause might be you're not disposing the webview2 control, which under the hood is dependent on a COM object. Also, please see [this comment](https://github.com/MicrosoftEdge/WebView2Feedback/issues/246#issuecomment-670250036). Hope this might help you. Thanks

**Comment by zhizhuowq** [comment]
Hi, @ElyssaJyu. Yes, when I click button1, the bing website shows correctly. And I have closed the wpf dialog which contains WebView2 before I close Excel.  The error will only occur when I closed Excel.  

Also, I tested the  WebView2 of WinForm namespace(create a new form instanse and add a WebView2 instanse to it's Children Property), it works fine, and the error will not occur when I close Excel.
In both situation, I don't call Dispose method of the WebView2 in my code. 

After that, I did another test: if I call Wpf.WebView2.Dispose method in the Ribbon Closed event handler, the error will not occur when I close Excel.

**Comment by ElyssaJyu** [comment]
The root cause is that Webview2 was initialized in the interface, and then you created a new WebviewWrapper class which referenced that webview2 inside it. When the application exited, webview2 was disposed, but WebviewWrapper still held a reference to webview2. A workaround is to manually dispose WebView2 controls before application exit. 
Does any other issue block your work?

**Comment by zhizhuowq** [comment]
I think webview2 inside isn't disposed correctly when vsto addin closed. Although used the same way, the webview2wrapper is work correctly is windows desktop application project，but don't in vsto addin project. In vsto project, it needs call inside webview2.Dispose() manually before closing the application.

**Comment by ElyssaJyu** [comment]
Could you confirm that whether WebView disposes when you close vsto addin in an opening excel? (it looks like not)

I have opened a bug on our backlog to look into some potential fixes. Please consider manually dispose WebView before closing vsto addin right now, for unblocking your following work. Thanks

**Comment by zhizhuowq** [comment]
Yes, if I don't dispose the WebView2 manually, the error will rise when closing Excel. There may be a bug when CLR dispose webview2. As you suggest, I will dispose webview2 manually in my project to avoid this bug.
