### ISSUE TITLE
Bug: Null Reference Exceptions

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#3402]
I'm running into a null reference exception in CoreWebView2PrivateHostObjectHelper. In the debugger I can see where the exception originates:

![image](https://user-images.githubusercontent.com/1374013/232671552-f65aa84d-3e87-469e-a580-2db9d045e6e6.png)

The stack trace doesn't originate in my code but the code I'm launching from has to do with WebView key handling which no longer works and appears to have been broken.

In my logs, however the error shows up as:

```text
4/17/2023 6:22:49 PM - AppRoot: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Markdown Monster v2.8.15.1
10.0.22621.1.amd64fre.ni_release.220506-1250 - en-US - NET 4.8 - 64 bit
Dell Inc. XPS 15 9520, NVIDIA GeForce RTX 3050 Laptop GPU, hw-acc: True
en-US - en-US    
---
WindowsBase
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at StartUp.Main() in D:\projects\MarkdownMonsterCode\MarkdownMonster\Program.cs:line 53
System.AccessViolationException
---------------------------
``` 

I'm seeing a ton of these in my application and I suspect they are all hitting this same issue.

**Comment by RickStrahl** [comment]
After a little more exploration in my code this is due to my Alt-Menu key forwarding code that has been working but is now failing.

I ended up changing the call on client side from sync JavaScript to Async and that now doesn't hit that codebase. However, the issue still remains that there's some problem in the above outlined method where apparently the incoming type is null and should probably be checked for.

```csharp
// check for Windows Alt-Menu behavior
// delay trigger menu so native alt- key processing can work
if (te.mm && event.key == "Alt" && !event.ctrlKey && !event.shiftKey) {
    te.lastAltkeyTime = new Date().getTime();
    
    setTimeout(async function () {
        console.log("alt key triggered 2 (timeout)");
        var t = new Date().getTime();
        //console.log('alt timeout: ' + (t - te.lastAltkeyTime), t, te.lastAltkeyTime);
        // other key or more than 5 secs
        if (te.lastAltkeyTime == 0 || t - te.lastAltkeyTime > 5000) {
            te.lastAltkeyTime = 0;
            return;
        }                        
        // await here avoids the exception here compared to sync call used previously
        await te.mmAsync.TriggerWindowAltMenu();                        
    }, 500);
} else
    te.lastAltkeyTime = 0;
```

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by RickStrahl** [comment]
Just as a follow up - I made the JS Async method fix I described above that **avoids a drive-by of this method**. As soon as I made this change I stopped getting the

**Attempted to read or write protected memory.**

errors in my log. I've moved to production and haven't seen any of those errors in the last 2.5 days so pretty sure that was the problem.

The above error and code path due the synthetic async context was the likely trigger for that very hard to debug error.

I do wonder why the failed type check and null reference exception would eventually end up reporting a  
**Attempted to read or write protected memory.** error though - that seems... harsh and very hard to debug as the stack trace is wiped out, pointing back only to the App root (`App.Run()`)

**Comment by lostobject** [comment]
I am also seeing this exception in a different scenario. In my case I am calling async methods on the HostObject (updating my app to use #75) and trying to propagate exceptions back to javascript. This works fine for synchronous HostObject methods but async ones trigger the NullReferenceException on the same line of code as posted above.

WebView2 version: 1.0.2151.40

Here is the relevant code from the HostObject:
```C#
        public string TestMessage(string msg)
        {
            throw new ArgumentException();
        }

        public async Task<string> TestMessageAsync(string msg)
        {
            await Task.Run(() => throw new ArgumentException());
            return msg;
        }
```

And the test html page:
```js
    async function Test1() {
        try {
          let external = await window.chrome.webview.hostObjects.external;
          let data = await external.TestMessage("test sync call);
          document.getElementById("result-TestMessage").value = data;
        } catch (e) {
          document.getElementById("result-TestMessage").value = `Error: ${e.toString()}`;
        }
    }

    async function Test2() {
        try {
          let external = await window.chrome.webview.hostObjects.external;
          let data = await external.TestMessageAsync("test async call);
          document.getElementById("result-TestMessage").value = data;
        } catch (e) {
          document.getElementById("result-TestMessage").value = `Error: ${e.toString()}`;
        }
    }
```
Running `Test1()` renders the expected output:
`Error: Error: Value does not fall within the expected range.`

Running `Test2()` results in the internal `NullReferenceException` and the application crashes:
Microsoft.Web.WebView2.Core.dll!Microsoft.Web.WebView2.Core.CoreWebView2PrivateHostObjectHelper.RawHelper.SetAsyncMethodContinuation.AnonymousMethod__0() Line 100	C#

**Comment by NiklasPor** [comment]
@lostobject did you manage to work out a workaround? I'm running into the exact same issue, oterwise I'll need to wrap every of my tasks for error handling 👁️

**Comment by lostobject** [comment]
@NiklasPor No I have not found any workarounds other than 'make sure exceptions never get thrown'. This is not a valid workaround for me since I need to propagate errors back to javascript. 

@david-risney Has there been any progress on this issue from your side?

**Comment by LiangTheDev** [comment]
Changes for https://github.com/MicrosoftEdge/WebView2Feedback/issues/4509 might have changed the behavior. Is there any repro after updating WebView2 SDK to version > 1.0.2562?

**Comment by 3ldor** [comment]
> Changes for #4509 might have changed the behavior. Is there any repro after updating WebView2 SDK to version > 1.0.2562?

Seems like the browser no longer crashes, and a JavaScript exception is triggered as expected. The exception doesn't seem to contain any of the originating information however, the message always seems to be `Error (0x13D) while retrieving error. (0x80131604)`, so I wouldn't consider this fixed.
