### ISSUE TITLE
COMException during WebView2 initialization when multiple instances are running with remote-debugging-port set

### ISSUE THREAD

**Issue by ztanczos** [MicrosoftEdge/WebView2Feedback#3449]
**Description**
In a simple WPF application I set the remote debugging port to a random value between 8000 and 9000 and simply navigate to https://www.microsoft.com. The first instance of the application works fine, however if I start any subsequent instance I get the following COMException: The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__88.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass34_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WpfApp3.MainWindow.<Initialize>d__1.MoveNext() in C:\Users\ztanc\source\repos\WpfApp3\WpfApp3\MainWindow.xaml.cs:line 33

**Version**
SDK: 1.0.1722.45
Runtime: 112.0.1722.64 
Framework: WPF
OS: Win10, Win11

**Repro Steps**
My MainWindow.xaml:
```
<Window x:Class="WpfApp3.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        xmlns:local="clr-namespace:WpfApp3"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <wv2:WebView2 x:Name="webView" />
    </Grid>
</Window>
```

MainWindow.xaml.cs:
```
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            Initialize();
        }

        public async Task Initialize()
        {
            int port = new Random().Next(8000, 9000);
            await webView.EnsureCoreWebView2Async(await CoreWebView2Environment.CreateAsync(options: new CoreWebView2EnvironmentOptions($"--remote-debugging-port={port}")));
            webView.Source = new Uri("https://www.microsoft.com");
        }
    }
```

**Comment by champnic** [comment]
Hey @ztanczos - Thanks for the bug report. This behavior is By Design.

The way WebView2 works is that it has a 1:1 user data folder to browser runtime processes relationship. What this means is that when you create the first WebView2 it uses the app's default user data folder and creates a set of browser processes to power the WebView2, using the command line that you pass in, including the remote debugging port. When you try to initialize a new WebView2 it uses the same user data folder and so attempts to connect to the already running browser processes. However, because you've randomized the debugger port (and thus randomized the command line) it notices the command lines don't match and so fails to connect.

The possible fixes are:
1. to use the same remote debugging port (therefor same command line for each WebView2 that has the same user data folder.
2. to use a shared environment for each WebView2 (which is similar to above)
3. to use separate user data folders for each WebView2 (not recommended - this will result in a new set of browser processes for every WebView2, as well as duplicated space on disk for the extra user data folders)

Hope this helps!
