### ISSUE TITLE
Getting "Cannot change thread mode after it is set" error in .NET 7 Console application

### ISSUE THREAD

**Issue by UweKeim** [MicrosoftEdge/WebView2Feedback#3475]
This is my whole program for a .NET 7 Console application running as 64-bit on Windows 11:

```c#
internal static class Program
{
    private static readonly IntPtr HWND_MESSAGE = new(-3);

    [STAThread]
    private static async Task Main()
    {
        var runtimePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"WebView2");
        var environment = await CoreWebView2Environment.CreateAsync(runtimePath);

        const int width = 1000;
        const int height = 2000;

        var browserController = await environment.CreateCoreWebView2ControllerAsync(HWND_MESSAGE);
        browserController.BoundsMode = CoreWebView2BoundsMode.UseRawPixels;
        browserController.Bounds = new(0, 0, width - 1, height - 1);

        browserController.CoreWebView2.NavigationCompleted += async delegate
        {
            await using var fs = new FileStream($@"C:\Ablage\image-{DateTime.Now.Ticks}.png", FileMode.Create);
            await browserController.CoreWebView2.CapturePreviewAsync(CoreWebView2CapturePreviewImageFormat.Png, fs);
        };

        browserController.CoreWebView2.Navigate(@"https://www.bing.com");

        Console.ReadLine();
    }
}
```

When starting it, the call to `CoreWebView2Environment.CreateAsync` throws an error:

> Cannot change thread mode after it is set

The call stack is:

```
System.Runtime.InteropServices.COMException
  HResult=0x80010106
  Message=Der Threadmodus kann nicht nach dem Einstellen geändert werden. (0x80010106 (RPC_E_CHANGED_MODE))
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode) in System.Runtime.InteropServices\Marshal.cs:line 1283
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext() in Microsoft.Web.WebView2.Core\CoreWebView2Environment.cs:line 652
   at HeadlessConsoleTest.Program.<Main>d__2.MoveNext() in C:\Projects\HeadlessConsoleTest\Program.cs:line 14
   at HeadlessConsoleTest.Program.<Main>(String[] args)
```

I've tried to remove the `[STAThread]` attribute and also tried to change it to `[MTAThread]` but this did not change the error message.

My CSPROJ file looks like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1774.30" />
    <PackageReference Include="WebView2.Runtime.X64" Version="113.0.1774.35" />
  </ItemGroup>
</Project>
```

When running the same code inside a WinForms .NET 7 application, the code runs successfully.

### My question

How should I change my code in order to successfully use WebView2 inside a console application?

**Comment by UweKeim** [comment]
Thanks, @sln162, I'm aware of #202 and checked everything there.

Could you clarify what you imply that I did wrong?

**Comment by plantree** [comment]
Hi @UweKeim,

@sln162‘s right. Do you want to run WebView2 in a console application? If it does, you can follow https://github.com/MicrosoftEdge/WebView2Feedback/issues/202.

Hope to solve your problem.
