### ISSUE TITLE
Webview2 Initialization exception -- Specified cast is not valid. StackTrace

### ISSUE THREAD

**Issue by flashyyp123** [MicrosoftEdge/WebView2Feedback#3504]
The following is the exception information:

Initialization exception ex.GetType():System.InvalidCastException  ,ex.HResult & 0x0000FFFF:16386, ex.HResult:-2147467262 ,ex.Message:Specified cast is not valid. StackTrace:   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.T

**Comment by flashyyp123** [comment]
I also report a related BUG#3329, #3329 Can resolve by restarting the Explorer,But This is invalid.

**Comment by champnic** [comment]
Hey @flashyyp123 - Can you add more info to this issue, including what framework you are using, WebView2 runtime and SDK versions, and perhaps some sample code or a sample app we can use to reproduce this issue?

**Comment by champnic** [comment]
I'm unable to repro. Have you tried with the latest evergreen runtime version (113+)? Does it still repro?

**Comment by flashyyp123** [comment]
It's accidental. It's just a matter of reinstalling the system

**Comment by champnic** [comment]
Ok, my understanding of your comment is that it was a transient issue and that you got it resolved, so I'm going to close this issue. Let me know if that's not what you meant. Thanks!
