### ISSUE TITLE
Edge webview initialization failing during shutting down of system

### ISSUE THREAD

**Issue by devbrats** [MicrosoftEdge/WebView2Feedback#3574]
During the system shutting down, some edgewebview process is exiting causing the below exception:
ProcessFailedException in View : Browser Process failed having  process failed kind as: RenderProcessExited, Reason: Unexpected, Description:  , Framed information for the failed process:  and Exit code is :0. Sender details as Microsoft.Web.WebView2.Core.CoreWebView2 and browser process version is 112.0.1722.68

To handle the above scenario we registered one event handler for ProcessFailed event which tries to initialize webview again: edgeWebView.CoreWebView2.ProcessFailed += CoreWebView2_ProcessFailed;

During initialization we are getting the following error:
System.Exception: Exception occur while Initializing Edge webview2:System.Runtime.InteropServices.COMException (0x80070270): {DLL Initialization Failed} The application failed to initialize because the window station is shutting down. (Exception from HRESULT: 0x80070270)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at <<Initialize>b__23_0>d.MoveNext()

I tried to capture SystemEvents.SessionEnding to set a flag and use the flag to manage initialization but  edgewebview initialization is occuring before the capturing of the SessionEnding event, so basically the flag is not setting.
Is there any better way to handle this scenario like ProcessFailed event should not be triggered if system is shutting down?

**Comment by novac42** [comment]
Thanks for reporting the issue. May you also let us know the framework you are using and OS version?

**Comment by devbrats** [comment]
.Net Framework version is 4.8 and OS is windows 10 or 11.

**Comment by yunate** [comment]
Hi, @devbrats, thanks for your feedback!
SessionEnding may be helpful: [SessionEnding](https://learn.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents.sessionending?view=dotnet-plat-ext-7.0). And there are some APIs which could query the state: `GetSystemMetrics(SM_SHUTTINGDOWN)`.
