### ISSUE TITLE
How to enable the browser extensions in WebView2?

### ISSUE THREAD

**Issue by mikeduglas** [MicrosoftEdge/WebView2Feedback#3694]
[Edge Add-ons page](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home?hl=en) doesn't allow to get browser extensions for WebView2, it says:

> To install add-ons, you'll need the new Microsoft Edge.[Download the new Microsoft Edge](https://www.microsoft.com/en-us/edge)

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/12225093/ef866d38-4b83-4118-aaaa-40b639ba038a)

My WebView2 instance uses AreBrowserExtensionsEnabled==true environment option, also user agent string is 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2024.0).

- SDK: 1.0.1988-prerelease
- WebView2 runtime: 117.0.2024.0 canary
- Platform: WinForms/Win32

**Comment by novac42** [comment]
@mikeduglas Thanks for trying out the experimental extension API! If possible may you share a sample app for us to reproduce the issue?

**Comment by dianaqu** [comment]
Hi,

Thanks for trying out our feature. It's by design to not allow extension to be installed throw the store. If you want to use extension you can use our API to install it. I  can follow with my team to update you if we plan to support the extension store in the future.

**Comment by mikeduglas** [comment]
@dianaqu Thanks for the quick reply. 
If I'm correct, I need to download the installer of an extension, then call AddBrowserExtensionAsync(installerPath) to install it. But all the usefult extensions are located in Microsoft Store which doesn't allow to download the installer. This makes your new Extension API quite useless.

**Comment by nishitha-burman** [comment]
Hello, WebView2 does not plan to support installing extensions in WebView2 through Edge/Edge Store. Edge and WebView2 are different entities and an extension being in Edge Store does not mean it is licensed to be used in WebView2. What WebView2 does support is a BYO extension mechanism where developers source their own extensions and are compliant with the extension's license. 

Thank you!

**Comment by jeremiahjordanisaacson** [comment]
@nishitha-burman Can you please provide the code example on how to add a C# UWP BYO extension? I can't find an example online or using ChatGPT.

**Comment by victorhuangwq** [comment]
We have a C++ sample code here as well: https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WebView2APISample/ScenarioExtensionsManagement.cpp

**Comment by jeremiahjordanisaacson** [comment]
@jeremiahjordanisaacson Thanks for the response. It would be nice to have a C# example.

**Comment by AdvancedNotifier** [comment]
For me, it does not work with .NET C# WinForms, too. I've tried version 1.0.2357-prerelease with this code:

    CoreWebView2.Profile.AddBrowserExtensionAsync("C:\\Temp")
        .ContinueWith(
            (task) =>
            {
                if (task.IsFaulted)
                    Debug.WriteLine(task.Exception.Message);
            });

As a result, I get this exception:

    One or more errors occurred. (The request is not supported. (0x80070032))

(I translated the message from German.)

Inside my "C:\Temp" folder, I have the file "manifest.json" and the whole directory is an extraction of Edge Extension.

**Comment by softworkz** [comment]
> @jeremiahjordanisaacson Thanks for the response. Can you please help with providing a **UWP** **C#** example, as I'm sure other folks will appreciate it. I've tested this using your provided C++ example as a reference and it's not working for C# UWP using the recommended library from Microsoft's docs site (e.g., [Microsoft is recommending](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2#step-5---install-the-winui-2-sdk-microsoftuixaml) using the "Microsoft.UI.Xaml" file which has "Microsoft.Web.WebView2" as a dependency, so it's also installed).

The method is under Profile now: `webView2.CoreWebView2.Profile.AddBrowserExtensionAsync()`
and the event is named `CoreWebView2Initialized` and the event args: `CoreWebView2InitializedEventArgs`

**Comment by softworkz** [comment]
> @dianaqu Thanks for the quick reply. If I'm correct, I need to download the installer of an extension, then call AddBrowserExtensionAsync(installerPath) to install it. But all the useful extensions are located in Microsoft Store which doesn't allow to download the installer. This makes your new Extension API quite useless.

Don't waste your time with "downloaders" or trying to determince the store url and unpacking. It's much easier this way:

- Find the desired extension in the store
- Install it in MS Edge
- Go to: `C:\Users\<YourUsername>\AppData\Local\Microsoft\Edge\User Data\Default\Extensions`
- Copy the folder of the desired extension 
  (the folder name is the extension id)

You can use the folder as-is with `AddBrowserExtensionAsync()`

**Comment by AdvancedNotifier** [comment]
> @dianaqu Thanks for the quick reply. If I'm correct, I need to download the installer of an extension, then call AddBrowserExtensionAsync(installerPath) to install it. But all the useful extensions are located in Microsoft Store which doesn't allow to download the installer. This makes your new Extension API quite useless.

I don't agree with you. You can download the extension from the store programmatically by using this URL:

https://edge.microsoft.com/extensionwebstorebase/v1/crx?response=redirect&x=id%3D[EXTENSION_ID]%26installsource%3Dondemand%26uc

... [EXTENSION_ID] is the id of the Extension inside the Edge Store.

With this, you get a .crx file.

You can unpack them with this method:

    public static void UnpackCrxFile(string crxFilename, string destinationPath)
    {
        const int MinimumCrxHeaderLength = 12;

        string tempFilename;

        using (var stream = File.Open(crxFilename, FileMode.Open))
        {
            if (!Directory.Exists(destinationPath))
                Directory.CreateDirectory(destinationPath);

            if (stream.Length < MinimumCrxHeaderLength)
                throw new FileFormatException(
                    "Could not find Crx file header at the begin of the file \"" + Path.GetFileName(crxFilename) + "\".");

            var buffer = new byte[4];
            stream.Read(buffer, 0, buffer.Length);
            if (Encoding.ASCII.GetString(buffer) != "Cr24")
                throw new FileFormatException("Invalid Crx file header");

            stream.Read(buffer, 0, buffer.Length);
            var version = BitConverter.ToUInt32(buffer, 0);
            if (version != 3)
                throw new FileFormatException(string.Format("Invalid Crx version ({0}). Only Crx version 3 is supported.", version));

            stream.Read(buffer, 0, buffer.Length);
            var headerLength = BitConverter.ToUInt32(buffer, 0);
            if (stream.Length < stream.Position + headerLength)
                throw new FileFormatException(string.Format("Invalid Crx header length ({0}).", headerLength));

            stream.Seek(headerLength, SeekOrigin.Current);


            tempFilename = Path.GetTempFileName();
            File.Delete(tempFilename);
            using (var fileStream = File.Create(tempFilename))
                stream.CopyTo(fileStream);
        }

        using (var zipArchive = ZipFile.OpenRead(tempFilename))
            zipArchive.ExtractToDirectory(destinationPath, true);

        File.Delete(tempFilename);
    }

And now, you can use `AddBrowserExtensionAsync()`.

**Comment by Tajmi** [comment]
Hi is it possible to make them working if  we are in private mode? `CoreWebView2ControllerOptions op = ev.CreateCoreWebView2ControllerOptions();
			op.ProfileName = "SomeRandomProfileName";
			op.IsInPrivateModeEnabled = true;` The show that Extension is enabled if i call `await webView2.CoreWebView2.Profile.GetBrowserExtensionsAsync();` but they are not working. Any ideas? :/

**Comment by SequPL** [comment]
![image](https://github.com/user-attachments/assets/98ee7d76-6f41-4b26-b54b-260be0195753)
```c#
 e.EnvironmentOptions = new()
 {
     AreBrowserExtensionsEnabled = true,
 };
 ```
 should help, but in latest  version throw exception : 
 
 ```
 System.InvalidCastException: No such interface supported

No such interface supported

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.Web.WebView2.Core.ICoreWebView2EnvironmentOptions6Methods.set_AreBrowserExtensionsEnabled(IObjectReference _obj, Boolean value)
   at Microsoft.Web.WebView2.Core.CoreWebView2EnvironmentOptions.set_AreBrowserExtensionsEnabled(Boolean value)
   ```

**Comment by michTheBrandofficial** [comment]
Hi, guys 🙋‍♂️.
I am also encountering this issues with an application I made. A device simulator application (picture of it down below) relies heavily on webview2 as it was built with Tauri. 
My main problem is that I dont know any C# code and even if I unpack the extension, I wont know where to move from there.
![image](https://github.com/user-attachments/assets/870efa65-ca77-4757-86fe-39e72a8b916a)

I would appreciate any kind of help.

**Comment by Sparkenstein** [comment]
This makes no sense, If you are allowed to install extensions "somehow" why not just save the efforts and allow them installing directly? The way I understand it, It's not even a security risk as installing them is "easy" with C++ or C#

**Comment by SequPL** [comment]
Whould be nice to install extensions directly from a DevTools opened "from" application (in my case Windows app)/or setup these extensions from the code - what is possible with android app (MAUI app), when remote debugging from MS Edge - then you can use your normal browser with all installed extensions without limits.

...but for Windows app i cannot use browser extensions (e.g. css inspector) ...

**Comment by mrmattipants** [comment]
> > [@dianaqu](https://github.com/dianaqu) Thanks for the quick reply. If I'm correct, I need to download the installer of an extension, then call AddBrowserExtensionAsync(installerPath) to install it. But all the useful extensions are located in Microsoft Store which doesn't allow to download the installer. This makes your new Extension API quite useless.
> 
> I don't agree with you. You can download the extension from the store programmatically by using this URL:
> 
> [https://edge.microsoft.com/extensionwebstorebase/v1/crx?response=redirect&x=id%3D[EXTENSION_ID]%26installsource%3Dondemand%26uc](https://edge.microsoft.com/extensionwebstorebase/v1/crx?response=redirect&x=id%3D%5BEXTENSION_ID%5D%26installsource%3Dondemand%26uc)
> 
> ... [EXTENSION_ID] is the id of the Extension inside the Edge Store.
> 
> With this, you get a .crx file.
> 
> You can unpack them with this method:
> 
> ```
> public static void UnpackCrxFile(string crxFilename, string destinationPath)
> {
>     const int MinimumCrxHeaderLength = 12;
> 
>     string tempFilename;
> 
>     using (var stream = File.Open(crxFilename, FileMode.Open))
>     {
>         if (!Directory.Exists(destinationPath))
>             Directory.CreateDirectory(destinationPath);
> 
>         if (stream.Length < MinimumCrxHeaderLength)
>             throw new FileFormatException(
>                 "Could not find Crx file header at the begin of the file \"" + Path.GetFileName(crxFilename) + "\".");
> 
>         var buffer = new byte[4];
>         stream.Read(buffer, 0, buffer.Length);
>         if (Encoding.ASCII.GetString(buffer) != "Cr24")
>             throw new FileFormatException("Invalid Crx file header");
> 
>         stream.Read(buffer, 0, buffer.Length);
>         var version = BitConverter.ToUInt32(buffer, 0);
>         if (version != 3)
>             throw new FileFormatException(string.Format("Invalid Crx version ({0}). Only Crx version 3 is supported.", version));
> 
>         stream.Read(buffer, 0, buffer.Length);
>         var headerLength = BitConverter.ToUInt32(buffer, 0);
>         if (stream.Length < stream.Position + headerLength)
>             throw new FileFormatException(string.Format("Invalid Crx header length ({0}).", headerLength));
> 
>         stream.Seek(headerLength, SeekOrigin.Current);
> 
> 
>         tempFilename = Path.GetTempFileName();
>         File.Delete(tempFilename);
>         using (var fileStream = File.Create(tempFilename))
>             stream.CopyTo(fileStream);
>     }
> 
>     using (var zipArchive = ZipFile.OpenRead(tempFilename))
>         zipArchive.ExtractToDirectory(destinationPath, true);
> 
>     File.Delete(tempFilename);
> }
> ```
> 
> And now, you can use `AddBrowserExtensionAsync()`.

Thanks for the Download Link. Still works as anticipated.

I also wanted to note that you can also use 7-Zip to Extract the contents of the .CRX File.

**Comment by 59de44955ebd** [comment]
For those using plain C - or Python and libffi, as in my case - the best solution I could come up with is to create a custom loader .dll in VisualStudio and C++ that wraps `CreateCoreWebView2EnvironmentWithOptions` and links statically to WebView2Loader.lib, and then use this custom loader .dll instead of `WebView2Loader.dll` for creating an environment. My custom loader .dll exports a single function `CreateEnvironmentWithOptions` that I can call from Python (or C) and that is currently implemented like this:

```
LOADER_API HRESULT CreateEnvironmentWithOptions(
	LPCWSTR browserExecutableFolder,
	LPCWSTR userDataFolder,
	LPCWSTR additionalBrowserArguments,
	LPCWSTR language,
	BOOL browserExtensionsEnabled,
	ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler * handler
)
{
	auto options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
	if (additionalBrowserArguments)
		options->put_AdditionalBrowserArguments(additionalBrowserArguments);
	if (language)
		options->put_Language(language);
	options->put_AreBrowserExtensionsEnabled(browserExtensionsEnabled);
	return CreateCoreWebView2EnvironmentWithOptions(
		browserExecutableFolder,
		userDataFolder,
		options.Get(),
		handler
	);
}
```

It allows me to enable browser extensions in WebView2, I currently use this to load [uBlock Origin Lite](https://microsoftedge.microsoft.com/addons/detail/ublock-origin-lite/cimighlppcgcoapaliogpjjdehbnofhn) from a local folder (that I created by extracting its .crx file with 7-Zip).
