### ISSUE TITLE
CoreWebView2 members cannot be accessed after removing DownloadStarting event

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#3750]
**Description**
In our application we seem to dispose the `WebView2` (and `CoreWebView2`) objects before we remove their event handlers. We have always done it this way and so far it has worked with all event handlers, for Microsoft-based controls and for other controls.

Now we have added the `DownloadStarting` event and we are trying to remove it in a similar manner, however we get an exception:
> Exception : System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed. ---> System.Runtime.InteropServices.COMException: The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_4.remove_DownloadStarting(EventRegistrationToken token)
   at Microsoft.Web.WebView2.Core.CoreWebView2.remove_DownloadStarting(EventHandler`1 value)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2.remove_DownloadStarting(EventHandler`1 value)

Is this something that can be fixed on your end? We rely on the behavior that event handlers can still be removed even though the object it is attached to is disposed.

**Version**
SDK: 1.0.1938.49
Runtime: 117.0.2045.12 beta
Framework: WinForms
OS: Win10, Version 22H2 (Build 22621.2134)

**Comment by champnic** [comment]
Hey @fvanheeswijk - thanks for catching this issue. I've added it to our backlog to try and address before 117 stable runtime is released.

**Comment by champnic** [comment]
Actually it looks like this bug has always been there with DownloadStarting event and isn't a regression in the runtime, is that right?

**Comment by fvanheeswijk** [comment]
> Actually it looks like this bug has always been there with DownloadStarting event and isn't a regression in the runtime, is that right?

That I don't know for sure, we have just started using this event.

**Comment by champnic** [comment]
@fvanheeswijk I took a look and it seems most of our events on the Core* objects function in a similar manner, where if they are already disposed then throw an exception when removing an event. 

Is there a different CoreWebView2* event you were using where this was working as you expect? This behavior is By Design, as nearly everything in the CoreWebView2* objects shouldn't be accessed after they're disposed, due to underlying COM objects being destroyed. Is there a reason you need to remove the event handlers after Dispose(), or just an existing pattern?
