### ISSUE TITLE
 webView.CoreWebView2 throws an exception on look up

### ISSUE THREAD

**Issue by farzonl** [MicrosoftEdge/WebView2Feedback#3821]
**Description**
I have a VSTO word app. I want to upgrade to Webview2 for web navigation.
Following the win form tutorial:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms

I can set the source.  However, I can't call `webView.CoreWebView2.Navigate(address);`
If I check if `CoreWebView2` is valid the application throws an exception.

I've experimented with trying to force on the UI Thread a function that calls ` webView.EnsureCoreWebView2Async` like so:
```csharp
this.syncContext = SynchronizationContext.Current;
ThreadPool.QueueUserWorkItem(_ =>
{
    // worker thread starts
    // invoke UI from here
    this.syncContext.Send(_ => InitializeAsync(), null);
});
```
And setting competition callbacks
```csharp
private void CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
{
    if (e.IsSuccess)
    {
        IsInitialized = true;
    }
    else
    {
        var ex = e.InitializationException;
        MessageBox.Show($"{ex.Message}\n{ex.StackTrace}");
    }
}
```
All of these appear to complete successfully. That said none have made it possible for me to use `CoreWebView2`

**Version**
Reproduced on two machines
Windows 11 version: 10.0.22000.0
Windows 10 version 10.0.19045.0
Webview2 nuget version: 1.0.2045.28
Edge Version: 116.0.1938.81
Version of Webview2: 117.0.2045.43

I find it really odd my WebView version is newer than my browser. 

**Regression**
```bash
Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{4D00C0D1-9434-4EB6-8078-8697A560334F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).


************** Exception Text **************
System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{4D00C0D1-9434-4EB6-8078-8697A560334F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.WinForms.WebView2.get_CoreWebView2()
```

**Repro Steps**
```csharp
 public partial class WebviewForm : UserControl { 
     public static readonly string Title = "Webview";

     public WebviewForm()
     {
         InitializeComponent();
        var userDataFolder = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "MY__APP__NAME");
        var webView2Environment = await CoreWebView2Environment.CreateAsync(null, userDataFolder, options);
        await webView.EnsureCoreWebView2Async(webView2Environment);
}

public void Navigate(string addressText)
{
            Debug.Assert(webView != null && webView.CoreWebView2 != null);
            if (IsInitialized)
            {
                webView.CoreWebView2.Navigate(addressText);
            }
}
```
**ScreenShots***
My work around is to  just set Source before calling  ` webView.EnsureCoreWebView2Async` 

I see a number of exceptions get thrown in that case:
Exception thrown: 'System.UnauthorizedAccessException' in Microsoft.Web.WebView2.Core.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Exception thrown: 'System.MissingMethodException' in Microsoft.Web.WebView2.WinForms.dll
Exception thrown: 'System.UnauthorizedAccessException' in Microsoft.Web.WebView2.WinForms.dll

If I print out one of the exception messages to a messageBox I see: 
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1802579/f13440e9-7f9b-4746-a847-7515e6afb81c)

```bash
Exception thrown: 'System.UnauthorizedAccessException' in Microsoft.Web.WebView2.Core.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__26.MoveNext()
```

I solved my first UnauthorizedAccessException using this comments feeback hence why I do ` await webView.EnsureCoreWebView2Async(webView2Environment);` and not ` await webView.EnsureCoreWebView2Async(null);`
https://github.com/MicrosoftEdge/WebView2Feedback/issues/271#issuecomment-796760273

The debug assert gives slightly more context
```bash
Exception thrown: 'System.UnauthorizedAccessException' in Microsoft.Web.WebView2.Core.dll
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__26.MoveNext()
Exception thrown: 'System.UnauthorizedAccessException' in Microsoft.Web.WebView2.WinForms.dll
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----

---- Assert Long Message ----

   at EdgeSecurityReview.WebviewForm.<>c__DisplayClass12_0.<NavigateWebView>b__3(Object _) in \WebviewForm.cs:line 126
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Exception thrown: 'System.MissingMethodException' in Microsoft.Web.WebView2.WinForms.dll
The thread 0x8324 has exited with code 0 (0x0).
The thread 0xb038 has exited with code 0 (0x0).
The thread 0x6630 has exited with code 0 (0x0).
The thread 0x99f4 has exited with code 0 (0x0).
```

One  more thing of note:

All the `System.UnauthorizedAccessException` go away if I run as administrator. So webview must be trying to write files some where it shouldn't.  I thought I handled that with `webView2Environment`? Is there something else that is writing files?
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1802579/4a10a3b9-2631-401d-bba6-09f07c223a12)

However in Administrator mode the call stack still looks the same. Only the exceptions have changed. From `System.UnauthorizedAccessException` to `System.ArgumentException` and `System.Reflection.TargetInvocationException`.

```bash
Exception thrown: 'System.ArgumentException' in Microsoft.Web.WebView2.WinForms.dll
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----

---- Assert Long Message ----

   at EdgeSecurityReview.WebviewForm.<>c__DisplayClass12_0.<NavigateWebView>b__3(Object _) in \WebviewForm.cs:line 126
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
```

**Comment by champnic** [comment]
Hey @farzonl - I believe this is all expected. You shouldn't be setting Source property and also calling EnsureCoreWebView2Async. The AccessFailed is due to trying to create the user data folder inside the protected Office folder location. Here are some changes you should make:
1. Remove the Source property setting.
2. Use EnsureCoreWebView2Async instead to do the WebView2 initialization.
3. Set a custom user data folder location in a known writeable location, something like `Application.LocalUserAppDataPath`.
Let me know if you are still running into other issues.
