### ISSUE TITLE
[Problem/Bug]: When msedgewebview2 is already running (in task manager) and I try to run my webview2 project, an exception is thrown

### ISSUE THREAD

**Issue by carrie-battaglia** [MicrosoftEdge/WebView2Feedback#4163]
### What happened?

When I build my .NET project using VS 2022 - the build launches msedgewebview2.exe processes and then does not shut down those processes.
Then when I run my application that uses webview2, I get an exception and I cannot launch my webview2 dialog.  To get it to work, I need to open task manager and shut down the msedgewebview2 processes.

This happens in multiple projects.  Is there something I need to do prior to EnsureCoreWebView2Async so this does not happen?

Exception on this call:
 await webView.EnsureCoreWebView2Async(null);
 
Exception:
System.Runtime.InteropServices.COMException
  HResult=0x8007139F
  Message=The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
  Source=mscorlib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__80.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__24.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SmartViewWebTrace.Form1.<InitializeAsync>d__2.MoveNext() in D:\Projects\Intern\SmartViewWebTrace\SmartViewWebTrace\SmartViewWebTrace\Form1.cs:line 34

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

119.0.2151.58

### SDK Version

1.0.1518.46

### Framework

Winforms

### Operating System

Windows 11

### OS Version

10.0.22621 build 22621

### Repro steps

Starting with msedgewebview2.exe in taskmanager - in my case, if I build my .net project, these processes appear and do not go away.
Run app with Windows.Form that has webview2 control.  Initialize webview2 with EnsureCoreWebView2Async and get exception.

### Regression

No, this never worked

**Comment by carrie-battaglia** [comment]
Are there any updates on this issue?  Thank you.
