### ISSUE TITLE
[Problem/Bug]: The WebView2CompositionControl throws a System.PlatformNotSupportedException with .NET 8

### ISSUE THREAD

**Issue by cmiles** [MicrosoftEdge/WebView2Feedback#4726]
### What happened?

In the 1.0.2646-prerelease the Wpf Microsoft.Web.WebView2.Wpf.WebView2CompositionControl throws a System.PlatformNotSupportedException.

System.PlatformNotSupportedException: Operation is not supported on this platform. (0x80131539)
at Microsoft.Web.WebView2.Wpf.WebView2CompositionControl.WebView2CompositionControl_Loaded(Object sender, RoutedEventArgs e)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)__

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Prerelease (Edge Canary/Dev/Beta)

### SDK Version

1.0.2646-prerelease

### Framework

WPF

### Operating System

Windows 11

### Repro steps

Use the WebView2CompositionControl in a .NET 8 WPF Application.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

[AB#53041634](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/53041634)

**Comment by victorhuangwq** [comment]
Does `WebView2CompositionControl` work on the release SDK?

**Comment by champnic** [comment]
This is resolved and should be available in the next pre-release SDK.
