### ISSUE TITLE
Event 1026, .NET Runtime Error when running a published application

### ISSUE THREAD

**Issue by dorofino** [MicrosoftEdge/WebView2Feedback#531]
Hi, 

After I publish and install the sample app WebView2WpfBrowser. 
I get the following error when I press the Go button and the application crash 

I can't determine the issue

![image](https://user-images.githubusercontent.com/1240729/95907995-63fab000-0d6a-11eb-8e13-63aa4bdd3cbd.png)

```
Application: WpfApp2.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(System.String, System.String, Microsoft.Web.WebView2.Core.Raw.ICoreWebView2EnvironmentOptions, Microsoft.Web.WebView2.Core.Raw.ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment+<CreateAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Web.WebView2.Wpf.WebView2+<>c__DisplayClass25_0+<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WpfApp2.MainWindow+<GoToPageCmdExecuted>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at System.Windows.Application.Run()
   at WpfApp2.App.Main()
```

**Comment by champnic** [comment]
What SDK version are you using?

**Comment by dorofino** [comment]
I'm running 0.9.579-prerelease.

**Comment by champnic** [comment]
Can you see if 0.9.628-prerelease solves this? We recently made some changes to how the WebView2Loader.dll gets deployed (which is I think what you may be seeing here).

**Comment by dorofino** [comment]
The issue I'm having with this version is that the webView does not render any content directly from <wv2:WebView2 **Source=""**, and when I press the "GO" button I get this other error.

![image](https://user-images.githubusercontent.com/1240729/95912896-70ced200-0d71-11eb-90ea-b6e37f4a1b40.png)

**Comment by DomenicoFormoso** [comment]
Similar problem with winforms. This morning it worked fine, now it doesn't work. The only thing I have changed on my pc is windows update:https://support.microsoft.com/it-it/help/4576947/kb4576947-cumulative-update-for-net-framework.

**Comment by dorofino** [comment]
> Similar problem with winforms:
> 
> ```
> async void InitalizeAsync()
> {
>     await webView.EnsureCoreWebView2Async(null)
>     ....
> }
> ```
> 
> fail and causes exit.
> This morning it worked fine, now it doesn't work. The only thing I have changed on my pc is windows update:https://support.microsoft.com/it-it/help/4576947/kb4576947-cumulative-update-for-net-framework.

That is a good clue, I have this update done back in Sep.

**Comment by champnic** [comment]
The BadImageFormatException is #431. You should be able to uncheck "Prefer32Bit" in build settings for the project, or build specifically x64 (instead of AnyCPU).

**Comment by dorofino** [comment]
> The BadImageFormatException is #431. You should be able to uncheck "Prefer32Bit" in build settings for the project, or build specifically x64 (instead of AnyCPU).

This change definitely fixed the issue with the **"await webView.EnsureCoreWebView2Async(null)"** and version version 0.9.628-prerelease.

I also published the project, and it ran flawlessly.

I belived this issue can be close from my end.

**Comment by champnic** [comment]
Great! Glad this is resolved.

**Comment by DomenicoFormoso** [comment]
I think I have found the cause of my problem, I am working with version 0.9.628-prerelease. The same project (compiled without the prefer 32 bit parameter) works fine on a pc with canary version 87.0.669. But it doesn't work well if on the same pc if I update edge canary to the version 88.0.670.
Thanks
