### ISSUE TITLE
load canary version

### ISSUE THREAD

**Issue by BugKiller-tech** [MicrosoftEdge/WebView2Feedback#870]
Webview2 is loading default edge browser installed on Windows.
How to load canary version with webview2 ? (I've already installed canary version on my windows)

Why I want to try canary version is because now app is crashing when browsing domain is changed.
How to fix the issue ?
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.Reload()
   at Microsoft.Web.WebView2.Core.CoreWebView2.Reload()
   at WebView2WindowsFormsBrowser.BrowserForm.BtnRefresh_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
WebView2WindowsFormsBrowser
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///E:/Work/C_sharp/WebView2WindowsFormsBrowser/bin/Debug/net462/WebView2WindowsFormsBrowser.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.721.0
    Win32 Version: 1.0.721.0
    CodeBase: file:///E:/Work/C_sharp/WebView2WindowsFormsBrowser/bin/Debug/net462/Microsoft.Web.WebView2.WinForms.DLL
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.721.0
    Win32 Version: 1.0.721.0
    CodeBase: file:///E:/Work/C_sharp/WebView2WindowsFormsBrowser/bin/Debug/net462/Microsoft.Web.WebView2.Core.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Symbai** [comment]
WebView2 looks at the most minimum version first, order is:

- WebView2 runtime
- Beta
- Dev
- Canary

The stable version of Edge (is that what you meant with "default"?) is NOT being used. If you have issues with not picking the right version, you can either uninstall whatever comes before your version. Or you distribute it using fixed runtime version by following the documentation.

**Comment by likuba** [comment]
The best way to tell it to use Canary instead of Stable is to tell WebView2 to reverse runtime lookup order. By default, the WebView2 runtime loader logic will try to use the most stable version of the runtime available: WebView2 Runtime > Edge Beta > Edge Dev > Edge Canary. You can reverse this order by setting an environment variable before initializing WebView2:
WEBVIEW2_RELEASE_CHANNEL_PREFERENCE = 1
This will make the search order Edge Canary > Edge Dev > Edge Beta > WebView2 Runtime. This means it will prefer Canary if you have it installed

Another option is to tell WebView2 which path to look for a runtime in. When creating the WebView2, you can specify the directory you want the loader to look for a runtime, using the browserExecutableFolder parameter when calling CreateCoreWebView2EnvironmentWithOptions. This can be flaky because the directories for the browser channels can include the version number, which won’t be correct when the channel updates on your machine. 

More info about these options can be found in our documentation:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.664.37#createcorewebview2environmentwithoptions
