### ISSUE TITLE
Make it easier to call javascript callback function from .NET host objects

### ISSUE THREAD

**Issue by mspaugh1** [MicrosoftEdge/WebView2Feedback#918]
**Problem:** HostObjectToScript throws exception when trying to execute a passed-in function

**Scenario:** WPF application has a WebView2 tab embedded and exposes an object for scripting using CoreWebView2.AddHostObjectToScript(). I'm able to access this object using Javascript:
```
window.blah = chrome.webview.hostObjects.sync.blah_blah_external;
```
and call functions without issue. Everything works just fine until I call a function that creates a class instance and passes in a function as parameter to that class. The parameters pass in just fine, but when the code tries to call the functions it throws the System.NotImplementedException exception. This worked just fine before replacing the IE-based browser control with WebView2, so I'm hoping it's something simple I'm missing.

**Environment:**

The Host object is exposed with this:
```
variablename.CoreWebView2.AddHostObjectToScript("blah_blah_external", new MYTABExternal(_tabHost));
```

The Host Object looks like this:
```
namespace MYTAB
{
    [ClassInterface(ClassInterfaceType.AutoDual)]
    [ComVisibleAttribute(true)]
    public class MYTABExternal
    {
        public void createTHING(String user, dynamic onError)
        {
            CLASSNAME currentCLASSNAME = new CLASSNAME(user, onError);
            currentCLASSNAME.create();
        }
    }
}
```
The class that throws the error is setup as such:
```
namespace MYTAB
{
    public class CLASSNAME
    {
       
        protected String user;
        protected dynamic onError;

        public CLASSNAME(String user, dynamic onError)
        {
            this.user= user;
            this.onError = onError;
        }

        public void create()
        {            
            BackgroundWorker backgroundWorker = new BackgroundWorker();
            backgroundWorker.WorkerSupportsCancellation = true;
            backgroundWorker.WorkerReportsProgress = true;
            backgroundWorker.DoWork -= backgroundWorker_DoWork;
            backgroundWorker.DoWork += backgroundWorker_DoWork;
            backgroundWorker.RunWorkerCompleted += backgroundWorker_RunWorkerCompleted;  //Tell the user how the process went
            RequestContext requestContext = EXTERNALLIBRARY.SharedContext.Instance;
            backgroundWorker.RunWorkerAsync(requestContext);
           
        }

        /// <summary>
        /// Fires when the background task is complete
        /// </summary>
        private void backgroundWorker_RunWorkerCompleted(object sender, System.ComponentModel.RunWorkerCompletedEventArgs e)
        {
            if (e.Cancelled)
            {
                this.onError("The creation process was cancelled"); // HERE'S THE EXCEPTION
            }
        }
...
```

The javascript to call the function is:
```
window.setTimeout(function () {
  window.blah.createTHING(btn.attr('data-requestor-user-id'), function (onErrorResponse) {
                                  dialog.$modal.addClass('type-danger');
                                  dialog.setMessage('<p>' + onErrorResponse + '</p>');
                                  spinner.stop();
  });
}, 1000);
```

Exception stack trace is:

```
Exception thrown: 'System.NotImplementedException' in System.Dynamic.dll
Exception thrown: 'System.NotImplementedException' in System.Dynamic.dll
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>BLAH</AppDomain><Exception><ExceptionType>System.NotImplementedException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>The method or operation is not implemented.</Message><StackTrace>   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Dynamic.ComRuntimeHelpers.GetITypeInfoFromIDispatch(IDispatch dispatch, Boolean throwIfMissingExpectedTypeInfo)
   at System.Dynamic.IDispatchComObject.EnsureScanDefinedMethods()
   at System.Dynamic.IDispatchComObject.System.Dynamic.IDynamicMetaObjectProvider.GetMetaObject(Expression parameter)
   at System.Dynamic.DynamicMetaObject.Create(Object value, Expression expression)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at MyTab.CLASSNAME.backgroundWorker_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\CLASSNAME.cs:line 145
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()</StackTrace><ExceptionString>System.NotImplementedException: The method or operation is not implemented.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Dynamic.ComRuntimeHelpers.GetITypeInfoFromIDispatch(IDispatch dispatch, Boolean throwIfMissingExpectedTypeInfo)
   at System.Dynamic.IDispatchComObject.EnsureScanDefinedMethods()
   at System.Dynamic.IDispatchComObject.System.Dynamic.IDynamicMetaObjectProvider.GetMetaObject(Expression parameter)
   at System.Dynamic.DynamicMetaObject.Create(Object value, Expression expression)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at MyTab.CLASSNAME.backgroundWorker_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\\CLASSNAME.cs:line 145
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()</ExceptionString><DataItems><Data><Key>ApplicationName</Key><Value>BLAH</Value></Data></DataItems></Exception></TraceRecord>
```

[AB#31841227](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31841227)

**Comment by champnic** [comment]
Hey @mspaugh1 - this is an interesting case! It looks like the onError is failing to call when backgroundWorker_RunWorkerCompleted is hit. The callback type of onError should be an IDispatch object under the covers, which has an Invoke(...) method on it for calling back into the JS function. In our C++ sample it looks like this:
```
STDMETHODIMP HostObjectSample::CallCallbackAsynchronously(IDispatch* callbackParameter)
{
    wil::com_ptr<IDispatch> callbackParameterForCapture = callbackParameter;
    m_runCallbackAsync([callbackParameterForCapture]() -> void {
        callbackParameterForCapture->Invoke(
            DISPID_UNKNOWN, IID_NULL, LOCALE_USER_DEFAULT, DISPATCH_METHOD, nullptr, nullptr,
            nullptr, nullptr);
    });

    return S_OK;
}
```

I'm not sure how this IDispatch object shows up in .NET (and dynamic is new to me). If you put a breakpoint on this.onError, what does it show up as in the debugger? What properties/methods does it have? My guess is that this probably needs to be changed to something like `this.onError.Invoke(...);`, thought I don't know exactly what format that would take.

@david-risney Any thoughts here?

**Comment by mspaugh1** [comment]
Thanks for the feedback and info. The onError and onCreated also throw the exception in the backgroundWorker_DoWork:

```
       private void backgroundWorker_DoWork(object sender, System.ComponentModel.DoWorkEventArgs e)
        {
            try
            {
                Dictionary<string, string> thing = doSomething;
                if (thing.ContainsKey("error"))
                {
                    this.onError(thing["error"]); // NotImplemented EXCEPTION HERE
                } else  {
                   //thing worked
                   this.onCreated(result); // NotImplemented EXCEPTION HERE
                }

            } catch (Exception ex) {
                this.onError(ex.ToString()); // NotImplemented EXCEPTION HERE
            }
        }
```

Of note for the conversation - If I call onCreated or onError in the createTHING() method (i.e. outside of the background worker) it doesn't throw the exception, but also doesn't do what it's supposed to do or fit into the flow. 

I'll grab some details on the onCreated and onError from the debugger and post here when I'm able.

Thanks again for thinking/digging!

**Comment by champnic** [comment]
Hey @mspaugh1 - Can you take a look at this example from another user?
https://github.com/MicrosoftEdge/WebView2Feedback/issues/75#issuecomment-711443711

It looks like you should be saving the callback as an object and then calling `InvokeMemberHelper.InvokeDispMethod(...)` with the callback. Want to give that a try?

**Comment by mspaugh1** [comment]
@champnic - wow, that did work! 

I pulled the idispatch from [here](https://gist.github.com/yizhang82/a1268d3ea7295a8a1496e01d60ada816), added the LOCALE_USER_DEFAULT const into InvokeMemberHelper and sent that into the disp.Invoke() method. I also had to add a null check to the GetDispID() method and viola.

```
    static class InvokeMemberHelper
    {
        // new const to store default locale
        private const int LOCALE_USER_DEFAULT = 0x0400;
...
        // sending LOCALE_USER_DEFAULT to avoid unknown locale issues
        try
                {
                    disp.Invoke(
                        (uint)dispId,
                        IID_NULL,
                        LOCALE_USER_DEFAULT,
                        flags,
                        paramArray,
                        out result,
                        out info,
                        out err);
                }

...
        // added null check below
        static uint GetDispID(IDispatch disp, string name)
        {
            uint[] dispid = new uint[1];
            if (name == null)
            {
                return dispid[0];
            }
```

I *think* I'll be ok going live with this as-is, but would love to roll the idispatc.cs out at some point. Is there progress on that front?

Thanks again for all the help!

**Comment by champnic** [comment]
Glad you're unblocked! As #75 is mostly focused on support for async .NET functions in host objects, I'm going to repurpose this issue into a feature request to improve the .NET callback experience. Thanks!

**Comment by dimmelsw** [comment]
@champnic 
Are there any news on this?

**Comment by ztanczos** [comment]
Hi @champnic ,

Is there any progress on this issue?
Also do you know the license for the workaround mentioned in this thread? I'm wondering if we could use that in the meantime.

Thanks,
  Zoltan

**Comment by champnic** [comment]
@ztanczos No progress on this one. Which workaround are you talking about? I don't believe there's a license associated with the code in https://github.com/MicrosoftEdge/WebView2Feedback/issues/75#issuecomment-711443711, and CEFSharp is a separate product so I don't know specifics for the license there.

**Comment by ztanczos** [comment]
@champnic I meant the code from [gist](https://gist.github.com/yizhang82/a1268d3ea7295a8a1496e01d60ada816): the custom IDispatch implementation.

**Comment by champnic** [comment]
Sorry I don't have any comment on the license of that code.

**Comment by novac42** [comment]
This fix is currently available in canary runtime and prerelease SDK and will soon be available in stable release this month.

**Comment by ztanczos** [comment]
Hi @novac42,
Can you please explain / point me to the documentation how can we call JS callbacks with the new prerelease sdk?

Thanks,
  Zoltan
